### ISSUE TITLE
Inconsistencies in our css

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1005]
CSS-stats shows that we have [quite a few inconsistencies in our won.css](http://cssstats.com/stats?link=https%3A%2F%2Fwww.matchat.org%2Fowner%2Fgenerated%2Fwon.css): e.g. *almost* identical colors, too many font-sizes (should be 6 max), an interesting array of z-indices, relatively high specificity, *almost* identical media queries, and a few spacing-reset.

We should work through these to improve the quality of our SCSS-codebase and improve maintainability.

**Comment by fkleedorfer** [comment]
We are working on that
