### ISSUE TITLE
Change need rdf structure to "is/seeks"

### ISSUE THREAD

**Issue by heikofriedrich** [researchstudio-sat/webofneeds#1009]
* we are changing the rdf structure of needs to have 2 parts "is" and "seeks"
* "is" describes the properties that relate to the offering of the need 
* "seeks" describes the properties that describe potential other needs which should be matched with this one
* this structure replaces the need types (e.g. demand, supply, dotogehter, critique) that we were using and became too inflexible for our purposes now
* further each need can have a MatchingBehavior entry with the following values: Mutual, Steahly, Lazy, DoNotMatch.
* Mutual: is the default => hints get send to both needs if one seeks caluse matches the other needs is clause
* DoNotMatch: do not sent hints neither to current need nor to other need
* Steahly: send hints only to current need, not to other need
* Lazy: send hints only to other need, not to current need

**Comment by soheilh** [comment]
It is not clear for me how these changes would be reflected in the GUI.

**Comment by heikofriedrich** [comment]
Currently in the GUI nothing changes. For now these are just structural changes. The GUI can be adapted later

**Comment by m0ru** [comment]
The pull-request #1025 adapts the create-need GUI to the is-seeks-structure and thus enables creating needs with the GUI again.

As of a78a6ec on `need-structure-impl_GUI`, the needs arrive in the state. "All that remains" is to look for all usages of `won:hasContent` and `won:hasBasicNeedType` in selectors, reducers and components and adapt them to the new structure.
