### ISSUE TITLE
webintents?

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1012]
Te should look into whether or not we want to use [web-intents](http://webintents.org/) for making interactions with other apps easier. Currently there's native support in Chrome and a shim for other browsers (that uses <http://webintents.org/>'s API though). 

This would give us a simple way to access and provide access for the following functionalities:

* Share (!)
* Edit
* View
* Pick
* Subscribe
* Save

**Comment by fkleedorfer** [comment]
+1 .. a possible lab-day project?

**Comment by fkleedorfer** [comment]
too old
