### ISSUE TITLE
FailureResponseEvent FailureMessage does not contain the exceptionclass

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#1016]
WonRdfUtils.MessageUtils.getTextMessage(((FailureResponseEvent) event).getFailureMessage())

generates a human readable textmessage including the exceptionclass as a text, we should refactor this so we have the exception class available aswell so we can use the instanceof operator to distinguish between the  different failureevent causes -> needed for factoryneeds that a bot did not remember yet but are already present in the node

**Comment by fkleedorfer** [comment]
That's not possible. We're operating on a String in that case.
