### ISSUE TITLE
wrong use of prefixed uris in owner app

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1018]
the owner application uses wrong URIs for need descriptions (more specifically, for describing the location)
instead of defining a prefix and using it, the URIs use the string inteded as the prefix as the schema, such as  `<s:GeoCoordinates>`

**Comment by m0ru** [comment]
Probably it isn't added to the `@context` in `buildMessageRdf`.

**Comment by fkleedorfer** [comment]
Here is an example: https://node.matchat.org/won/resource/need/6883144902980285000

**Comment by m0ru** [comment]
Also things like `<s:Place>` and `<s:GeoCoordinates>` shouldn't happen -- they shouldn't have the parantheses.
