### ISSUE TITLE
use ng-bind instead of expressions.

### ISSUE THREAD

**Issue by sbyim** [researchstudio-sat/webofneeds#102]
from https://docs.angularjs.org/api/ng/directive/ngBind

"It is preferable to use ngBind instead of {{ expression }} if a template is momentarily displayed by the browser in its raw state before Angular compiles it. Since ngBind is an element attribute, it makes the bindings invisible to the user while the page is loading".

**Comment by quasarchimaere** [comment]
this is regarding the old ui -> close
