### ISSUE TITLE
Sign-up: Clearer feedback if account-name is already in use

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1035]
Currently the feedback is small print below the account-name. We might want to make it more visually distinct or move it closer to the button / also change the button, that people have clicked directly before to reduce the likelyhood of missing error/recovery-message.

**Comment by m0ru** [comment]
Also it should be phrased as recovery-path instead of as error (or contain a recovery-path at least):
e.g. "This email is already in use. Click [here to sign in]() instead (or [here to reset your password]() if you've forgotten it)."

**Comment by peacememories** [comment]
What needs to be clarified about this issue?

**Comment by quasarchimaere** [comment]
@peacememories i just think whether or not we do it soon, later or close it

**Comment by quasarchimaere** [comment]
imma move this to later

**Comment by quasarchimaere** [comment]
moved to internal kanban board
