### ISSUE TITLE
contenteditable/medium.js: sometimes not all lines are `<p>`s

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1042]
sometimes in chrome (when typing fast?) i get the following
```
<div class="medium-mount Medium Medium-partial" contenteditable="true">
  <p class="medium_title">&nbsp;asdf #asdf</p>
  qwerqwer #qwer qwerqwer
</div>
```
Which causes the parsing of the description and it's tags to fail (silently), as the selector `'.medium-mount p'` doesn't match the last line that isn't wrapped in a `<p>`-tag.

**Comment by m0ru** [comment]
can't reproduce it atm :|

**Comment by quasarchimaere** [comment]
no longer relevant as we removed medium.js from our codebase
