### ISSUE TITLE
Title ends with `<br>`

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1052]
Not every title, but almost every title I create in the GUI is somehow transformed to have trailing `<br>`

**Comment by m0ru** [comment]
One way to reproduce this, is to type "asdf #asdf" (without ending in a linebreak). The tag will will then contain a "<br>"

**Comment by fkleedorfer** [comment]
or to use firefox

**Comment by m0ru** [comment]
ah, yes, the problem is FF specific.
