### ISSUE TITLE
message view does not scroll down to newly received message

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1053]
on #1024, in Firefox. 
Steps to reproduce: chat with the debug bot, scroll down to the last message, then say: `send 9`. Wait for the messages to arrive. The view will not be scrolled down the the last message received.
![grafik](https://cloud.githubusercontent.com/assets/551624/24996942/17415140-2035-11e7-8c3f-8be9d6cec525.png)

**Comment by m0ru** [comment]
There might be some problem with how the $watch interacts with the state-updates.

**Comment by m0ru** [comment]
The problem seems to be, that the call to `updateScrollposition` -- even though delayed -- seems to trigger after angular renders the list of messages to the DOM. Thus it scrolls to the bottom of the list and *then* angular adds the latest message.
