### ISSUE TITLE
Async tasks in seperate thread/worker

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1054]
Move rdf-processing to seperate thread/worker to avoid the GUI freezing up while the data for an account with a lot of needs/connections is loaded. Atm one can't even sign out.

Then again, we probably should first improve the selective loading.

**Comment by quasarchimaere** [comment]
currently not possible with our rdfstore library as we can't move all the necessities into a worker thread due to the used functions and vars (global scope and stuff)

**Comment by fkleedorfer** [comment]
Agreed - we looked into it and it's not feasible currently.
