### ISSUE TITLE
Smarter "show more"

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1056]
When the first message is visible, "show more" shouldn't be displayed. It would be even nicer, if it would list the number of remaining messages (or days worth of messages to make this time-based, which would probably be even more useful)

**Comment by m0ru** [comment]
Can't fix that atm the way it should be fixed, i.e. by daisy-chaining through the messages, as the debug-bot, doesn't append the `hasPreviousMessage` triples.

A different way to go about this, would be to check if all events of a connection are also in the state.

**Comment by m0ru** [comment]
@fkleedorfer suggested another, even easier solution: the first message always is message with appended text and of type "connect-message"

**Comment by m0ru** [comment]
loading the full event-container once would have a side-benefit: by knowing how many url's there are, we could show how many events could be shown.

**Comment by m0ru** [comment]
@fkleedorfer mentions, that ld-paging also has facilities for this, i.e. there should be a "previous-page" pointer, if there's still pages remaining or not if we've reached the earliest page.

**Comment by fkleedorfer** [comment]
https://github.com/researchstudio-sat/webofneeds/blob/master/webofneeds/won-node-webapp/doc/linked-data-paging.md - see the examples

**Comment by m0ru** [comment]
btw, how do we deal with breaks in the chain / there's events that don't have a previous message but defenitely aren't the first message? can this happen?

**Comment by m0ru** [comment]
The easiest solution: hide the button, when the connect-message is loaded.

**Comment by fkleedorfer** [comment]
It could also be an open-message
