### ISSUE TITLE
Missing border when list on the left-side is longer than the chat

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1078]
When the list on the left-side is longer than the chat, the lack of a border on the right edge of selected items (intended to deal with the problem above) becomes apparent. No idea, how we can fix this without having double borders (see #1077)

**Comment by quasarchimaere** [comment]
there is no need in this, there will be no border issue if the chat window "snaps" into the view, and leave the rest of the content (excluding the header) scrollable, however this is not the case right now, it would only be a "simple" solution for the problem, and as far as i am concerned this was also intended that way bye the ui-design
