### ISSUE TITLE
Host Own Nominatim Server (oldtitle: Adherence to nominatim usage policy)

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1094]
Amongst others, the [Nominatim usage policy](https://operations.osmfoundation.org/policies/nominatim/) lists auto-complete search as unnacceptable usage. also it states a hard limit of one request per second. We should also send some sort of ID identifying it as use by matchat.org.

related to #1095

child of #2820

**Comment by m0ru** [comment]
@ waffle discussion column tagging: what's the question to be discussed here? :)
(this is design work that's open imo)
if the question is whether or not we should (given time) then that's a definitive yes. ultimatively we won't get around running our own services for that :)

**Comment by sigpie** [comment]
Right now, we're not adhering to the usage policy at all, which means that nominatim might block us eventually. (auto-completing search, more than 1 request/second). I'm not convinced that we can adhere to the policy without big changes, it probably would be easier to run our own instance as @m0ru suggested.

Nominatim suggests https://geocoder.opencagedata.com and https://locationiq.com as alternative providers. As far as I can tell, both impose the 1 request/second limit on free accounts, which means that we would need to get a paid subscription if we want to keep searching for locations reasonably responsive.

**Comment by peacememories** [comment]
@fkleedorfer does it seem reasonable for us to run a Nominatim instance in the future? If  so I would move this to "soon" or "later", if not we should debate different options or close this and create a new issue to "find ways to adhere to Nominatim usage policies"

**Comment by fkleedorfer** [comment]
Let's look into hosting the data and see how much time we spend doing that

**Comment by quasarchimaere** [comment]
moved to internal kanban board
