### ISSUE TITLE
Back-Button in post-view not always leading back

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1096]
Currently it always leads to the post-overview, even when people started out in the feed view.

**Comment by heikofriedrich** [comment]
this is quite irritating, happens to me in firefox

**Comment by heikofriedrich** [comment]
I think this happens when you follow a HTML link to matchat. then the back-button doesnt work anymore. this happens on our git hub page where a lin to matchat is: https://github.com/researchstudio-sat/webofneeds. i also tested with another html document with a link to matchat. same happens there!

**Comment by quasarchimaere** [comment]
is duplicate of #1312
