### ISSUE TITLE
Avoid reloading connection / additional server-roundtrip in incoming message handlers

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1101]
Atm most message-handlers in the client refetch the entire connection instead of just using the events it gets as part of the message and updating the connection state as appropriate. This incurs a severe performance penalty as at least a full server-roundtrip is needed till the GUI updates.

#1100 already avoids this for incoming requests. The should be done for all message types though, ideally together with the refactoring described in #1098 and #1099.

**Comment by m0ru** [comment]
#1125 documents a flaw with the implementation of `connectMessageReceived` that should be fixed before using that as a blueprint / abstracting the functionality into a generic message handling function.

**Comment by fkleedorfer** [comment]
Done
