### ISSUE TITLE
Needless rerenders - ngrepeat for immutablejs

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1104]
Probably due to the conversion from immutablejs-collections to arrays the object references change a lot and needless rerenders are caused. E.g. for the chat, when I register a listener for `DOMSubtreeModified` （as seen below), typing a single letter in the chat textfield causes some 30 events, probably one per child that changed, even though there hasn't changed *anything* about the chat messages displayed in the list!

```
$0.addEventListener('DOMSubtreeModified', () => console.log("CHAT has changed - DOMSubtreeModified"))
```

There's a plugin for angular that allows iterating over immutablejs-collections. We should use that.

**Comment by fkleedorfer** [comment]
@m0ru still an issue?

**Comment by m0ru** [comment]
yes, sadly. it's probably part of the reason why our app is needlessly performance-heavy.

didn't get the plugin to work at that time, tho. we can retry or defer this till the switch to react (and typescript #1130) or, even better, elm. these don't have that problem and  should provide a relatively large performance gain.

**Comment by m0ru** [comment]
I'd move this to "later" (if we want to fix that performance sink in angular) or close it, as the switch will solve this by itself (iff we are sure we'll switch). alternatively we can also decide this along with the decision to switch.

**Comment by quasarchimaere** [comment]
afaik the issue lies in the rdfstore.js so switching to elm or react probably does not help us, also when was it ever more than an idea to switch to react or even elm?

**Comment by quasarchimaere** [comment]
i retract my former statement, the issue lies within the constant unnecessary ng-repeats etc. due to our immutable state, we will hopefully change our frontendarchitecture soon

**Comment by quasarchimaere** [comment]
moved to internal kanbanboard
