### ISSUE TITLE
Font-size on FF

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1112]
![image](https://cloud.githubusercontent.com/assets/1730492/26625400/421ad1f4-45f4-11e7-877f-b318355e85ec.png)

I'm usually zooming to ~130% on FF on our 4k displays. We should fix it in a way that it looks legible on all browsers and screen sizes.

**Comment by quasarchimaere** [comment]
i think this isnt an issue anymore, zooming to 125% in chrome or firefox looks fairly ok -> closing this issue
