### ISSUE TITLE
In gulpfile, cannot find ./jspm_packages/system.js

### ISSUE THREAD

**Issue by bshambaugh** [researchstudio-sat/webofneeds#1115]
A gist containing the stack trace of this error is here:

https://gist.github.com/bshambaugh/bdd5d4f70afde3abc2ea513c9fc2e69e

**Comment by fkleedorfer** [comment]
Hmm - I see this for the first time. @m0ru?

**Comment by m0ru** [comment]
Hm, weird...
Have you tried deleting `jspm_packages` and rerunning the build?

Alternatively, can you run `npm install` (or `./node_modules/.bin/jspm install`) manually and see if the file is there afterwards? if so it could be an issue with (our usage) of frontend-maven in regard to `jspm install`.

For debbugging I cloned the repo freshly and maven pulled the same version of frontend-maven, so it must be something else. What maven version are you using @bshambaugh?

**Comment by bshambaugh** [comment]
I'll dive in. For now, I put these in my environment:

apache-maven-3.3.3  jdk1.8.0_121

**Comment by quasarchimaere** [comment]
no longer relevant... right? @m0ru

**Comment by m0ru** [comment]
yep, we're using webpack now
