### ISSUE TITLE
Is it possible for the same person to create needs and wants and have matching?

### ISSUE THREAD

**Issue by bshambaugh** [researchstudio-sat/webofneeds#1116]
I could not get matches with a creation of needs and wants, when they were both created by me. I got them with the debugger.

Here are some screenshots illustrating this:

http://raptorlicious.blogspot.com/2017/06/won-screenshots-cont-2.html

**Comment by fkleedorfer** [comment]
Matches between the needs of the same owner are filtered out. Neither matchers nor WoN nodes can do that becauss they only see needs, but they don't have any information about owners/useres. Therefore, the owner application has to do the filtering.

**Comment by fkleedorfer** [comment]
For testing purposes, create a need with another account. If you want to see both sides at rhe same time, either use a different browser or log into your second account using the the 'private mode' of your browser

**Comment by bshambaugh** [comment]
This seems to be done. Thus I am closing this issue. Screenshots are here:
http://raptorlicious.blogspot.com/2017/06/won-apples-to-apples-recompiled-final.html

 I see client side browser certs and self-signed certificates as a separate issue.

**Comment by fkleedorfer** [comment]
Definitely a different issue.
