### ISSUE TITLE
Push received connect messages into rdf-store

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1125]
`connectMessageReceived` in `messages-actions.js:220` has recently been implemented and avoids refetching the entire connection as the other message handlers do (thus avoiding the needless server-roundtrip!). However, the way it's been implemented, the messages never are stored in the rdf-store. Thus they'll needlessly be fetched the next time the message is queried, even though the client already has the information. So to finish this function, the json-ld of the messages should also be pushed to the rdf-store.

**Comment by fkleedorfer** [comment]
Done
