### ISSUE TITLE
Client doesn't generate hasPreviousMessage triple

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1127]
Some events are stored in the state directly (instead of fetched from the node after posting them there). As the  `hasPreviousMessage` triples are generated on the node, the resulting events in the state don't contain that field, making daisy-chaining impossible.

The imperformant, but faster-to-implement way to fix this, would be to fetch every event after posting it. It would be better though, to generate the `hasPreviousMessage` triples already on the client.

**Comment by fkleedorfer** [comment]
whichever way we do it, it works now. the chat isn't particiularly slow.
