### ISSUE TITLE
Typescript/Elm

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1130]
The type-system provided by typescript would help us avoid many bugs and it's a rather low hanging fruit to switch to it from javascript, as it's a superset of the latter.

**Comment by m0ru** [comment]
Apparently `typings` has been deprecated in favour of `npm install @types/pkgname`. Gotta find out how well this plays together with `jspm` (at the worst case we'll have to align versions, as we would have with typings)

**Comment by m0ru** [comment]
hm, the compiler/linter intellij uses seems to run on different/stricter defaults than our project (it builds via gulp, but intellij highlights a lot of things as compiler-errors)

**Comment by m0ru** [comment]
Also, the typesystem doesn't seem to take hold, when compiling via gulp/jspm. I can put the following in our app_jspm and it still compiles:
```
function foo(bar: string) {
    console.log(bar);
}
foo(123)
```

**Comment by m0ru** [comment]
one very far-fetched option here, would be to change the build-setup, and drop jspm in favour of a custom setup with npm, systemjs and possibly [cbuild](https://github.com/charto/cbuild) (that promises faster build-times when bundling(!))

**Comment by fkleedorfer** [comment]
I am not really in favour of changing the build process if we can avoid it.

**Comment by m0ru** [comment]
After trying a few different build combinations and failing, I think doing this in two stages (compile ts->js, then bundle via jspm) might be the most viable solution, unless we want to move away from jspm/systemjs.

Example setup for the two-stage-process: <https://stackoverflow.com/questions/34614743/how-to-prepare-release-version-with-systemjs-and-gulp>

**Comment by m0ru** [comment]
The example in the typescript documentation uses browserify (<https://www.typescriptlang.org/docs/handbook/gulp.html>) respectively webpack for bundling (https://www.typescriptlang.org/docs/handbook/react-&-webpack.html)

**Comment by m0ru** [comment]
Using two-step compilation, i got it working to the extend that a dummy-app.ts compiles and can import utils.js and angular. Open issues:

* [ ] get type-declarations (e.g. for angular) to cause compiler-errors when those libs aren't used correctly
* [ ] keep source-maps intact during 2-step compilation (atm you will see the intermediate code, i.e. the `tsc`-output when you open the dev-tools)
* [ ] gradually migrate `app_jspm.js` to `app_jspm.ts`

**Comment by m0ru** [comment]
As getting the source-maps to work properly is probably a lot of work, the migration will be postponed until either the [issue with jspm-typescript](https://github.com/jspm/jspm-cli/issues/2323) will be fixed or we decide to migrate the whole build to webpack.

**Comment by m0ru** [comment]
[fabiandev/jspm-tsc-update](https://github.com/fabiandev/jspm-tsc-update) mentions listing all your packages in tsconfig.json, which the tool does automatically. We could try using this.

**Comment by m0ru** [comment]
@aluanhaddad mentions a possible solution using the `concurrently` package [here](https://github.com/jspm/jspm-cli/issues/2323#issuecomment-322680340)

**Comment by aluanhaddad** [comment]
Greetings, @m0ru. My suggestion was about running the typechecker independently of and alongside JSPM.

Acquiring and provisioning declarations is a separate and difficult problem. 

https://github.com/fabiandev/jspm-tsc-update is something I have not yet had time to investigate, but plan to look at in great detail in the coming month. It appears maintain and generate some of the boilerplate that I am about to suggest.

In the past, the approach I have used is writing paths configuration, manually. It is annoying, but is also less work than it seems like at first glance.

Consider https://github.com/moment/moment which ships its own, highly accurate type declarations:
**tsconfig.json**
```js
{
  "extends": "./tsconfig.paths.json",

  "compilerOptions": {
    "module": "system", // or "es2015" or "esnext"
    "allowSyntheticDefaultImports": true, // enabled by when `"module"` is `"system"`
    "target": "es5",
    "strict": true
  }
}
```
**tsconfig.paths.json**
```json
{
  "compilerOptions": {
    "moduleResoltion": "node",
    "baseUrl": "./",
    "paths": {
      "moment": ["jspm_packages/npm/moment@2.18.1"],

      "app/*": ["src/*"]
    }
  }
}
```
**config.js** (jspm.config.js in jspm@0.17.0-beta.*)
```ts
SystemJS.config({
  "transpiler": "plugin-typescript",
  "typescriptOptions": {
    "tsconfig": true
  },
  "paths": {
    "app/": "src/",
    // etc.
  },
  "map": {
    "moment": "npm:moment@2.18.1",
    // etc.
  }
  packages: {
    "app": {
      "format": "esm",
      "main": "main.ts",
      "defaultExtension": "ts",
      "meta": {
        "*.ts": {
          "loader": "plugin-typescript"
        }
      } 
    }
  }
});
```

I wrote a tool specifically for https://github.com/aurelia that generates the above paths for aurelia packages. (Aurelia has an official story for installing declaration files but it uses _ambient_ external modules and that fails in multi-version scenarios.

**Comment by m0ru** [comment]
Awesome, thx :)
I'll give this a try in one of the next sprints :) (we're currently working on some other features)

**Comment by m0ru** [comment]
Important TODO here: in the [Elm Europe 2018 keynote](https://youtu.be/PCmfuYymySE?t=3645) Evan mentions that he has problems finding companies that have tracked number of bugs and hours spend (and thus costs incurred) fixing bugs for non-Elm and Elm-projects. Can we supply that data without too much effort? we might need to link github-issues to zep-hours. afair @quasarchimaere already does so, or not?

**Comment by quasarchimaere** [comment]
moved to our internal kanban board
