### ISSUE TITLE
typing gets slow as conversation gets long

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1137]
To reproduce, 
1. connect to the debugbot
2. observe how typing a message to the debugbot is not slow
3. type 'send 9' a couple of times, wait until the bot has sent its messages.
4. observe that typing a message to the debugbot is slower now

**Comment by fkleedorfer** [comment]
@quasarchimaere thinks it seems related to #1109

**Comment by quasarchimaere** [comment]
no longer relevant due to state change PR
