### ISSUE TITLE
Structure of rescal matching matrix files

### ISSUE THREAD

**Issue by heikofriedrich** [researchstudio-sat/webofneeds#1151]
> Naming of matrices is arbitrary apart from the connection.mtx matrix, which
> contains the target relation to predict. Entities in headers.txt are
> prefixed either as needs (instances of won:Need) or attributes (everything
> else?).
> 
> So there is no need to distinguish between demands and offers (both are
> needs)? How do you then prevent predicting links between two demands or
> between two offers? In my case, I can treat both contracts and bidders as
> needs, while everything else can be an attribute. Would that be OK?

**Comment by heikofriedrich** [comment]
Thats right, the only file name "connection.mtx" is currently hardcoded. Every other matrix file is passed dynamically.
In the header file the entities can either be needs or attributes (everything else but needs). The entries there have to be prefixed with either 'Need:' or 'Attr:' (see issue TODO).
There is no distiguish between demand and offer (these types have been removed from our structure, see #1024), links between all "kind" of needs can be predicted by rescal. If you need some filtering (e.g. contracts should not be matched with other contracts or bidders not with other bidders) then this has to be detected later in processing e.g. after reading the predicted hints.mtx file by your matcher and before sending out hint messages.

**Comment by jindrichmynarz** [comment]
Predicting links between all needs and only then discarding the links between the incompatible needs seems computationally wasteful. Maybe we should investigate how to use RESCAL with constraints.

**Comment by heikofriedrich** [comment]
RESCAL anyway in one run computes all predictions of the whole matrix. If you would want to restrict it i guess you would have to decrease the size of the matrix/tensor by removing entities/attributes. After the predictions are computed we can then decide which predictions should actually be treated as hints (either in the python program or later in the java matcher). This is related to issue #1156
