### ISSUE TITLE
RESCAL bit mask 

### ISSUE THREAD

**Issue by heikofriedrich** [researchstudio-sat/webofneeds#1156]
> As I mentioned, I don't quite understand the purpose the mask matrix (
> https://github.com/researchstudio-sat/webofneeds/blob/master/webofneeds/won-
> matcher-rescal/src/main/python/tools/tensor_utils.py#L212-L239) serves.
> This seems to guide the evaluation on the test/train split. It would be
> great if you can explain it a bit more.

**Comment by heikofriedrich** [comment]
This mask matrix is used to restrict the possible hint predictions between matrix entries (e.g. needs). For all the positions in the matrix with value 1 hints can be calculated (but do not have to be). For example one could have different kinds of needs e.g. in your case contracts and bidders and doesnt want that hints will be predicted between the same kind of these needs (contracts - contracts or bidders-bidders). Then you would set 1 entries in the matrix only between contracts and bidders and omit them between contracts and contracts or bidders and bidders. 
You can see that this matrix is used here: https://github.com/researchstudio-sat/webofneeds/blob/master/webofneeds/won-matcher-rescal/src/main/python/tools/tensor_utils.py#L189-L210. The filtering of predictions according to this hint matrix is achieved by the multiplication in line 208.

I now see this relates to your former question in #1151. This is actually the place where you could build in such a filtering and avoid hints between contracts for instance. However this would be custom code and if you need such a filtering we should think a way to realize this in a general reuseable way (e.g. by maybe passing such a matrix or similar structure to the python program)

**Comment by jindrichmynarz** [comment]
So by default the [mask matrix is created](https://github.com/researchstudio-sat/webofneeds/blob/master/webofneeds/won-matcher-rescal/src/main/python/tools/tensor_utils.py#L212-L239) for all pairs of needs (i.e. entities prefixed by "Need:" in the headers.txt file) minus the pairs, for which a connection already exists?

Do I then understand it correctly that the mask matrix doesn't have to do with cross-validation (i.e., withholding the connections the prediction of which is then evaluated)?

**Comment by heikofriedrich** [comment]
Yes thats all right. 
However this matrix could also be used for cross-validation purposes during testing.

**Comment by jindrichmynarz** [comment]
How would you use the mask matrix for cross-validation? I thought it is only used for post-processing the results of RESCAL. I believe that for cross-validation, you'd need to withheld the test connections from the connections matrix. For example, you'd set 20 % of the known connections to be zero.

**Comment by heikofriedrich** [comment]
i mean you are totally right, i just meant you can use a mask matrix and by multiplication during pre-processing filter entries from the connection input matrix. i meant the same but didnt express myself clearly

**Comment by jindrichmynarz** [comment]
Would matrix multiplication be better for setting the test partition of connections to zero instead of iterating through non-zero entries in the matrix and reseting some of them?

**Comment by heikofriedrich** [comment]
i just checked how i did that during my evaluations, and i also iterated over the entries. actually i dont know what is faster but often these matrix operations can be handled quite efficiently too
