### ISSUE TITLE
Following  #1152, a thread to understand RESCAL

### ISSUE THREAD

**Issue by bshambaugh** [researchstudio-sat/webofneeds#1165]
Hello all:

I traced RESCAL back to Nickel et al.'s paper, "A Three-Way Model for Collective Learning on Multi-Relational Data" [1]. It is used in the Factorizing YAGO paper, and I believe it is the basis for the EX-RESCAL (extended RESCAL) used in WoN. 

RESCAL seems quite popular as it was the first result when searching for machine learning and linked data. It was also developed quite close to Austria, in Bavaria, although the lead author is now doing AI work for Facebook in New York City (inferred from his Twitter).

I am presently trying to verify whether equation 2 is minimizing over factor matrices A and R sub k. 

[1] http://www.icml-2011.org/papers/438_icmlpaper.pdf

This is a similar domain to #1152

**Comment by bshambaugh** [comment]
It's probably understandable from the code somewhere.

**Comment by heikofriedrich** [comment]
@bshambaugh Your question is specific to the mathematics of the RESCAL algorithm. We are just using RESCAL in our matcher. You should therefore check out the RESCAL papers or their repositories if you are interested in implementation details. Here are some resources:

- Maximilian Nickel, Volker Tresp, Hans-Peter Kriegel Factorizing YAGO: Scalable Machine Learning for Linked Data in Proceedings of the 21st International World Wide Web Conference, 2012, Lyon, France
- Maximilian Nickel, Volker Tresp, Hans-Peter Kriegel A Three-Way Model for Collective Learning on Multi-Relational Data in Proceedings of the 28th International Conference on Machine Learning, 2011 , Bellevue, WA, USA.
- Nickel, Maximilian. Tensor factorization for relational learning. Diss. München, Ludwig-Maximilians-Universität, Diss., 2013, 2013.
- Zhiltsov, N., Agichtein, E. Improving Entity Search over Linked Data by Modeling Latent Semantics. Proceedings of the International Conference on Information and Knowledge Management (CIKM 2013). ACM, 2013.
- RESCAL implementation: https://github.com/mnick/rescal.py
- https://github.com/mnick/scikit-tensor
- RESCAL implementation extension: https://github.com/nzhiltsov/Ext-RESCAL

**Comment by bshambaugh** [comment]
Thanks for the links!
