### ISSUE TITLE
More expressive page titles

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1168]
Atm all views have "Web of Needs" as title. However, the favicon is enough indication, that a tab shows matchat and we could use the title, to show more expressive information, e.g.: "My Posts" or "Need a Couch for new flat" or "Chat with 'Need a Couch...'".

This would also improve the logging information in piwik. Make sure that the title change happens before the routing-logger in piwik.js, however.

related to #2658

**Comment by fkleedorfer** [comment]
Agree. Also, I'd like the number of unseen events in brackets in the title.

**Comment by quasarchimaere** [comment]
> Agree. Also, I'd like the number of unseen events in brackets in the title.
already included in #2658

**Comment by quasarchimaere** [comment]
moved to internal kanban board
