### ISSUE TITLE
Can't see own request text in outgoing request

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1172]
![no chat message on outgoing request](https://user-images.githubusercontent.com/1730492/28428034-57895eb0-6d78-11e7-9fd3-1e460aa9ec5e.PNG)

**Comment by m0ru** [comment]
Was missed when merging the pull-request, as the debug-bot accepted too quickly and i didn't check with 2 accounts and a matcher. We could add a command to the debug bot, to turn accepting requests off and on.

**Comment by quasarchimaere** [comment]
see behaviour of messages.connectMessageReceived (need-reducer.js), we need to add the addMessage (with an event from the payload) in the corresponding actionType of a sentRequest -> possibly right within case actionTypes.messages.connect (need-reducer.js) after the connection was put in the state

**Comment by quasarchimaere** [comment]
seems to be fixed, saw the text while making an adhoc connect -request
