### ISSUE TITLE
MMB to open new tab

### ISSUE THREAD

**Issue by pheara** [researchstudio-sat/webofneeds#1181]
The changes introduced by the privateId-pullrequest removed the `ui-sref` and thus `href` from a lot of hyperlinks (by using `ng-click="self.router_stateGo*(...)"` instead. This, however, means that those links don't react to the the middle-mouse-button anymore. 

Since then (i.e. in commit 9184c07), I've written a few utility-functions in `sref-utils.js`, that generate the strings needed by `ui-sref` without needing to manually bind the `privateId` in every link. Using these we can change make sure, that all elements that change the route allow opening new tabs via mmb-click.

requires #2283

**Comment by quasarchimaere** [comment]
is thist still an issue?

**Comment by fkleedorfer** [comment]
@m0ru?

**Comment by m0ru** [comment]
Yep, just try mmb- or ctrl-clicking anything in the app ^^

**Comment by quasarchimaere** [comment]
AFAIK if we remove all the privateId parameters except when accessing it from scratch (see requires #2283) we do not need the privateId in the url anymore and could probably close/retest this issue
