### ISSUE TITLE
Landing Page » Slider for Comic Strip position should not be remembered

### ISSUE THREAD

**Issue by thistis** [researchstudio-sat/webofneeds#119]
Clicking on a hotspot in the landing page will open up a comic strip below. The slider can be used to see the whole image.
Closing a comic strip and opening another strip will show the slider at the same position as the previous strip. 

A first comic strip is opened and the slider is set to the middle of the comic strip. The comic strip is then closed again by pressing the x.
![slider1](https://cloud.githubusercontent.com/assets/7766513/4627176/8c352de0-5388-11e4-91d1-fd8fbf873494.PNG)

Another comic strip is opened and its slider is at the same position as the previous strip, but should be at the beginning to read the comic in a chronological order.
![slider2](https://cloud.githubusercontent.com/assets/7766513/4627196/ba1286ea-5388-11e4-922a-c22ca5c76a5f.PNG)

The position should be resetted each time a comic strip is opened.

**Comment by quasarchimaere** [comment]
no longer relevant because of the new gui implementation
