### ISSUE TITLE
Use $transitions and AuthService

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1195]
Ui-Router 1.* deprecated the $stateChange* events, but provides
a shim for migrating with minimal effort. In the long-run
we should use ui-router's own, new access-control-system
and the `$transition`-API.

An example for a migration path can be found [here](https://ui-router.github.io/guide/ng1/migrate-to-1_0#state-change-events).

**Comment by fkleedorfer** [comment]
@m0ru still an issue?

**Comment by m0ru** [comment]
yep it is. then again angular 1.x is deprecated in general. i think we can close this issue as we'll need to change the entire thing anyway (or defer the decision until we get around to switching to ts+react or elm)

**Comment by fkleedorfer** [comment]
closed as it is just one symptom of our need to update angular (or get rid of it)
