### ISSUE TITLE
Gzip served content on owner-server

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1198]
[As](https://github.com/researchstudio-sat/webofneeds/issues/546#issue-155504563) [discussed](https://github.com/researchstudio-sat/webofneeds/issues/546#issuecomment-327726446) [in](https://github.com/researchstudio-sat/webofneeds/issues/546#issuecomment-327782245) #546, we need to enable gzip-encoding in tomcat (and possibly nginx). This will reduce the app-bundle's size by about 1M/73% and thus significantly speed up the page load.

**Comment by m0ru** [comment]
I've enabled gzip-compression on my localhost, by adding the following to lines to the `Connector`-declarations in my `$TOMCAT_HOME/conf/server.xml`:

```
<Connector
    compression="on"
    compressableMimeType="text/html,text/xml,text/plain,text/css,text/javascript,application/javascript"
   .../>
```

Afterwards, I've run the same experiment as listed [here](https://github.com/researchstudio-sat/webofneeds/issues/546#issuecomment-327556409), i.e. hard-reloading the landing page with throttling set to "fast 3g" (1Mb/s down, 750kb/s up, 40ms RTT) while logged out.

**Before:**

![loading_landingpage_-_good_3g](https://user-images.githubusercontent.com/1730492/30125633-4b3c6742-9339-11e7-9b94-80d9853cf306.PNG)

**After:**

![loading_landingpage_-_good_3g_-_with_gzip](https://user-images.githubusercontent.com/1730492/30169001-61dd35f0-93eb-11e7-9cf7-27773ef40614.PNG)

As you can see, page-load has improved from 12.5s to about 8.5s (without fonts; 16s to 14s with them), thus yielding roughly a **4s improvement (32% of load-time)** to first meaningful render (i.e. till text and buttons of the landing page are visible, even if just with a backup-font)

**Comment by fkleedorfer** [comment]
As we do have rather large RDF documents sometimes, it's worth adding those MIME types too - see https://github.com/researchstudio-sat/webofneeds/blob/bb732eb9080551838a1f72636e8042cc0bf67f55/webofneeds/won-core/src/main/java/won/protocol/rest/RDFMediaType.java

**Comment by heikofriedrich** [comment]
also i think enabling the gzip on the wonnode server (not only the owner) could improve performance too if we gzip the rdf documents

**Comment by fkleedorfer** [comment]
Done
