### ISSUE TITLE
Landing Page » View should adjust after opening/closing comic strips

### ISSUE THREAD

**Issue by thistis** [researchstudio-sat/webofneeds#120]
Clicking on a hotspot in the image on the landing page should let the view slide down to focus on the comicstrip. How it should be:

Before clicking on the blue spot
![before](https://cloud.githubusercontent.com/assets/7766513/4627399/d46d162a-538a-11e4-9f56-e4dd903ffac7.PNG)

After clicking on it, the view slides down so that the comic strip is in the center
![then](https://cloud.githubusercontent.com/assets/7766513/4627403/e2e34ecc-538a-11e4-9251-0f0c65146aa5.PNG)

Closing the comic strip by clicking the x should restore the former view by sliding up again (currently the strip gets transparent and the view abruptly jumps up again, this movement should be more subtle and soft)
![before](https://cloud.githubusercontent.com/assets/7766513/4627423/15dd23de-538b-11e4-9d4c-d24fe9fd83fd.PNG)

**Comment by quasarchimaere** [comment]
no longer relevant because of the new gui implementation
