### ISSUE TITLE
whatsaround match on map not shown

### ISSUE THREAD

**Issue by heikofriedrich** [researchstudio-sat/webofneeds#1200]
For this need here: https://satvm05.researchstudio.at/owner/#!/feed?privateId=ai68m5mk-h1v1vz0f

 the matched need "lost my wallte" is shown on the map in matches view. However you see it when you enter the map view by clicking on the matched need in the feed (and the popup opens)

**Comment by quasarchimaere** [comment]
map view for matches has been removed from the app -> no longer relevant
