### ISSUE TITLE
docker compose sometimes container start in wrong order

### ISSUE THREAD

**Issue by heikofriedrich** [researchstudio-sat/webofneeds#1209]
worst case is if for instance certificate creation is not ready before nginx, owner or wonnode start. but can also be problem if rdf store is not there when matching service starts. a lot of dependencies are affected by this.

there is now a solution in docker-compose 1.12.0+ called HEALTHCHECKS that can be used to avoid these problems: 
* https://stackoverflow.com/questions/31746182/docker-compose-wait-for-container-x-before-starting-y/41854997#41854997
* https://docs.docker.com/compose/compose-file/#healthcheck
* https://docs.docker.com/engine/reference/builder/#healthcheck

**Comment by heikofriedrich** [comment]
However, i think we should not implement this yet since the feature (codition in depends_on) has been abandoned again in v3 of docker-compose: https://docs.docker.com/compose/compose-file/#depends_on

**Comment by heikofriedrich** [comment]
ways to handle the issues currently: https://docs.docker.com/compose/startup-order/

**Comment by fkleedorfer** [comment]
Fixed.
