### ISSUE TITLE
Landing Page » Position of colored hotspots adjustment

### ISSUE THREAD

**Issue by thistis** [researchstudio-sat/webofneeds#121]
As the image from the streetscene was depicted from the paper prototype, the colored paper squares were used to indicate a colored border without overlapping the drawing below.
In the digital versions, the boarders with colors should surround the persons in the image for setting the focus on the action of a person/persons in the image and clicking on them should show the comic strip as a way to zoom in and give a further explanation for their current situation.
Storyboard v45, Section Landing Page - Upper Part Landing Page, page 11.

Better:
![img_8283_better](https://cloud.githubusercontent.com/assets/7766513/4630551/33df7b0c-53ae-11e4-88f9-101189ab559b.JPG)

Best: The borders could surround the figures in a more natural way (adjusted to the then-final image) instead of a rectangle and be soft, more like a glow just highlighting that there is something that can be clicked, maybe Kevin or someone else has a better idea?

**Comment by quasarchimaere** [comment]
no longer relevant because of the new gui implementation
