### ISSUE TITLE
long http content data loading time

### ISSUE THREAD

**Issue by heikofriedrich** [researchstudio-sat/webofneeds#1211]
In my account on master have 5 needs that have around 50 matches (in total), so a lot of content rdf data is loaded from the server each in a indivual request. At some request after loading already some reseources the load time takes extremely long (~ 2 min). In the screenshot it says its "content downlad" time, but the content is very small and cannot take so long. My suspection is that the problem is something like a connection pool which runs out and we wait for a timeout here.

![grafik](https://user-images.githubusercontent.com/7766279/30493906-51a43632-9a46-11e7-8c13-e811c6c739d2.png)

**Comment by fkleedorfer** [comment]
We should at least not crawl connection data for closed needs or closed connections

**Comment by fkleedorfer** [comment]
This is much better now, but still an issue. We'll open a new one when appropriate
