### ISSUE TITLE
Password forgotten » Error message for invalid email address appears instantly

### ISSUE THREAD

**Issue by thistis** [researchstudio-sat/webofneeds#122]
The error message should appear after the users started typing an email address in the text field, not just after the page has loaded.
![pwd](https://cloud.githubusercontent.com/assets/7766513/4628434/32007d3e-5397-11e4-894d-75672cb49d78.PNG)

**Comment by sbyim** [comment]
closed.
64aab23c66b6161b4369c8799b0b1f7dc039229f
