### ISSUE TITLE
in responsive mode tabs start to scroll

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1223]
![in responsive mode tabs start to scroll](https://user-images.githubusercontent.com/1730492/30965917-5ca8dfe0-a457-11e7-9a50-199806b918a2.PNG)

This looks suboptimal. We could try an alternative layout/interaction design, try reducing the font-size (atm it's larger than the title in responsive mode) or replace the text with icons (however the [usability of the latter approach would be suboptimal](https://ux.stackexchange.com/questions/1795/when-to-use-icons-vs-icons-with-text-vs-just-text-links)). Maye we could also lay out the dom in a way, that the tab-bar can use the whole screen-width in responsive mode.

**Comment by quasarchimaere** [comment]
the scrolling tabs are not really an issue on mobile devices as it is somewhat common to have horizontal scrolling, the scrollbar is also not shown then, the only problem that i think could be an issue is that the currently selected tab is not always directly visible (on page reload or on direct to matches/request links)

**Comment by quasarchimaere** [comment]
tabs have been removed in favour of a single view
