### ISSUE TITLE
matches -- map-view-icon stands out / doesn't fit in

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1225]
![rectangular icons, one is round](https://user-images.githubusercontent.com/1730492/30966506-6e8b7bf8-a459-11e7-860d-3e5fbc642dfc.PNG)
^ spot the odd one

We could try something along the line of these: 

![various icon variations](https://user-images.githubusercontent.com/1730492/30967396-75aade3a-a45c-11e7-8570-a3cb8fb0cf22.png)

vector-format: [matches-map.pdf](https://github.com/researchstudio-sat/webofneeds/files/1340880/matches-map.pdf)

**Comment by quasarchimaere** [comment]
you can change it, i think option 4 (the one on the farthest right) is the best one

**Comment by m0ru** [comment]
mhm, that or number two. set in context i'm leaning more to two (it's similarly quadratic as the others). ^^

![matches-map-in-context](https://user-images.githubusercontent.com/1730492/31511472-1f57856a-af88-11e7-9d28-d37583b4cfd1.png)

semi-vector: [matches-map-in-context.pdf](https://github.com/researchstudio-sat/webofneeds/files/1380206/matches-map-in-context.pdf)
