### ISSUE TITLE
Remove color variations from sprite-map, use css instead

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1226]
Currently we're including most icons three times in the sprite-map: once in red, once in grey, once in black. It should be possible to use css to change the color in the browser.

**Comment by m0ru** [comment]
This would probably decrease the sprite-map's size by about 50% (not all icons are duplicated). However, as the sprite-map only makes up a small amount of the overall app-size, this would only save us about 0.1s. Thus it isn't the highest priority imho.

**Comment by quasarchimaere** [comment]
is already implemented
