### ISSUE TITLE
Solving error message in chat after closing conversation

### ISSUE THREAD

**Issue by maxstolze** [researchstudio-sat/webofneeds#1231]
When user_1 closes the message connection with user_2, the following error appears as message for user_2:

WonMessageProcessingException: java.security.SignatureException: Could not verify message https://node.matchat.org/won/resource/event/nun0xzk2wglbwgmbuoni: No public key found for https://node.matchat.org/won/resource/event/5386950924531300000#data-sig

**Comment by maxstolze** [comment]
![close_connection_bug](https://user-images.githubusercontent.com/32457902/31127053-010f7ce8-a84e-11e7-80b1-279aa5f11795.png)

**Comment by maxstolze** [comment]
No problem with the closing operation with the following steps:

1.  Close the chat
2. Wait +/- 5 seconds
3. Close connection

-> Own Connection is closed, message gone and chat of the other user also dissapears, connection is closed, message gone.
But: No information for the "other" user, why his conversation is gone.

Log of the "other user" when his chat dissapears

![wait 5 secs](https://user-images.githubusercontent.com/32457902/31337024-caec7ac0-acf9-11e7-8de6-03ca4f5f8337.png)

**Comment by maxstolze** [comment]
Closing connection problem occurs again:
![new_error_1](https://user-images.githubusercontent.com/32457902/31928903-26e6e404-b89a-11e7-8ad2-ad0a9a01615a.png)

**Comment by maxstolze** [comment]
It seems to be a state problem: The two owners aren't updated by the node and try to close the other/remote connection in their "local" states. This connection isn't event set

![state1_1](https://user-images.githubusercontent.com/32457902/31947258-2b345390-b8d4-11e7-85e4-566698c81f32.png)
![state1_2](https://user-images.githubusercontent.com/32457902/31947261-2cb37fac-b8d4-11e7-8fff-86511d6b6f33.png)

**Comment by quasarchimaere** [comment]
as far as i am concerned the "MESSAGE WASN'T PROCESSED...." warning occurs if we receive a message that we do not specifically handle in the ownerwebapp yet, so i assume that implementing this message type and dispatching the event to the state accordingly will resolve this issue
