### ISSUE TITLE
Resize icon-svgs to have a sane default size

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1232]
For the sake of graceful degradation: Even if stuff breaks (e.g. a component's code has an exception and doesn't apply a class), icon-svgs shouldn't take up the entire screen but rather have a sane size baked into the svg itself (e.g. 10-16px)

**Comment by fkleedorfer** [comment]
We'll make this change when we need it. For now, the issue does not help us.
