### ISSUE TITLE
Replace "Request Contact"-button when connected with need from visitor link

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1234]
Currently the info-page of non-owned needs always shows "Request Contact", even when there's already connection(s) with that need. In those cases the button should be replaced/supplemented with links to those needs. Doing this, we could remove the redirect (connections-actions:196) as the app-state would then be clear without it. We might still want to keep it, though.

A variant would be, to allow only having one connection with a counterpart all-together. I'm not sure whether or not that is a good idea from a usability perspective, though (avoids paralell conversations with the same counterpart, risks forgetting a thing matched ages ago, even though it would match the need of today, etc.)

**Comment by fkleedorfer** [comment]
Fixed
