### ISSUE TITLE
Static dev server

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1254]
We could spawn a static server (e.g. `nws -b owner/ -p 8432`) in the webapp folder during development. 

However, the app then can't open the websocket or request rdf-data (as it doesn't use the owner-server's proper url). One way around this, would be to make the target-url for these requests absolute with a variable base and conf that, e.g. via conf.local. 

This would save us ~20s per code-change spent waiting for the tomcat deploy, which would be really nice, as I noticed that (others and) I tend to lose one's train of thoughts while waiting 1-3mins for the app to build and deploy. Afair, this starts happening when there's 20s-2min (or longer) interruptions depending on the context. I think spending a bit of time to enhance our build-/redeploy-time during development now might save us a lot of time/project volume down the line lost due to the constant waiting and need to reorient oneself.

**Comment by quasarchimaere** [comment]
moved to internal kanban board
