### ISSUE TITLE
During crawling need creation does not work

### ISSUE THREAD

**Issue by heikofriedrich** [researchstudio-sat/webofneeds#1260]
It seems while the matcher service is crawling the won node that the creation of needs (and matches) in parallel to the crawling process is not working. This may be because won node is handling too requests

**Comment by heikofriedrich** [comment]
if there are hints sent while crawling then this would overwhelm the wonnode even more, make sure that this is not the case

**Comment by fkleedorfer** [comment]
Fixed AFAIK
