### ISSUE TITLE
Image-Picker Detail/Viewer

### ISSUE THREAD

**Issue by cnvo** [researchstudio-sat/webofneeds#1262]

**Comment by fkleedorfer** [comment]
Yep, definitely on the list! The functionality is there, but when we reworked the web GUI, we did not re-enable it there. Do you have ideas/suggestions for the implementation, or would you even be interested in participating in the implementation yourself, @cnvo ?

**Comment by cnvo** [comment]
I'm the idea/suggestion person - implementation for me unfortunately for this goes so far as mockups.

**Comment by fkleedorfer** [comment]
Sure, we are thankful for any input! If you could keep observing this issue and comment on results we produce, that would be great!

**Comment by cnvo** [comment]
No problem, I'll do you one better by just observing the entire repo.

**Comment by fkleedorfer** [comment]
We are de-prioritizing this issue because our current projects do not require images, so we're lacking the resources. However, it might help to understand what use case you had in mind, @cnvo - were you thinking of something specific?

**Comment by quasarchimaere** [comment]
changing the title to be in accordance to our usecase/detail structure
