### ISSUE TITLE
Tutorial?

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1288]
Guides through interface? Ends with how to close tutorial need.

First question about whether to disable tutorial (and how to reenable it).

Start with overlay? Start with preexisting need? Start with suggestion for need "looking for tutorial"

Written in EML?

**Comment by quasarchimaere** [comment]
i removed the "bot" part of the title, since this could possibly be confusing since we use the word "bot" for a whole different purpose in the context of the webofneeds project

**Comment by fkleedorfer** [comment]
We'll know it when we need it, and then, this issue won't help.
