### ISSUE TITLE
window.back() gets messed up due to routechanges (aka Get stuck on connected post detail page)

### ISSUE THREAD

**Issue by maxstolze** [researchstudio-sat/webofneeds#1312]
After entering the post detail page of the connected need over the chat and open the request form after clicking the "Request Contact" button there is a problem to leave the page again. If you decline the "request" pop up and try to leave via the "back arrow" the form pops up again. No chance to leave the page without sending the request.

![request_2](https://user-images.githubusercontent.com/32457902/32775003-7594ff10-c92e-11e7-93dd-5c23e62bc941.png)
![request_1](https://user-images.githubusercontent.com/32457902/32775005-765fbe4e-c92e-11e7-87b8-a6997b18ebc8.png)

And: Why is there a "Request Contact" button for a post we are already connected to?

**Comment by m0ru** [comment]
the popup is a route-change (to allow the normal backbutton e.g. on a phone to reverse opening it and to be able to reload with it open). atm the back-arrow next to the title-image only triggers a `window.back()`. i guess we should have made it a bit smarter anyway -- i.e. a new sub-reducer should remember the last "real" page(s)/history of these so the back-button can redirect to them. all the info is contained in the state-go actions that are being dispatched. ideally it should still integrate with the browser history. we could try calling `window.back()` until this last "real" page is reached or the history-stack in our app exhausted (in which case it should redirect to the default route)

**Comment by fkleedorfer** [comment]
@m0ru @maxstolze pls close this issue after checking how much of it still applies

**Comment by maxstolze** [comment]
Issue is not relevant anymore and was solved with the new GUI
