### ISSUE TITLE
Sensorica Discussion

### ISSUE THREAD

**Issue by bshambaugh** [researchstudio-sat/webofneeds#1326]
Hello all, 

I spoke with the Sensorica crowd yesterday, and they are full of excitement and energy about the Web of Needs.  

So much so that Bob Haugen added the conversation as a Github Issue:
https://github.com/valueflows/intent/issues/11#issuecomment-350081246
It is also here: https://groups.google.com/forum/?hl=en-gb#!topic/sensorica/ARX7gXex9x8

I invite any who want to to engage them in breaking the ice. I got an away message when trying to engage  Christian Huemer, so maybe bringing him on-board is a January thing. 

-Brent

**Comment by fkleedorfer** [comment]
Moved to other channels.
