### ISSUE TITLE
Just have one message-chain

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1329]
Instead of creating events in every connection endpoint that reference the remotes, we could just have one chain (with one message and one success event per endpoint) and just duplicating this between the nodes. This should simplify the protocol and make messaging easier/more reliable to parse (and avoids any work-arounds that require access to the other connection-endpoint or any other workarounds to enable the required daisy-chaining for checking agreements).

This would probably be a larger rework and should be put off until we have the capacities.

**Comment by fkleedorfer** [comment]
This would require not using linked data URIs for messages that uniquely identify one resource on the Web. Definitely worth thinking about though.

**Comment by quasarchimaere** [comment]
moved to our internal kanban board
