### ISSUE TITLE
What's around with text search

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1332]
"What's around" should also be usable via text search / without sharing the location. This could either be a fallback for when the user doesn't share their location or an alternative with a GUI like the following (if a location has been detected, otherwise the editable text is a textfield. or it is anyway.)

![Thurngasse 8, 1090 Wien [Button: Edit] // [Button: What's around?]](https://user-images.githubusercontent.com/1730492/33993415-bc1784d4-e0d6-11e7-93b5-d8651255416b.PNG)

**Comment by maxstolze** [comment]
No "what's around" anymore.
