### ISSUE TITLE
Configuring Web-App Build

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1334]
It would be nice, to have some way to inject configs into the build process (e.g. custom scss and json-files). One way of doing this would be to give docker a path to a config-folder, that it just mounts into the owner-application folder. This doesn't change our dev-setup though, i.e. we'd need docker to test these configs. 

Imo these build-configs should live in conf.local along with the run-configs.

**Comment by fkleedorfer** [comment]
Fixed through skinning feature
