### ISSUE TITLE
requestIdleCallback for non-essential code-paths

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1335]
Anything that's not directly contributing to app-responsiveness should be queued up via `requestIdleCallback` to avoid blocking the main thread. This goes, in particular, for analytics.

Even if we're not going to refactor all old code right away, we should get in the habit of using this when writing action-creators and when the criteria outlined in [^1] are fulfilled.

This should make our own perform a bit better. :)

* [^1]:  concept overview and code example on mdn: <https://developer.mozilla.org/en-US/docs/Web/API/Background_Tasks_API> 
* [^2]:  docs on mdn: <https://developer.mozilla.org/en-US/docs/Web/API/Window/requestIdleCallback>
* [^3]: old but exhaustive explanation; by now supported by chrome, ff and opera: <https://developers.google.com/web/updates/2015/08/using-requestidlecallback>

**Comment by m0ru** [comment]
Depends on whether or not we want that performance gain ^^

I'd put it in the "later" column tho :)

**Comment by peacememories** [comment]
I think for our usecase (the rdfstore) there are more feasible options, either replacing it with a different "caching" mechanism or moving it into a web worker where its executions don't need to be chunked (a `requestIdleCallback` with a long-running function still blocks the main thread).

We could create a new issue "Remove load from UI thread" and list the options we have in the description.

**Comment by quasarchimaere** [comment]
@peacememories, i am also in favor of creating a new issue (put it in later) reference this issue as a comment here, and close this one after

**Comment by peacememories** [comment]
Closing in favor of #2203 as discussed above
