### ISSUE TITLE
Limited, harmonizing color palette for uri based color generation

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1337]
Unless we decide to remove them (see user feedback during the latest tests), the generated colors should be picked from a limited palette that's designed to work together. Atm it looks like this:

![mismatching colors on title pictures in feed](https://user-images.githubusercontent.com/1730492/34003288-38f74d5e-e0f5-11e7-8993-91e588023629.PNG)

None of the colors harmonizes with with the `$wonRed`.

functions where the color is generated are in `utils.js` named:
- `generateHexColor`
- `generateRgbColorArray`

**Comment by fkleedorfer** [comment]
nice to have, some day

**Comment by quasarchimaere** [comment]
moved to internal kanban board
