### ISSUE TITLE
Minimalist Matchat = Create + Feed + Conversation

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1341]
We could theoretically reduce our view-count by removing the other overviews and moving the widgets from the post-info-view and matches-popup into the conversation column. This would reduce the number of views and thus maintenance effort and would potentially make the app clearer for users. For this, we'd need to fix/polish sorting in the feed and maybe add a text-search (to allow people to look for older posts without scrolling endlessly)

**Comment by quasarchimaere** [comment]
no longer relevant / implemented
