### ISSUE TITLE
Improve geocoding

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1345]
According to https://operations.osmfoundation.org/policies/nominatim/, we have to cache geocoding results in the client, multiple requests for the same coordinates are considered faulty and blocked. 

Blocked geocoding queries are responsible for unresponsiveness in the owner app. 

Two consequences for us: 
1. As we cannot assum the service to be available at all times, the app must be more forgiving in such cases. 
2. We really should cache query results in the client.

**Comment by maxstolze** [comment]
So far the geocoding works fine with the minimal solution (use browser coordinates in case of a bad response).
