### ISSUE TITLE
GoalShape Issue geoCoordinates

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#1353]
as we have discussed before christmas, it would be necessary for the goalshapes to be in a form that the data is in the results. in the current example the result only contains s:geoCoordinates but not which latitude or longitude the geocoordinate of lets say the departure adress is (or that s:geoCoordinates even needs to have two subtypes latitude and longitude)

**Comment by heikofriedrich** [comment]
should be done with latest pr into your branch
