### ISSUE TITLE
Sign Up » View in the background behind sign up window changes while creating new account

### ISSUE THREAD

**Issue by thistis** [researchstudio-sat/webofneeds#139]
Clicking on the Sign Up link in the top navigation changes the view in the background to the Homepage
![signup](https://cloud.githubusercontent.com/assets/7766513/4679010/f059ff64-55fc-11e4-8e0b-6dd763dc4bba.PNG)

If a type of post was clicked in the Home Page once when visiting the Owner Application and the View is changed to a different View in the meantime, clicking on Sign Up will change the view in the background to the Homepage and overlay the Sign up window with the once clicked button.
![signup-button](https://cloud.githubusercontent.com/assets/7766513/4679056/6a51ec0a-55fd-11e4-8306-afb883befe92.PNG)

**Comment by quasarchimaere** [comment]
no longer relevant since the redesign of the gui
