### ISSUE TITLE
Reactivation link in email

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1458]
> This posting is deactivated because it has no active connections, nor has there been any activity from your side in the last 10 days. Automatic deactivation is done to clean up abandoned postings. You can reactivate your posting at any time.

^ make the "reactivate your posting at any time" a clickable link that reactivates the posting.

**Comment by fkleedorfer** [comment]
good idea

**Comment by quasarchimaere** [comment]
moved to internal kanban board
