### ISSUE TITLE
Link to Raw Message shows unrendered HTML on Chrome -- Missing Content-Type

### ISSUE THREAD

**Issue by pheara** [researchstudio-sat/webofneeds#1473]
## Problem

![unrendered html](https://user-images.githubusercontent.com/1730492/37219360-6b2773ba-23c3-11e8-9762-26ef7f51b501.png)

HTTP-Request for the message:

![header without content-type](https://user-images.githubusercontent.com/1730492/37219367-735decd0-23c3-11e8-992c-8946cf9a78ae.png)

## Reference

A properly working HTTP-Request for a need directly on the node (that shows the page as it should look like): 

![header with content-type for need](https://user-images.githubusercontent.com/1730492/37219376-78cc4004-23c3-11e8-8a59-31d991c25f33.png)

## Possible Solution

Pass-through content-type through the owner (and potentially some of the other omitted fields as well).

**Comment by quasarchimaere** [comment]
fixed
