### ISSUE TITLE
Matcher crashes on Integration Server

### ISSUE THREAD

**Issue by sigpie** [researchstudio-sat/webofneeds#1495]
The matching service on the integration server crashes with the log message: 

`[main] WARN  o.s.c.a.AnnotationConfigApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'linkedDataSource': Unsatisfied dependency expressed through field 'parallelRequestsThreadpool'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'java.util.concurrent.ThreadPoolExecutor' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}`

**Comment by heikofriedrich** [comment]
seems to be fixed, matches are coming again on int test
