### ISSUE TITLE
refactor owner overview

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1521]
* remove posts view
* ~~use icons (conversations, requests, matches) in chats view~~<-- is implemented within PR #1535 
* ~~show postings without connections in chats view, too~~ (with an indicator panel saying 'This posting has no connections. Consider posting this link (link) in social media, or wait for matchers to connect you with others.  <-- is partially implemented within PR #1536 PR #1538
* ~~show closed needs in chats view (like currently in postings view~~ <-- is implemented within PR #1536 
* ~~make popdown on needs in chat view that shows all details (own and remote). Popdown should activate on title click or image/icon click. Also add an option to reopen closed needs.~~ implemented within PR #1538
* ~~when clicking on a connection type indicator on the own need (conversation/request/match), select a connection of that kind with unread messages, or the connection with the most recent activity~~ <-- is implemented within PR #1535
* ~~on each posting in the chats view, show the unread message counter~~ <-- is implemented within PR #1531

**Comment by quasarchimaere** [comment]
if we removethe post view we lose the ability to reopen closed posts.

i am also not sure if removing it at all is a good idea.since the feed as a replacement is very unstructured and verbose (just my two cents)

**Comment by quasarchimaere** [comment]
i am currently working on the last open item and the second item (indicator link plus indicators)
