### ISSUE TITLE
Refactor state variables + update README.md

### ISSUE THREAD

**Issue by maxstolze** [researchstudio-sat/webofneeds#1529]
![state_issue](https://user-images.githubusercontent.com/32457902/38539458-97940a4c-3c98-11e8-977a-e16b0a3a37a6.png)

Summarize boolean flags into a message type variable:
messageType: chatMessage | proposeMessage | proposeToCancel | acceptMessage | rejectMessage | retractMessage

Update the "State Structure" in the README.md of the won-owner-webapp

**Comment by fkleedorfer** [comment]
That's actually not a correct refactoring suggestion. Closing
