### ISSUE TITLE
browser does not retain accept headers when following a redirect (303 see other) with a different host name

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#153]
observed when requesting a linked data URI using only the hostname, not the fully qualified dns name, and the redirect points to the fully qualified dns name. In that case, chrome (or jquery?) sends standard headers, not the ones sent with the first request.

In our setting, this leads to the accept header being forgotten. Thus, the server uses the default RDF language. We may look into it to see under what other circumstances this happens, and try to find a fix, but we can live with the default format being the format our webapp expects, in which case, the problem does not have any adverse effects.

**Comment by quasarchimaere** [comment]
@fkleedorfer so what is the issue here, and is this still relevant since it has been created 4 years ago

**Comment by quasarchimaere** [comment]
moved to internal kanban board
