### ISSUE TITLE
Getting stuck in 'right hand side' of chats on small devices

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1556]
Steps to reproduce:
1. Use a phone in portrait orientation
2. Do something to get matches (e.g. What's Around)
3. navigate to the chats view 
4. click on one of the matches or click the matches indicator button. Result: you now see the detail view of the matched need
5. click 'bad match - remove'

Result: you only see a grey area, the text 'No Element selected' is not shown either. changing device orientation or clicking 'chats' in the navigation bar at the top gets you back to the chats view.

**Comment by quasarchimaere** [comment]
duplicates #1545
