### ISSUE TITLE
Clicking on an item in a dropdown should close the dropdown

### ISSUE THREAD

**Issue by peacememories** [researchstudio-sat/webofneeds#1564]
When clicking the dropdown menu arrow on a need or connection and then clicking e.g. on the rdf button, the menu stays open.

**Comment by quasarchimaere** [comment]
not necessarily needed -> afaik there are only actions that result in a view change (e.g closeConnection or gotopost) which "close" the contextmenu as is, the  rdf links open the rdf content in a different tab or toggle the rdf in the post-messages, we might want to close the contextmenu there
