### ISSUE TITLE
Owner-webapp skin changes

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1577]
We should make the following changes to the matchat skin:
* add a 'fork me on github' sticker to emphasize that it's open source and distributed
* remove the 'do I need an account`' FAQ question (related to #2528)
* the how it works section has suffered a bit during the refactoring for skinning. (icon color was read, vertical spaces were smaller

**Comment by sigpie** [comment]
Third point overlaps with #1414

**Comment by fkleedorfer** [comment]
true but #1414 is closed now, and this is not done yet

**Comment by quasarchimaere** [comment]
@peacememories what does this have to do with the skin itself?

**Comment by peacememories** [comment]
Discussion on this issue seems to have stalled. Is there anything still to be discussed here?

**Comment by quasarchimaere** [comment]
> @fkleedorfer what does this have to do with the skin itself?

**Comment by peacememories** [comment]
Since discussion does not seem to be picking up, I will close this issue if no actions are taken within a week.

**Comment by peacememories** [comment]
Closing this because the conversation does not seem likely to start up again.
