### ISSUE TITLE
Improve routing/app startup so routes can access loaded state

### ISSUE THREAD

**Issue by peacememories** [researchstudio-sat/webofneeds#1578]
While working on #1571 I ran into the problem that while routing the data i needed to decide whether to redirect was not loaded yet, and I had no method to wait for the `initialPageLoad` to finish.
I propose changing the page load so after it is done either a callback or another route change is triggered.
Optionally, while booting up a loading spinner could be shown (which would either require a root level conditional component or a substantial change to how routing is executed right now).

**Comment by fkleedorfer** [comment]
`I propose changing the page load so after it is done either a callback or another route change is triggered.` sounds like the low-cost approach.

Why should we do that? Is it still an issue?

**Comment by quasarchimaere** [comment]
@fkleedorfer yes its still an issue, repro steps open the share link of a need that belongs to a user you are currently logged in as

**Comment by quasarchimaere** [comment]
nlr -> closing this issue
