### ISSUE TITLE
Old and inactive whatsaround needs stay in overview

### ISSUE THREAD

**Issue by sigpie** [researchstudio-sat/webofneeds#1588]
Every time a new "See What's Around?" need is created, the previous one is set to inactive. If this happens several times, old "See What's Around?" needs accumulate in the overview. 

![closed_whatsaround_needs](https://user-images.githubusercontent.com/32930574/38947178-0bd3e428-433c-11e8-8f66-6d96dc7c5492.png)

It would be better to show no or only the most recent inactive "See What's Around?" need in the overview instead, especially since there is no reason to reopen old "See What's Around?" needs.

**Comment by quasarchimaere** [comment]
imho we can hide all the inactive whats around needs in the connections list
