### ISSUE TITLE
Cannot select visitor link in Firefox

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1591]
Ironically, the link is the only thing on the bloody page that one cannot select in FF 59.0.2 (64-Bit)

![grafik](https://user-images.githubusercontent.com/551624/39000669-de0bcfce-43f4-11e8-8a03-8cf4757098e7.png)

**Comment by quasarchimaere** [comment]
there is also a different issues with these links which could/should be tackled in this issue as well:

-the items takes up alot of space and should be reduced -> maybe extract the usages/codesnippets and put them in a component, then we can implement a button for copying to clipboard or at least automatically selecti the whole url on click, and maybe make the component collapsible (default value collapsed, and include share icon?)

**Comment by quasarchimaere** [comment]
is related to #1560
