### ISSUE TITLE
Agreements GUI: glitch when accepting too quickly

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1592]
If one hits the accept button too quickly, it reappears after the message has been processed, allowing me to accept the proposal again.

example: after accepting quickly: 

![grafik](https://user-images.githubusercontent.com/551624/39001370-75a593b4-43f6-11e8-803e-594da0d4703c.png)

and after clicking accept again: 

![grafik](https://user-images.githubusercontent.com/551624/39001404-8999e244-43f6-11e8-9e36-29bb8645eac8.png)

**Comment by quasarchimaere** [comment]
to remove the glitch we could facilitate the "isLoading" param in the specific connectionstate,

see PR #1599

**Comment by maxstolze** [comment]
Fixed in PR #1530
