### ISSUE TITLE
Show RDF button should point to need

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1605]
Currently, when selecting 'show RDF' in the remote need's popdown menu, the connection resource is opened in a new window. This is not what one would expect. It should link to the need's linked data resource.

**Comment by quasarchimaere** [comment]
to be fair the header popdown is not necessarily the "need"header but the header of the underlying connection, so if one wants to get to the need rdf you have to go through the post-detail view... unless a match is selected then you should automatically get to the need rdf as well

but i see how the header is misleading here,maybe we should think about naming the rdf button in a clearer way or add a second button in the context

also there is no way to see the connection rdf now when you have selected a connected connection, the show rdf button is used for the toggle in that case

**Comment by fkleedorfer** [comment]
let's have 2 RDF buttons, one for the need, one for the connection, renderd as 
'[RDF logo] Post' 
and
'[RDF logo] Connection'

**Comment by quasarchimaere** [comment]
Added a label to every RDF link to show which rdf document is going to be opened in a new tab
the match has two rdf links now one for connection and one regarding the remote post
