### ISSUE TITLE
Remove checked-in dependencies, get via npm

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1618]

**Comment by fkleedorfer** [comment]
Why? How long will it take?

**Comment by quasarchimaere** [comment]
@fkleedorfer we cant remove all of them anyway, so why bother figuring it out in bulk, lets just see if it happens naturally within other issues or stories, i would close this item because we cant get rdfstore.js from npm anyway because of our own changes and fixes within the lib

**Comment by m0ru** [comment]
True, I guess :)
Only other script in `scripts/` is `rdf-ext` that we don't actually use and that should be removed.
