### ISSUE TITLE
Get N3 via npm and bump version to 1.0

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1620]
Just got this via the rdfjs-mailinglist:

> I've released N3.js v1.0.0-alpha with full RDF.js compatibility

:3

**Comment by quasarchimaere** [comment]
nice that it seems like a major release bump is happening and that n3.js is still in active development, however i am not certain if we should use alpha versions of libraries already...

imho i would even go as far as to say we should not touch beta versions either, but seeing how this is all javascript dependencies we can probably toss everything we already include as well ;-)

**Comment by quasarchimaere** [comment]
isn't that already done?
