### ISSUE TITLE
Mobile View Input Fields are hidden

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#1625]
Problem: 
- Our input fields are usually on the bottom of the screen (in chat and requests)
- If the app is used on a mobile device the software keyboard opens after tapping an input field and therefore hiding the input field underneath the keyboard until the user types the first character (this is true for android i am not sure if this is the case in ios), idk i think the viewport of the screen is only reduced once the a character is typed, maybe there is a way to add an attribute to the input fields that indicates that the browser should resize the viewport on selection and not after the first character has been typed...

**Comment by fkleedorfer** [comment]
@quasarchimaere @peacememories @m0ru can you think of a way to fix this?

**Comment by maxstolze** [comment]
So far it works in the "chatview", to reduce the grid-template-rows on mobile devices from 10rem to 5rem.

**Comment by quasarchimaere** [comment]
thats great! what about the input in the login dropdown/signup/need creation? did the removal of medium.js and the reduction help there as well?

**Comment by maxstolze** [comment]
Work in progress! I am pretty shure, yes!
