### ISSUE TITLE
rotate matchat logo svg 180deg

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#1638]
the icon still shows a W instead of a M for our matchat instance

**Comment by fkleedorfer** [comment]
@quasarchimaere this is a 10 minute issue, right?

**Comment by fkleedorfer** [comment]
If so, do it asap please ;-)

**Comment by quasarchimaere** [comment]
@fkleedorfer yes maybe 11min if one changed the title in the config too, i just created this ticket to see if we should do it at some point or not
