### ISSUE TITLE
Automatic What's New Posting

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1653]
Whenever the owner webapp is opened, and there is no active session (and no remember-me cookie), an anonymous user should be created.
Next, a "What's New" - posting should be created, which is a What's Around without a location.
if any "What's New" or "What's Around" already exist in that situation, they should be closed

**Comment by quasarchimaere** [comment]
also see feature #1632

**Comment by m0ru** [comment]
Asking for a users location straight away comes off somewhat creepy. We should find a way to pass some text along (e.g. by showing a custom popup/-over) or keep this user-initiated but make it a single click and visually the first thing they'll look a (+explanation of the value it brings).

**Comment by maxstolze** [comment]
Duplicate of #1632
