### ISSUE TITLE
(no matching context specified) is displayed too often

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#1668]
the default case of no matching context at all is taking up alot of space and clutters the interface in list views
![screenshot_20180426-205558](https://user-images.githubusercontent.com/8503486/39326244-a0726916-4994-11e8-99e9-0ea912b09e84.png)

**Comment by fkleedorfer** [comment]
just remove the `(no matching context specified)` in that case

**Comment by maxstolze** [comment]
I will remove the String, because in the current GUI it's not possible to define a matching context anymore.
