### ISSUE TITLE
Long titles mess up layout

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1704]
In firefox, long titles aren't handled properly:
wide screen seems kind of ok, but still weird because the title is not abbreviated, it just overflows into an invisible ara:
![grafik](https://user-images.githubusercontent.com/551624/39691980-a15af8ae-51df-11e8-9fcd-f60880189039.png)
less space: not so good
![grafik](https://user-images.githubusercontent.com/551624/39692030-da982dee-51df-11e8-9c48-4690792f340c.png)

**Comment by quasarchimaere** [comment]
not sure which instance this is but it seems like there are attributes within master _connection-header.css and _post-header.css that are not present (at least it seems that way within the minified code)
