### ISSUE TITLE
Non-URL-style URIs when authoring need with arbitrary RDF

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1716]
Make `ttl2jsonld` fail if there's unresolved/-solvable uri-placeholders. Atm e.g. the following fails silently:

```ttl
@prefix c: <http://example.org/cartoons#>.
c:Tom a c:Cat.
<this:messageuri> a c:Mouse;
        c:smarterThan c:Tom.
c:Jerry a c:Mouse;
        c:smarterThan c:Tom.
```

note the `<this:messageuri>` (that doesn't get replaced here)

This ends up in something like the following showing up in the need-rdf on the node:

![image](https://user-images.githubusercontent.com/1730492/39762610-634f45a4-52db-11e8-8223-9ce0dc814ba3.png)

**Comment by m0ru** [comment]
This is probably also a problem on the node, as this RDF shouldn't be published by trigger a failure-response imo.

**Comment by quasarchimaere** [comment]
ttl2jsonld does not exist anymore --> no longer relevant
