### ISSUE TITLE
Drop titles of reply needs in favor of first text (in request/connection message)

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1719]
Instead of:

![image](https://user-images.githubusercontent.com/1730492/39775567-99a2d4d6-52fe-11e8-8122-d736a1feb40a.png)

Do:

![image](https://user-images.githubusercontent.com/1730492/39775649-d6cb6da0-52fe-11e8-9e58-9262f4d3f98b.png)

I think this would help people recognizing the conversation. We might ignore new-lines for the text-snippet and just crop after a set number of characters (or replace newlines with "\<first line\> // \<second line\>" or any other similar typographic measure). We could also use the latest chat-message, but that one will probably change quite often making memorization harder. On the other hand though, it will probably be related to the most recent thing ppl might remember about that conversation.

**Comment by quasarchimaere** [comment]
i would even go as far as to say we should show the last message (includes the connect message as well) instead of the counterpart need title

**Comment by m0ru** [comment]
result of offline discussion: the last _renderable_ message. which currently means the last message with `won:hasTextMessage`. In the future we might need components/functions that render a line of text from any of the arbitrary message types we might have (e.g. location => address-string)

**Comment by quasarchimaere** [comment]
we also can't forget to call "connections__showLatestMessages" otherwise the connection might not have any loaded messages yet (especially when reloading the page)

also try to prefix the message with You: and Them: depending on the originator of the message

**Comment by m0ru** [comment]
hm, that's a problem. `showLatestMessages` has a rather large performance cost. so basically the server would need to pass this along with the connection. or there needs to of batch-loading all latest events for all connections in one roundtrip.

**Comment by fkleedorfer** [comment]
I like the direction this is taking but I think it's a marginal improvement - something we should leave for later. It opens a few new problems we don't know how to solve yet, and for the time being, we need to focus on things happening earlier in the user flow, such as search vs is/seeks

**Comment by quasarchimaere** [comment]
@fkleedorfer i do not agree that this will only be a marginal improvement, as this would fix the issue #1790 as well, since we do not parse any connection message after a login and that results into the user not knowing that anything has happened in the conversation (especially a problem if the user has plenty of needs)
