### ISSUE TITLE
Displaying Needs with Arbitrary RDF

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1721]
The long-term goal here is to identify and load widgets capable of displaying any RDF to users (see the [RDFruit-community](https://gitter.im/rdfruit/Lobby) for more details on that). In the short-term we need fallback mechanisms. Particular problems/design challenges are:

##  post as list-item in overview

  * title: there might be no title or no text at all
  * placeholder-image: if there's no attached image or title/text our current approach won't work. see  #1720.

## post details

same as above but also: we want to _show something for all triples_. for this we could use `rdfs:label`-schema-entries to render text that's friendlier to non-developers. if we can't display something, we should note it's absence / print an error message and link to the TTL-version.

**Comment by m0ru** [comment]
order of planned implementation:

1. error message for when there's non-displayable rdf
2. `rdfs:label` for key-value style display
3. posts without title =>
  1. update create-post
  2. fallback for title-text
  3. fallback for placeholder-images (see #1720)
4. optional: show-rdf allows displaying rdf in-client instead of linking to server (it's faster this way)

**Comment by fkleedorfer** [comment]
Let's leave 7 for later

**Comment by quasarchimaere** [comment]
i just moved this to in progress, because i think its currently in progress, if this is not the case please forgive me @m0ru

**Comment by m0ru** [comment]
Tinkering with the title placeholder (see screenshots below). Ideally, we'd have smarter ways of deriving "title"-strings for different needs (e.g. "cab ride from $x to $y" for the transport use-case). a somewhat more generic approach would be to look for `xsd:string`s and use the `rdfs:label` linked to their predicates.

end of uri (con: might not work for different nodes in the future)

![end of uri](https://user-images.githubusercontent.com/1730492/41613721-adae68be-73f6-11e8-972b-cb3cfb43f1ae.png)

entire uri (con: very long and thus requires word-wrap; only small difference between lines):

![entire uri](https://user-images.githubusercontent.com/1730492/41613781-dd48b0a2-73f6-11e8-8c9d-44cac1ec844a.png)

generic placeholder (pro: less intimidating; con: every need looks the same but for the identicon):

!["<no title>" as placeholder](https://user-images.githubusercontent.com/1730492/41613871-2a1a5520-73f7-11e8-96c8-9b78f4866a86.png)

**Comment by fkleedorfer** [comment]
How about a list of adjectives and a list of nouns and a function that selects from both pseudorandomly based on the hash of the uri? E.g. needuri -> "punctual hedgehog"

**Comment by m0ru** [comment]
@peacememories argued for the last, but without bracket and a slightly greyed out text.

**Comment by m0ru** [comment]
@fkleedorfer we might need to watch for insulting or tactless combinations

**Comment by quasarchimaere** [comment]
i agree with @peacememories, imho anything more sophisticated than this simple approach is too much hassle for no effect

**Comment by m0ru** [comment]
Fazit: last solution ("no title" placeholder) and use-case-specific titles (e.g. "cab from $x to $y") where possible and maybe automatic text generation using `rdfs:label`, if we manage to get around to it.

**Comment by m0ru** [comment]
Fazit:

![posts without title have a greyed out "<no title>" in their post-preview](https://user-images.githubusercontent.com/1730492/41672848-4ba9fd8e-74bb-11e8-9d0c-9bebf98d93ce.png)

![ad hoc contact requests to needs without title also have no title](https://user-images.githubusercontent.com/1730492/41673302-d931b9f2-74bc-11e8-876f-4851283ec5f1.png)

**Comment by m0ru** [comment]
Only thing left to do: displaying an "non-displayable content"-warning if there's RDF that has no nice gui-components and can only be viewed as raw rdf. See #2012. I'll close this issue for now then.
