### ISSUE TITLE
Ensure a better mobile experience for tablets and phones

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1722]
Old Title: ~~long titles still break layout~~
Old Description: ~~On my Nexus 6 in landscape mode (ff), the gui is still in 2 column mode, which is ok but a long title can really mess it up completely. The used space gets larger, causing horizontal scrolling, and the application is unusable for the most part. Needs Fixing.~~

We need to ensure a better mobile experience by altering our media queries in a way that the two column ui is only shown when there is sufficient space available, probably we need to ensure "list-only" view for mobile phones regardless of the current screen-orientation.

For tablets we should ensure that the two column ui is displayed at least in landscape mode, and also limit it to "list-only" view in portrait mode on tablets, as we are probably going to have to little space available to show both sides at the same time on a tablet....

**Comment by quasarchimaere** [comment]
mobile landscape view was not part of the "fix" for the long titles -> i will change the issue title and update the description accordingly

**Comment by fkleedorfer** [comment]
Better now.
