### ISSUE TITLE
close post is misleading

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1723]
Sounds like 'close this view'

**Comment by peacememories** [comment]
How about `archive post`?

**Comment by quasarchimaere** [comment]
i agree that in the context of the desktop view the "close connection" or "close post" buttons in the context menu are misleading as there is no other to close the view (in desktop) anyway... i think "archive post" and "remove connection" are better terms for the buttons, i will create a pr with the changes (including changing the label of the closed posts to "archived posts")
