### ISSUE TITLE
Share functionality is confusing and hard to find

### ISSUE THREAD

**Issue by peacememories** [researchstudio-sat/webofneeds#1728]
1. Create a need
2. Go to the share section
3. Try to select the link
---
When trying to select the link every selection gets immediately deleted (and the link gets copied to clipboard, because the click handler does that)
The only visual feedback for what is happening is that the text below the field changes to "Link copied to the clipboard"

I would prefer github-style behaviour where focusing the text element selects the whole link, and there is an extra button to the right for automatically copying to clipboard. After the initial click selecting any part of the link is possible.

![image](https://user-images.githubusercontent.com/1326334/39807346-5d0665fa-537c-11e8-9c8b-20ecefd4b345.png)

**Comment by fkleedorfer** [comment]
agreed

**Comment by fkleedorfer** [comment]
Also, the share functionality is hard to find. A user told me: 'You guys have to hide that share thing better. I almost found it all by myself'

Where should we put it ?

**Comment by peacememories** [comment]
I think Andrés had a mock-up where it was just always visible at the top of the details page, which makes sense. It doesn’t take up much space and this is a similar position to githubs.

**Comment by peacememories** [comment]
I think this is more of a solution for desktop use. Mobile browsers have a concept of sharing a page which, I assume, most people use. This doesn't work with our current url schema though.
