### ISSUE TITLE
post view cluttered when keyboard drawer is shown

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1731]

**Comment by fkleedorfer** [comment]
![img_20180508_231011](https://user-images.githubusercontent.com/551624/39810375-11651b6a-5385-11e8-8ae4-f2c63c9464af.jpg)

**Comment by quasarchimaere** [comment]
- maybe we need to remove the navbar in this view as well (similar to the view when a connection or need detail is shown)
- medium.js will show the placeholder incorrectly we should think about removing it in general, so there are no overlapping elements anymore (i am in favour of splitting title and description to two separate inputs/textareas where the description is only displayed when an additional detail "description" is added

**Comment by peacememories** [comment]
This also happens when adding a location on desktop.

![image](https://user-images.githubusercontent.com/1326334/39815455-4881e520-5398-11e8-9eec-32d972502902.png)

**Comment by quasarchimaere** [comment]
screenshot is not up-to-date anymore

**Comment by fkleedorfer** [comment]
Outdated
