### ISSUE TITLE
Line numbers in TTL error messages can be confusing

### ISSUE THREAD

**Issue by peacememories** [researchstudio-sat/webofneeds#1736]
Right now, when submitting custom TTL and producing an error, the line number of the error is shifted by the autogenerated `@prefix` lines. So an error on line 1 might become an error on line 14 in the output.
![image](https://user-images.githubusercontent.com/1326334/39815325-ebcf993a-5397-11e8-9c67-4b2c0b1f3d34.png)

A quick fix for this would be to print line numbers in the output. This way a user could more easily find their way around the code.

A more advanced solution is to include an editor like [monaco](https://github.com/Microsoft/monaco-editor) in the TTL text field. This editor could either just print line numbers or provide code hinting etc.

**Comment by quasarchimaere** [comment]
no longer relevant --> ttl detail doesnt exist anymore
