### ISSUE TITLE
connections with inactive posts in whatsaround needs

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#1739]
it seems to me that connectionsof whats around needs can contain closed posts (this is probably due to the fact that the whatsaround need is not represented in a connection of the counterpart need and therefore will not get a notification that the need is setto inactive...)

however if its not possible to inform a whatsaround need aboutthe status changes of the connected needs we could at least filter the connections of whatsaround needs if the remoteneed is inactive.

**Comment by fkleedorfer** [comment]
Yes, saw that too
