### ISSUE TITLE
Spring security version error

### ISSUE THREAD

**Issue by yanapanchenko** [researchstudio-sat/webofneeds#174]
In our 1.0 brunch we have the following error in server log when running the won-owner-webapp:

ERROR o.s.s.core.SpringSecurityCoreVersion - **\* Spring Major version '3' expected, but you are running with version: 4.1.1.RELEASE. Please check your classpath for unwanted jar files.

Does not seem to affect functionality.

**Comment by quasarchimaere** [comment]
we are currently on 4.2.3.RELEASE -> close
