### ISSUE TITLE
collapsed needs dont indicate if they have conns (except unread)

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1740]
By showing the 'v', we invite users to click eben if there is nothing there to see: no matches, no chats. It looks the same if there are matches/chats but no new/unseen

**Comment by fkleedorfer** [comment]
![screenshot_20180509-193711](https://user-images.githubusercontent.com/551624/39830928-1ee8a9c6-53c3-11e8-898d-ba1bbb9f5e81.png)

Guess which need has any interesting connections

**Comment by quasarchimaere** [comment]
maybe instead of showing just the number of the new connections within the need (on mobile) we could use two numbers (8/4) exp. all/new or just the sum of connections and a ! as a marker if there are any new connections within that need

**Comment by fkleedorfer** [comment]
A few thoughts on this:
* We could show a number as @quasarchimaere suggests. In that case, we'll have a lot of 0's there. That's visual clutter, is seems to me.
* We could add a collapsed section with needs without connections (i.e. no suggested, half-open or open), just like the section with closed needs, and omit the 0's there. By default, that section is collapsed.

**Comment by fkleedorfer** [comment]
On the numbers: i like that the numbers now indicate unseen events, the proposal here dilutes that a bit. I think it would be quite clear if 8/4 meant: 8 chats, 4 matches, because it visually corresponds to what you see when you open the need. If there are unread events, put a ! After the respective number: 8!/4 meant 8 chats (some unread), 4 matches (0 new)

**Comment by fkleedorfer** [comment]
And if we put the number instead of the 'v', we get rid of a confusing bit
