### ISSUE TITLE
No feedback if no location is found

### ISSUE THREAD

**Issue by sigpie** [researchstudio-sat/webofneeds#1748]
The location picker currently does not display anything if no results are found. 

![loc_noresult](https://user-images.githubusercontent.com/32930574/39928184-f1fd1938-5534-11e8-9185-eb3d5ed2dd89.png)

A message like "no results found" should be displayed. Note that the message should not discourage users from continuing to type, as "Thurnga" yields no results, but "Thurngasse" does.

child of #2820

**Comment by maxstolze** [comment]
So we open the suggestion dropdown by default and show "no results found" till there are some?

**Comment by sigpie** [comment]
That would be a possibility, but people might not continue typing if "no results found" is displayed too early. I think a better solution would be to display results from substrings of the current search string. This would cause more queries though, which conflicts with #1094

**Comment by peacememories** [comment]
Hmm, Google Maps shows an "add location to maps" option when no result is found in typeahead search. Obviously we don't need that, but I think the only feedback we need is "the search happened and there is no autocompletion".

One way to do this is to add a loading spinner inside the search field at the start of the query and remove it when the query is finished. This shows users that something happened in response to their interaction but doesn't tell them "what you did was wrong"

**Comment by peacememories** [comment]
Since this is marked as a design issue, which implies that the decisions discussed here are part of the task, I would suggest moving this to another column.
@fkleedorfer
