### ISSUE TITLE
five-star rating widget not connected to data model

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#175]
because the rating is not yet persisted, the rating widget doesn't work as expected:
* it keeps its state (e.g. a 2-star rating) when switching between different connections (conversations) of a posting.
* it can't reflect the value actually given for a connection after switching away from that conversation

**Comment by quasarchimaere** [comment]
rating was implemented with 2 different choices now (new gui) and is already functional
