### ISSUE TITLE
URI placeholders all over the place

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1751]
In the messages, we use `<this:eventuri>`, in the need RDF, we use `<_:isNeedContent>` and `<_:seeksNeedContent>`. We could be more consistent. 

Suggestion:
* `<_:is>`
* `<_:seeks>`
* `<_:msg>`

**Comment by m0ru** [comment]
For the needs, it's no placeholder as that's the name of the blank content-nodes. For the messages the placeholder get's replaced with an actual URI, as the triples are directly attached to the message. Theoretically we could use a placeholder for the needs as well, that get's replaced with the blank-node name.

**Comment by fkleedorfer** [comment]
that's ok as well.. how about:
``` 
* <this:is>
* <this:seeks>
* <this:msg>
```

**Comment by m0ru** [comment]
that works as well :)

**Comment by quasarchimaere** [comment]
just as a friendly reminder for whenever this is implemented: `this:is` or `_:is` is not a part of our need structure anymore, all that "is" is stored in the content

**Comment by quasarchimaere** [comment]
moved to internal kanban board
