### ISSUE TITLE
Connection list overflows container

### ISSUE THREAD

**Issue by peacememories** [researchstudio-sat/webofneeds#1757]
On small-ish screens the connection of a need overflows its container. This causes the padding to change, and also causes clipping on the "Show Post Details" button when opening and closing the list.
![image](https://user-images.githubusercontent.com/1326334/40068970-39ca0112-586a-11e8-8135-b64573053c67.png)

**Comment by quasarchimaere** [comment]
we need to find a reasonable min-width for the list side
