### ISSUE TITLE
Owner webapp omits messages

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1781]
After a reload, some messages of a conversation are missing in the GUI. 

Happened in a conversation with about 20 messages, roughly the same number from each participant.

The bug here is that the messages are not there, but you'd expect that the GUI would inform you of missing messages by checking the presence of previous ones.

**Comment by quasarchimaere** [comment]
was the connect message there...meaning only messages in the middle of the conversation where missing?

**Comment by fkleedorfer** [comment]
The issue is due to newline-characters in the messages.

**Comment by fkleedorfer** [comment]
This is caused by #1579, which is caused by https://github.com/digitalbazaar/jsonld.js/issues/242

**Comment by fkleedorfer** [comment]
The issue here is that we found out that you can produce newlines with Shift+Enter. We should provide a workaround until the original cause is fixed
