### ISSUE TITLE
Prevent undead browser sessions

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1789]
How to reproduce:
* log in and post something or chat
* leave the browser window open for some time (unclear how long... > 1h?)
* now close a connection, send a message, deactivate a need. Your action will have an effect in the GUI.
* reload the page
-> the effect of your last action is gone

It seems that the session times out but the webapp does not notice. This should not happen.

Related to #898 which contains useful information on how to get started debugging this.

**Comment by quasarchimaere** [comment]
i dont know how the config is on the docker/cluster but as far as i see the web.xml in our owner-webapp defines a session timeout of 24hours (86400 minutes) so i am not sure when or why the issue arises, so @fkleedorfer @m0ru @maxstolze @peacememories @sigpie if you happen to reproduce this issue or see this happen in the process of testing or dogfooding enrich this ticket with the console.log output and possibly the network traffic (which call fails etc.) and even a server log as well

**Comment by fkleedorfer** [comment]
child of #1885

**Comment by fkleedorfer** [comment]
Closed in favour of #1885
