### ISSUE TITLE
silent conversations

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#1790]
i came to realize that the reason why alot of people dont respond on matchat is that they do not see an incoming message after a login.since we only retrieve the messages after clicking on the conversation.

two possible solutions:
1) retrieve all conversation messages before (easy but slow)
2) implement the serverside unread counters

**Comment by m0ru** [comment]
defenitely (2)

incoming requests/messages while the app is loaded should be visible anyway as they universally get pushed through the websocket.

**Comment by m0ru** [comment]
^ or a counter/list of URIs if we can calculate that on the server without an extra performance cost.
