### ISSUE TITLE
Inconsistent Animation Speeds

### ISSUE THREAD

**Issue by sigpie** [researchstudio-sat/webofneeds#1801]
We use several animations to let interface elements slide in and out. However, those elements move at different speeds. Animation speed should at least feel consistent throughout the application.

**Comment by quasarchimaere** [comment]
problem is animating for undefined/variable heights -> maybe there isa way to calculate it based on the amount of elements present within the animated component

**Comment by quasarchimaere** [comment]
animations are almost completely obsolete now since we switched from angular to react -> i am going to close this issue, we would have to figure out a complete rework instead (tbd)
