### ISSUE TITLE
Too many different button styles and functions

### ISSUE THREAD

**Issue by sigpie** [researchstudio-sat/webofneeds#1806]
Right now we have: outlines buttons using the primary colour, full buttons using the primary colour, full buttons using another colour, disabled buttons and icons that act like buttons. 

Maybe it would be better to have one button style for everything that only changes what is displayed (e.g. Show Post Details) and one button style for everything that changes content (e.g. Publish).

**Comment by peacememories** [comment]
I assume we are all on board with having a more unified interface.
What are our options here? I see:

* Create a robust library of basic components.

    These components would have a fixed style and would be the building blocks for the rest of our UI. Defining custom UI somewhere else should be disallowed to prevent the current sprawl of similar-but-different elements.

If there are other solutions you can think of we should discuss them here, if we agree on a solution we should replace (or rename) this issue with the actual solution we want and move it to one of the to-do columns.

@moru You might be interested in this too?

**Comment by sigpie** [comment]
@peacememories does such a library exist for buttons now?
