### ISSUE TITLE
Interface elements in the footer are easy to overlook

### ISSUE THREAD

**Issue by sigpie** [researchstudio-sat/webofneeds#1807]
This is more of an issue on Desktop, especially with large screens and a low amount of detail in the open post.

**Comment by peacememories** [comment]
Are you referring to the "Good match/Bad match" and "what's in your area?" buttons at the bottom of a connection/need? All other instances of footer elements seem to have been removed in the recent UI changes

**Comment by sigpie** [comment]
The share button has been moved, but the publish button and match acceptance/rejection buttons are still in the footer.

**Comment by peacememories** [comment]
So the idea is to move the buttons in question into the top bar? I think that's a good idea.
Since this issue has been otherwise inactive for the last month I would suggest we move this to "soon", and consider how exactly to modify the interface part of the task?

**Comment by peacememories** [comment]
This issue seems to have been inactive for some time. Maybe we should close it and create a new issue describing the task of moving the mentioned buttons?

**Comment by quasarchimaere** [comment]
i second the suggestion made by @peacememories

**Comment by peacememories** [comment]
Replaced by #2510
