### ISSUE TITLE
Post and Connection icon behaviour

### ISSUE THREAD

**Issue by sigpie** [researchstudio-sat/webofneeds#1808]
Right now, clicking on a post icon toggles the extended post view in the connections overview (left column), while clicking on a connection icon always opens the connection (right column). 

I would have expected that clicking on the post icon opens the Post Detail View in the right column. This should happen only if the post is already extended, to avoid unexpected view changes on mobile.

**Comment by sigpie** [comment]
@#discuss: Do we want to change the current behaviour or does it seem fine to everyone? If we want to change it, do we use the behaviour I suggested or is there a better way to do it?

**Comment by maxstolze** [comment]
@`#discuss`: We should change the behavior as suggested by @sigpie

**Comment by m0ru** [comment]
What's the suggested behaviour? :3

**Comment by maxstolze** [comment]
When connections are closed on the left row

1. Click on the icon -> toggle dropdown
2. Click with drop down -> show  "post detail view" in the right column

**Comment by quasarchimaere** [comment]
not sure if having two completely different actions on the same element is a good idea, may i remind the team that we changed this from a similar behaviour to the current one because people got confused that a view change happened when clicking the element (especially on mobile, ask @fkleedorfer aka dogfooding expert)

**Comment by peacememories** [comment]
Bumping because of continued inactivity

**Comment by maxstolze** [comment]
We could get rid of the [Details] button in desktop view. For the mobile view we should keep the button und just toggle dropdown when clicking on the need, because of to much unwanted screen changes.

**Comment by sigpie** [comment]
As suggested in #2530, this might require a user test to see what the expected behaviour is in this case. All current developers are too familiar with the actual behaviour to accurately tell expected behaviour.

**Comment by quasarchimaere** [comment]
no longer relevant, the views have been split
