### ISSUE TITLE
Only some conversations have identifying icons

### ISSUE THREAD

**Issue by sigpie** [researchstudio-sat/webofneeds#1811]
Only suggested matches have an identifying icon, other conversation types don't.

Additionally, the red icon in the corner looks a lot like unread notification bubbles for mobile phone apps or browser tabs. In combination with #1809, this may be confusing.

**Comment by peacememories** [comment]
Is this still relevant now that identicons have been introduced and the design changed a bit?

**Comment by sigpie** [comment]
Not relevant anymore, due to design changes all conversations have icons now.
