### ISSUE TITLE
Different text field focus colours

### ISSUE THREAD

**Issue by sigpie** [researchstudio-sat/webofneeds#1813]
When focusing a text field on desktop it's blue: ![focus_blue](https://user-images.githubusercontent.com/32930574/40430594-c2e28d2a-5ea5-11e8-9c28-c4b1c9a9c576.png)

But when focusing the same text field with the user agent set to a mobile device, it's orange: 
![focus_orange](https://user-images.githubusercontent.com/32930574/40430752-2128de70-5ea6-11e8-809c-4c2fe4a6da3c.png)

**Comment by quasarchimaere** [comment]
happens because of an user agent stylesheet -> 

:focus {
    outline: -webkit-focus-ring-color auto 5px;
    outline-color: -webkit-focus-ring-color;
    outline-style: auto;
    outline-width: 5px;
}

**Comment by fkleedorfer** [comment]
@quasarchimaere is this a bug or a feature?

**Comment by quasarchimaere** [comment]
@fkleedorfer, its a browser dependant feature -> user agent stylesheets, we could circumvent it by using our own stylesheets to overrule the browser ones so we would have a unified look and feel over all devices and browsers,... but its not a bug,chrome and firefox intend to do it on their own and we just didnt tell them not to yet

**Comment by m0ru** [comment]
Would be nice to have the colors fit our color scheme.
