### ISSUE TITLE
Fix CORS-Headers in Owner Webapp

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1815]
1. change the base-url in `config/default.js` to use a different owner-server (or alternatively start a static http-server in the owner-application folder on a different port than tomcat)
2. open the application
3. in the console there should be a 403-error caused by a cross-site request. 

When this is implemented we'll have additional development/debug-tools at our disposable and it also enables making the application progressive (i.e. adding a web-manifest so it can be pinned as desktop/mobile app)

(assigned to @fkleedorfer as nobody else i asked had an idea where to start looking)

**Comment by fkleedorfer** [comment]
I understood what you mean @m0ru and changed the issue title

**Comment by quasarchimaere** [comment]
moved to internal kanbanboard
