### ISSUE TITLE
Account Export

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#1821]
requires #2521

**Comment by peacememories** [comment]
Also implies: Account import

**Comment by peacememories** [comment]
I'm assuming this means exporting all needs (including personas) attached to an account. What should we do about connections? Try to restore them on import? Warn the user that connections will be lost?

**Comment by quasarchimaere** [comment]
I think we can push the import aside for now, what should probably be done to be GDPR compliant is to make it easy for the User to export all the data we stored about the User in a zip-file (probably the best solution) and to email it to the users email adress as an attachment.

I do agree that a export does not make alot of sense if there is no corresponding import, however i think the scope of this feature is just to be compliant to the gdpr, and to reduce administrative effort to crawl and "sum up" the data on a user-request (which we are probably obliged to do for legal reasons)

**Comment by sigpie** [comment]
According to the GDPR, data needs to be exported in a commonly used, machine readable format, which is fulfilled by providing the information in an RDF format. Information that was calculated from user data or retrieved from public sources doesn't need to be included.
