### ISSUE TITLE
Dev-Setup: Syntax highlighting for angular templates

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1834]
[As the vscode-team notes](https://github.com/Microsoft/vscode/issues/130), this will require a vscode-plugin. In particular we have two options here: 

* [lit-html](https://marketplace.visualstudio.com/items?itemName=bierner.lit-html)
* [angular2-inline](https://marketplace.visualstudio.com/items?itemName=natewallace.angular2-inline) (that also works with angular-1.x)

for both of these we'd need to change the code: for angular2-inline we need to move the template declarations to the return statements of the components, for lit-html all template strings need to be prefixed with `html` (e.g. [1]) thus turning them into [tagged template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals), which requires adding the babel-plugin [plugin-transform-template-literals](https://www.npmjs.com/package/@babel/plugin-transform-template-literals) as well as a dummy html-function, that just passes on the string uneditedly, to our builds.

Neither of these seems clean to me, however it would avoid bugs like the one @sigpie had to deal with where a long tag just wasn't closed properly and angular failed silently.

[1]:
```js
html`<p>example</p>`
```

**Comment by quasarchimaere** [comment]
i am not fond of either of the solutions as they require code changes/refactorings, yes they might avoid silent fails which are very annoying (as seen in the aforementioned case) but for now i think we cant afford another refactoring

**Comment by quasarchimaere** [comment]
i will close this issue, our dev-team already uses vs-code plugins to support exactlythat without having to change the code (afaik), @peacememories can you add the plugins + urls for said plugins within this issue
