### ISSUE TITLE
meta-discussion @ waffle

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1837]
If we have too many issues in the discussion column, it's hard to maintain an overview and find the ones that actually require quick feedback (as opposed to those requiring multiple hours of research and design work)

I'd propose a similar 3-column split for the design decisions (both technical as well as UI-design) as we have for code development (with the difference that I'd name the third column "RFC/Discussion" instead of "Testing")

Atm the discussion is a bit cluttered imo and a lot of issues require design work by a single person or a group in some kind of ideation session (Github's not a good place for that imo). On Github, we should limit ourselves to discussing the merits of a handful of concrete and pre-selected alternative designs. If none of the alternatives turns out to be good, with a 3-col setup, we can simply move the issue back to "In Progress" or "Ready" until someone sits down and researches or designs another solution. Alternatively, we can just use the same three columns that we use for development and move issues that require more research/design work to the "Ready"-column.

What do you think? do you run into the same problem? Or does the current setup work for you? :)

**Comment by quasarchimaere** [comment]
we discussed this in the jf now, and we are currently "ok" with the new process created -> closing this issue
