### ISSUE TITLE
dummy posts... how to handle it?

### ISSUE THREAD

**Issue by sbyim** [researchstudio-sat/webofneeds#184]
According to storyboard, a user can request a conversation to the owner of a post while viewing the page of the post by clicking on a button.
this simple action causes several backend actions.
1. a dummy post, which shall be used for connecting to the post selected, will be created for the user.
2. the dummy post will only be used for connecting to the post.
3. the dummy post shouldn't get any matches
4. the dummy post shouldn't be displayed anywhere.

How should we implement this concept?

Will it be enough if we introduce a "dummy facet"?

Since the dummy post shall feature the same "conversation" functionalities as a "normal" posts, it shall be stored in the needRepository.
Thus, the owner application will be responsible for filtering out the dummy posts when displaying needs. (e.g. search page).

**Comment by m0ru** [comment]
Issue related to old, deprecated prototype.
