### ISSUE TITLE
Implement Whats New Matcher

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#1843]
see tip in PR #1842 (File: WhatsNewQueryFactory.java)

Define how new the need has to be to match to a whats new, it should probably match to every need created after the whatsnew and maybe the last week before the creationDate of the whats new (suggestion), in anyway we should only match needs that are still open, the no hint for counterpart flag should already be implemented

**Comment by fkleedorfer** [comment]
Should also fix #1844

**Comment by quasarchimaere** [comment]
should not be needed anymore
