### ISSUE TITLE
Unique input field IDs on settings page

### ISSUE THREAD

**Issue by maxstolze** [researchstudio-sat/webofneeds#1849]
Problem with non-unique ids of the '\<input\>' fields in setting components.

![settings_ids](https://user-images.githubusercontent.com/32457902/40829962-52721bc8-6585-11e8-9322-2b6b9e51db92.png)

**Comment by quasarchimaere** [comment]
i think wecan just remove all the id references used, since we dont access or need them anyway (but maybe this issue resolves itself during the rework ofthesettings page)

**Comment by fkleedorfer** [comment]
Does this have an impact on users?

**Comment by quasarchimaere** [comment]
its not valid to use non unique id's in html elements its just ignored by most browsers, it doesnt have an impact on the user it simply looks horrible in the console log and the dom

**Comment by quasarchimaere** [comment]
no longer relevant, settings page has been updated and refactored
