### ISSUE TITLE
Demonstrate end to end taxi use case

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1854]
Using the TTL input field, create a need that can be used to come to an agreement with the taxi bot. 

Make sure that this works, and note any problems in this issue. 

Repeat as soon as the post details can be used to create the Need.

**Comment by fkleedorfer** [comment]
I think this needs a the magic touch of @quasarchimaere before it can be taken up by someone else

**Comment by maxstolze** [comment]
Done without TTL, but new route picker.
