### ISSUE TITLE
Bug in Dev Environment

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#1863]
![img_20180605_083149](https://user-images.githubusercontent.com/8503486/40958890-31b1ed1e-689b-11e8-83dd-075a2de11e2e.jpg)
not sure if this is a blocking issue....

i named it grace...

**Comment by maxstolze** [comment]
Can we locate it again?

**Comment by quasarchimaere** [comment]
it seems it has disappeared. marking this issue as no longer relevant
