### ISSUE TITLE
What's in your area button too large

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1876]
The button: 

`What's in your Area? (Location access required)`

on a What's New? need's detail view causes the right view to scroll horizontally, thereby hiding e.g. the menu button. (probably the only reason for opening that view: archive that need)

Solution: Find a shorter label
Suggestion1: remove the bracket expression
Suggestion2: add a line break before the bracket expressionlines

**Comment by quasarchimaere** [comment]
i am for solution 1

**Comment by fkleedorfer** [comment]
2 column-layout:
![grafik](https://user-images.githubusercontent.com/551624/41039687-8222e3ac-699a-11e8-93dd-de175cb54538.png)

1 columen layout:
![grafik](https://user-images.githubusercontent.com/551624/41039730-ace6342c-699a-11e8-8da7-076ffa0cee90.png)
