### ISSUE TITLE
Style "Search" and "Post" buttons

### ISSUE THREAD

**Issue by sigpie** [researchstudio-sat/webofneeds#1877]
The current styling of the buttons used to access the need creation view doesn't fit the remaining app very well. 

They should look and act more like other buttons (for example: use the primary colour as a background colour or as a text and border colour).

Also, there should be some indication that a button is selected. This is already implemented (a `selected` css class is added on click), but not visually represented.

**Comment by quasarchimaere** [comment]
these buttons used to be on top of the conversation list, the buttons have been moved -> this issue is no longer relevant
