### ISSUE TITLE
Error in need icon tooltip

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1879]
The icon's tool tip text says `self.need.get('titile')`
That's weird for two reasons:
1. It should be the title, not the select expression
2. we made the new icons so we don't have to rely on a title, so even if this worked, it would not make so much sense.

Suggested solution: get rid of the tooltip or only add it if there is a title

**Comment by quasarchimaere** [comment]
solution will be getting rid of the tooltip, there is some issue with ng-attr-title and weird brakcet whatever, so i am not going to figure this out for something that mediocre -> the title is visible anyway
