### ISSUE TITLE
Draft auto-saving is not implemented yet

### ISSUE THREAD

**Issue by yanapanchenko** [researchstudio-sat/webofneeds#188]
According to the storyboard, the draft auto-saving should happen every minutes (described in 5.2 in "Save Draft") and with every 'step' (described in 5.2 "Steps"). 

Question to storyboard: in 5.2 in "Save Draft" in relation to auto-saving, every minute counter in brackets and spinning wheel is mentioned - I find no pictures in storyboard demonstrating that.

**Comment by quasarchimaere** [comment]
no longer relevant
