### ISSUE TITLE
Missing click-Indicators

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1881]
One reason the application seems slow is that most clicks have no visible effect at all until their full effect is shown. 

Solution: make all clickable elements show that they received the click by changing its color for some time - immediatly. 

We do that with some buttons, let's do it with all of them.

**Comment by quasarchimaere** [comment]
not really easy to implement especially with the timer, would have to refer this to our frontend specialists to find a valid solution, i assume this issue includes the post button but also the details of a need as well as the dropdowns that open the connection lists right?

**Comment by fkleedorfer** [comment]
Yes.

**Comment by fkleedorfer** [comment]
de-childed from #1852. This issue is a bigger design thing, and we've made quite some progress on the performance issues, so this is demoted to 'fancy idea status'.
