### ISSUE TITLE
Add privacy policy etc. links to main page

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1888]
We need to link to a few documents from the main page. 
Ideally, this is entirely configurable in the skin, such that we can have different numbers of links and entirely different documents per skin

child of #1866

use the imprint.html (within the uki skin (meicogsci) to add all necessary content in terms of agreement etc.)

then implement a slide-in (similar to the slide-in for reconnect (is implemented in topnav.js) that pops up if a imprint.html is present within the skin and a certain flag "privacyPolicySeen" (or other name) is not yet saved in the localStorage.

TODO:
-implement the new slide-in with a conditional (conditions: show if imprint.html present in skin and localStorage flag is not yet saved)
-implement the save and retrieval in the local storage
-link the imprint.html within the text of the slide-in as a link

**Comment by quasarchimaere** [comment]
child of #1866

**Comment by quasarchimaere** [comment]
seeing how there currently is an imprintTemplate in every configured skin, i think its save to say that we can only look for the condition of the localStorage
