### ISSUE TITLE
Using "copy link" button?

### ISSUE THREAD

**Issue by sbyim** [researchstudio-sat/webofneeds#190]
Storyboard ver 50. page  92,  6.4.3.2. Contact Confirmation View - no account. describes that 
"a button with an icon for copying and the text "copy link" shall be provided and that clicking on this button will copy the private link.

However, it seems like we have to consider some issues when we want to implement it this way.
From http://kb.mozillazine.org/Granting_JavaScript_access_to_the_clipboard

> "Granting JavaScript access to the clipboard
> By default, JavaScript is not allowed to read or set your clipboard data for security and privacy reasons. This is because websites scripts can erase and replace what you currently have in your clipboard (data loss issue) and they can read whatever you have in your clipboard (security and privacy issue); as such, you should grant access with caution. There are, however, instances when you might want to bypass this restriction for certain sites. Rich text editors (such as implementations of Mozilla's Midas) often require access to the clipboard to use copy/paste functions. Other sites may copy useful information to the clipboard for the user to paste elsewhere."

ZeroClipboard(https://github.com/zeroclipboard/zeroclipboard), which is used by ng-clip, a anglularjs component for clipboard copying, seems to make use of flash, because of the above mentioned restrictions.

Flash, AFAIK, is not supported by every browser. 

Maybe this could help. http://www.w3.org/TR/clipboard-apis/

**Comment by yanapanchenko** [comment]
http://ngmodules.org/modules/ng-clip

Specifying a fallback function if flash is not there seems like a good solution (e.g. pre-selecting the link text and just asking user to press ctrl+c)

**Comment by m0ru** [comment]
"Flash, AFAIK, is not supported by every browser."  <- Thankfully ^^ (It's most browsers biggest security whole and resource leak + is technically obsoleted by modern html/css/js)

+1 what @yanapanchenko wrote

**Comment by sbyim** [comment]
using ng-clip won't be an option if we don't want to use flash.
taken from their page.
>Usage
Add ng-clip.js and ZeroClipboard.js to your main file (index.html)
Update the .swf path location using ngClipProvider javascript .config(['ngClipProvider', function(ngClipProvider) { ngClipProvider.setPath("bower_components/zeroclipboard/dist/ZeroClipboard.swf"); }]);

So it's dependent on ZeroClipboard which is flash based.

**Comment by yanapanchenko** [comment]
Implemented, as of ff10ff4, with ng-clip (i.e. ZeroClipboard and Flash) with fallback function in case the flash is disabled/not present in the browser. The fallback just asks the user to press cmd+c. Two issues though with the copy to clipboard functionality:

1. for some reason, clicking the copy button copies only with the second click
2. the storyboard should specify the more pretty fallback than it is implemented now:
![fallback-copy](https://cloud.githubusercontent.com/assets/7224202/6153222/5f2e5034-b223-11e4-8229-75f256343168.PNG)

**Comment by yanapanchenko** [comment]
1. is somehow solved by itself: today with fresh clean-install-run the copy works as expected

**Comment by sbyim** [comment]
@yanapanchenko can we close this now?

**Comment by yanapanchenko** [comment]
the part about "storyboard should specify the more pretty fallback" is missing, otherwise it's done. I am removing the question label.

**Comment by m0ru** [comment]
Issue related to old, deprecated prototype.
