### ISSUE TITLE
accept/reject/propose/retract buttons on same line

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1900]
These buttons uses do be horizontally aligned, now they are vertically left-aligned, which looks weird and takes up more space than requried.

**Comment by quasarchimaere** [comment]
yes it surely looks weird now, i dont know how one would fit all 4 buttons horizontally though but nevertheless it will be possible, just please make sure that the message aligment itself is kept (its pre-wrapped) so we dont have to parse the new lines into <br/>s
