### ISSUE TITLE
MeiCogSci Skin

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#1902]
Create a special MeiCogSci Skin (instead of the uki skin, but keep all the existing folder names -> because the deployment is already set up and working)

take color scheme from:
http://www.meicogsci.eu/

for title and additional config please look into the other tickets (children of #1866) or talk to @fkleedorfer

child of #1866

**Comment by fkleedorfer** [comment]
@quasarchimaere Pls close if you think this is done

**Comment by quasarchimaere** [comment]
seems good enough for me, marking it done as requested
