### ISSUE TITLE
own match not filtered after being archived

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1903]
My own need shows up as a match as soon as I archive it.

Steps to reproduce:
1. create 2 needs that would match
2. archive one of them
3. Reload

Observe that the archived need is now a match to the other one.

**Comment by quasarchimaere** [comment]
the title is confusing, it says the own match is not filtered after being archived, but in fact the need was archived instead

**Comment by quasarchimaere** [comment]
this should could also fix #1739 as well
