### ISSUE TITLE
Logging out does not clear unloaded needs

### ISSUE THREAD

**Issue by peacememories** [researchstudio-sat/webofneeds#1909]
After logging out, the interface will continue to display all the archived needs of the old user as unloaded need count. This is because the unloaded needs in localStorage are not cleared on logout.
Also, they should get cleared when loading the archived needs.

**Comment by quasarchimaere** [comment]
i dont think that we should clear the list on logout, or even after loading the archived needs, this would defeat the whole purpose of storing the uris in the localstorage in the first place -> we wanted a performance increase after a login/reload, we would not get that increase if we start clearing the localstorage

**Comment by peacememories** [comment]
Then we need to get the list of needs for a user (not just loaded ones) into the state so the view can filter on that

**Comment by quasarchimaere** [comment]
well technically we can just prohibit showing the unloaded needs when a user is logged out, that way we dont have to save anything in the state.

**Comment by peacememories** [comment]
The problem is that even when logged in as a different user the unloaded need count will include the unloaded needs of the previous one. This is because there is no way for the view to establish whether an unloaded need is in fact owned by the current user just from the uri.
Solutions:

* Clear the unloaded needs list on every logout

    As mentioned above this would impair the effect of the lazy-loading of needs, but I would say that users do not log out and in so often that the increased load time would hurt them much.
* Add the list of need URIs a user owns to the state

    This would allow the view to filter the unloaded needs correctly, but would mean adding a new piece of data to the state.
* Do not correct the unloaded needs number but clear the local storage whenever unloaded needs are loaded

    This at least makes the problem "fixable" by just clicking the load button. After loading the list would only contain needs owned by the current user.
