### ISSUE TITLE
"Post Detail View" connect with own post. 

### ISSUE THREAD

**Issue by sbyim** [researchstudio-sat/webofneeds#191]
According to the storyboard ver.50 page 85, it states that "Select your post" is a dropdown list which contains all the posts the users possess.
This however could be irritating.
1. It will also display "dummy posts"
2. It will display all posts without considering the basicNeedType of the need selected for post detail view. If the need displayed in post detail view is of type "Demand", only "Supply" type of posts shall be listed and vice versa

**Comment by fkleedorfer** [comment]
I agree with everything that has been said. Let's imagine a user who arrives at the post-detail view of a posting (P) and wants to connect. What would he/she expect to happen? 
1. Case A: User is not logged in, hasn't created a posting (in the current session, didn't come with private link)
 1. Create new posting, connect with P
2. Case B: User is not logged in, but has created a posting anonymously.
 1. Connect existing post with P
 2. Create new posting, connect with P
3. Case C: User is logged in, has multiple postings.
 1. Connect existing post with P. Ranking:
  1. Posts that already have suggested connections to P 
  2. Posts that the user recently interacted with
  3. Rest of the posts
 2. Create new post and connect with P

My feeling is that this should be a 2-step process in the GUI
* First: user decides if he/she wants to connect
* Then: user works out how to do that

**Comment by m0ru** [comment]
Issue related to old, deprecated prototype.
