### ISSUE TITLE
click on match after scrolling down leads to confusing scroll to top

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1911]
Happens only in 2-column view.

Steps to reproduce:
1. create a need that will have many matches ("What's Around")
2. expand it in the list
3. scroll down toward the end of the list
4. click on one of the matches

Observe that the connection view is opened on the right hand side and the list scrolls up again, and that you are now confused.

Reason: The right hand side view should not scroll together with the left hand side view, but rather fill the available vertical space (and maybe scroll its own content - but that may cause additional problems )

**Comment by sigpie** [comment]
This is also an issue in 1-column view. Clicking on a match works fine, but when returning to the connection overview, the scrolling position is reset. This makes it very annoying to look through suggested matches.

**Comment by peacememories** [comment]
I think this is because when our route changes angular rerenders the whole interface. During this change the dom is emptied, which resets the scroll position.
As a workaround we could remember the scroll position before initiating a route change, but I don't think we can do better than that with our current setup.

**Comment by quasarchimaere** [comment]
it would be nice if we could fix the position of the right side in desktop view, especially if we remember the scrollpostion of a clicked listelement, otherwise we would not notice that anything has opened on the right side (in long lists)
