### ISSUE TITLE
Prevent the impression that a message was sent when it really wasn't

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1913]
When the app loses the connection to the server, it is sometimes still possible to send messages in a connection. Messages are then displayed in the chat view. However, those messages are not really sent and after a reload, they are gone.

Solution: 
* [x] use the two success responses we get for each message to display its sending status
* [ ] allow re-sending a message after a certain timeout if no or only one success response was received.

Child of #1885

**Comment by quasarchimaere** [comment]
if we alter the messages redux structure we can't forget to include the updates within the message in the optimisticEvent as well see need-reducer.js:193
