### ISSUE TITLE
Make 'reconnect' actually reconnect

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1914]
Sometimes (always?) when the app loses the WS connection to the server and the user clicks the 'reconnect' button on the 'lost connection' popdown, the WS is connected but the user is not logged in; consequently, nothing the user does has any effect. 

Solution: try to login upon reconnect. If the session is still valid (most of the time this will be the case), the login should just work. If the remember-me cookie is set, this should even work after a longer time. 
If the session is really dead, we should offer to re-login (and we should probably clear the complete application state at this point, including localstorage).

Child of #1885

**Comment by quasarchimaere** [comment]
notsure if localstorage clearing on logout is the way to go
