### ISSUE TITLE
Publishing needs is not disabled while disconnected

### ISSUE THREAD

**Issue by sigpie** [researchstudio-sat/webofneeds#1926]
When the connection to the server is lost, it's still possible to create new needs. Those needs only exist as placeholders until the page is reloaded, at which point they'll disappear. Maybe we should disable the Publish button until the session is reconnected.

**Comment by quasarchimaere** [comment]
just found out one can induce the connection loss by executing ´cnc.$ngRedux.dispatch(actionCreators4Dbg.lostConnection())´ within the dev console
