### ISSUE TITLE
Can reconnect with invalid private-id

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1927]
steps to reproduce:

1. post a need to create a private-id account
2. restart the server, the private id shouldn't exist any more (assuming you're using an in-memory db)
3. click the reconnect button once it shows up in the owner application
4. the slide-in goes away even though the login can't have been successful

**Comment by quasarchimaere** [comment]
is that not the correct case as the "login" of a privateId user is actually a sign up of the privateId-user and therefore will be signed up after a server restart (i assume this happened on a local owner with a hsql db and therefore the user is def not presetn and therefore will just be created)

**Comment by peacememories** [comment]
Discussion around this topic seems to have stalled. Do you want to add anything to the conversation? If not, I would suggest closing this issue.

**Comment by quasarchimaere** [comment]
we close it
