### ISSUE TITLE
SignUp displays the disclaimer for each keypress in a login field

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#1931]
rhe disclaimer is shown no matter if it was already accepted or not whenever you type within a field of the signup form (maybe even within the login menu idk)

anyway the problem is due to the user in the reduxstate which apparently does not include the default parameter "acceptedDisclaimer" when storing the formdata within the state

**Comment by quasarchimaere** [comment]
user-reducer.js:56 is missing the a part of the return value -> namely acceptedDisclaimer: userData.get("acceptedDisclaimer")

should be added and that will fix the issue

see actionTypes.logout for correct syntax, since this actionType is already implementing the acceptDisclaimer properly

**Comment by fkleedorfer** [comment]
PR #1934 did not fix this

**Comment by fkleedorfer** [comment]
Fixed by #1937
