### ISSUE TITLE
having Many Default Matching Contexts looks off in mobile view

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#1941]
![screenshot_20180613-230204](https://user-images.githubusercontent.com/8503486/41377991-07c500a8-6f5e-11e8-9c68-2af21e2a32a1.png)

-the checkboxes look unattached to their labels due to the vertical alignment of the individual contexts

**Comment by fkleedorfer** [comment]
Good enough for now
