### ISSUE TITLE
Direct Link to a post (aka VisitorLink) in mobile does not give info about the logged in user

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#1951]
if you access a direct link (e.g  https://meicogsci.matchat.org/owner/#!/post/?postUri=https:%2F%2Fnode.matchat.org%2Fwon%2Fresource%2Fneed%2Fw8je0odt5h9f ) on a mobile device, you have no way to see if you are logged in or if so with which user, you also dont have the ability to even start a login or sign up, since there is no back button or anything.

**Comment by peacememories** [comment]
Should we start showing the title bar again, or should we modify the visitor title bar to contain an account menu?
