### ISSUE TITLE
Sign Up is hidden in responsive mode

### ISSUE THREAD

**Issue by sigpie** [researchstudio-sat/webofneeds#1953]
When in responsive mode, the signup button disappears from the title bar and moves to the user menu. This makes it harder for new users to create accounts. Additionally, it's only a small text at the button of the user menu instead of a separate button.

![signup_mobile](https://user-images.githubusercontent.com/32930574/41460112-d7bcd794-708b-11e8-86a5-5e0a5ec6d164.PNG)

**Comment by quasarchimaere** [comment]
also a remark from my side, in responsive mode i find it rather difficult to distinguish between not being logged in at all or being logged in but not seeing my posts yet (or not having any)

**Comment by fkleedorfer** [comment]
Seems very important, especially today, if improved quickly.
