### ISSUE TITLE
Person Picker

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1964]
We need these fields:
* [ ] Name
* [ ] academic title
* [ ] Company
* [ ] Position
* [ ] Skills
* [ ] Bio

**Comment by sigpie** [comment]
I'm trying to match these to RDF definitions, this is what I've found so far:

- [ ] Name: https://schema.org/name
- [ ] Academic Title: maybe https://schema.org/honorificPrefix and https://schema.org/honorificSuffix
- [ ] Company: https://schema.org/affiliation or https://schema.org/worksFor
- [ ] Position: https://schema.org/jobTitle
- [ ] Skills: maybe https://pending.schema.org/knowsAbout
- [ ] Bio: ?
