### ISSUE TITLE
Restrict relevant matching time

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1971]
We need a way to inform matchers of a time span during which the need is suitable for matching.
parent of #1972
parent of #1973
parent of #1974
parent of #2003

**Comment by fkleedorfer** [comment]
Added the datataype properties to be used to the ontology in feat-doNotMatchBeforeAfter: 
* won:doNotMatchBefore
* won:doNotMatchAfter
both are properties of the need, the datatype is xsd:DateTimeStamp

**Comment by m0ru** [comment]
Will be delayed for a bit. Meanwhile here's my notes (including amongst others a list of time-pickers that might be applicable):

---

just match until event's end time (or use that as match-until). some use cases might use constant match-durations (e.g. now+10mins for taxi or now+1week in general)

there's no recovery if the match-time runs out

time-picker for events

repeat events? `[(start, end)*]`. use latest `end` for match-until.



<https://github.com/researchstudio-sat/webofneeds/compare/feat-doNotMatchBeforeAfter>

```ttl
:doNotMatchBefore rdf:type owl:DatatypeProperty ,
                     owl:FunctionalProperty ;
            rdfs:domain :Need ;
            rdfs:range xsd:dateTime ;
            rdfs:comment "Indicates that matchers should not use this need for matching before the specified xsd:dateTime."@en ;
            rdfs:isDefinedBy <http://purl.org/webofneeds/model> .

###  http://purl.org/webofneeds/model#doNotMatchAfter
:doNotMatchAfter rdf:type owl:DatatypeProperty ,
                     owl:FunctionalProperty ;
            rdfs:domain :Need ;
            rdfs:range xsd:dateTime ;
            rdfs:comment "Indicates that matchers should not use this need for matching after the specified xsd:dateTime."@en ;
            rdfs:isDefinedBy <http://purl.org/webofneeds/model> .
```


searching for pickers that give a date-time-range or single date, are usable and don't have dependencies (ideally not even angular).


* <https://www.npmjs.com/package/extended-datetimepicker> (angular, clock for hours and minutes(!); [demo](https://rawgit.com/amittkSharma/extended-datetimepicker/master/index.html))
* <https://www.npmjs.com/package/sc-date-time> (angular, date-time, focus on date(?), clock for time(!); [demo](https://codepen.io/SimeonC/pen/XJdWPy))
* <https://www.npmjs.com/package/angular-datetime-inputs> (angular, date-time, focus on time; [demo](https://rawgit.com/g1eb/angular-datetime-inputs/master/))
* <https://www.npmjs.com/package/angular-datetime-range> (angular, date-time range, focus on time; [demo](https://rawgit.com/g1eb/angular-datetime-range/master/))
* <https://www.npmjs.com/package/@senzil/angular-datetime-range> (angular, date-time range, focus on time; [demo](https://rawgit.com/senzil/angular-datetime-range/master/))
* <https://www.npmjs.com/package/datetime-range-picker> (angular+jquery, date-time range, both, time as 24h slider; [demo](https://rgkevin.github.io/datetimeRangePicker/#/home))
* <https://www.npmjs.com/package/angularjs-datetime-picker-v2> (angular, date-time, time as slider; [demo](https://rawgit.com/mani-s17/angularjs-datetime-picker/master/index.html))
* <https://www.webcomponents.org/element/fooloomanzoo/datetime-input> (polymer, date-time, just fancy text-field)
* <https://www.webcomponents.org/element/fooloomanzoo/datetime-picker> (polymer, date-time)
* <https://www.webcomponents.org/element/RoXuS/range-datepicker> (polymer, date range; [demo](https://roxus.github.io/range-datepicker/components/range-datepicker/demo/))

[moment.js](http://momentjs.com/) provides time utils (e.g. formatting and adding time). [momento](https://www.npmjs.com/package/momento) makes them more functional.

---

**Comment by quasarchimaere** [comment]
could be implemented with the won:hasQuery now, might be good to look into that instead of adding the ontology properties above (or in addition to it)

**Comment by quasarchimaere** [comment]
not sure why this is still open, all the child issues have been closed (@fkleedorfer: can we close this issue?)
