### ISSUE TITLE
matching time

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1972]
implement 'tune matching' detail for relevant time

**Comment by m0ru** [comment]
Will be delayed for a bit. Meanwhile here's my notes (including amongst others a list of time-pickers that might be applicable):

---

just match until event's end time (or use that as match-until). some use cases might use constant match-durations (e.g. now+10mins for taxi or now+1week in general)

there's no recovery if the match-time runs out

time-picker for events

repeat events? `[(start, end)*]`. use latest `end` for match-until.



<https://github.com/researchstudio-sat/webofneeds/compare/feat-doNotMatchBeforeAfter>

```ttl
:doNotMatchBefore rdf:type owl:DatatypeProperty ,
                     owl:FunctionalProperty ;
            rdfs:domain :Need ;
            rdfs:range xsd:dateTime ;
            rdfs:comment "Indicates that matchers should not use this need for matching before the specified xsd:dateTime."@en ;
            rdfs:isDefinedBy <http://purl.org/webofneeds/model> .

###  http://purl.org/webofneeds/model#doNotMatchAfter
:doNotMatchAfter rdf:type owl:DatatypeProperty ,
                     owl:FunctionalProperty ;
            rdfs:domain :Need ;
            rdfs:range xsd:dateTime ;
            rdfs:comment "Indicates that matchers should not use this need for matching after the specified xsd:dateTime."@en ;
            rdfs:isDefinedBy <http://purl.org/webofneeds/model> .
```


searching for pickers that give a date-time-range or single date, are usable and don't have dependencies (ideally not even angular).


* <https://www.npmjs.com/package/extended-datetimepicker> (angular, clock for hours and minutes(!); [demo](https://rawgit.com/amittkSharma/extended-datetimepicker/master/index.html))
* <https://www.npmjs.com/package/sc-date-time> (angular, date-time, focus on date(?), clock for time(!); [demo](https://codepen.io/SimeonC/pen/XJdWPy))
* <https://www.npmjs.com/package/angular-datetime-inputs> (angular, date-time, focus on time; [demo](https://rawgit.com/g1eb/angular-datetime-inputs/master/))
* <https://www.npmjs.com/package/angular-datetime-range> (angular, date-time range, focus on time; [demo](https://rawgit.com/g1eb/angular-datetime-range/master/))
* <https://www.npmjs.com/package/@senzil/angular-datetime-range> (angular, date-time range, focus on time; [demo](https://rawgit.com/senzil/angular-datetime-range/master/))
* <https://www.npmjs.com/package/datetime-range-picker> (angular+jquery, date-time range, both, time as 24h slider; [demo](https://rgkevin.github.io/datetimeRangePicker/#/home))
* <https://www.npmjs.com/package/angularjs-datetime-picker-v2> (angular, date-time, time as slider; [demo](https://rawgit.com/mani-s17/angularjs-datetime-picker/master/index.html))
* <https://www.webcomponents.org/element/fooloomanzoo/datetime-input> (polymer, date-time, just fancy text-field)
* <https://www.webcomponents.org/element/fooloomanzoo/datetime-picker> (polymer, date-time)
* <https://www.webcomponents.org/element/RoXuS/range-datepicker> (polymer, date range; [demo](https://roxus.github.io/range-datepicker/components/range-datepicker/demo/))

[moment.js](http://momentjs.com/) provides time utils (e.g. formatting and adding time). [momento](https://www.npmjs.com/package/momento) makes them more functional.

---

**Comment by fkleedorfer** [comment]
We need to think about the lifecycle of a need. There are multiple characteristic intervals and points in time for a need:

From the point of view of the owner:
1. the date/time when I create it
2. interval during which matching makes sense for me
3. interval during which (pre/post-)transaction communication may occur, if there is any at all
4. if the need is about some transaction/event: time or interval when it will likely take place ( e.g., dinner tonight)
5. date after which the need becomes stale (solved in another way, opportunity gone, ...)
6. There may be some interval at which the need becomes relevant again (e.g. weekly, monthly, seasonal, ...). this could be seen as  an event similar to creation, with respect to the lifecycle.

Where does it impact the system?
* A WoN node should be informed about 5: it's the point in time at which it should be deactivated.
* A matcher should learn 2, which is a function of 4 and 5
* The  GUI should make reasonable assumptions based on the use case (e.g. taxi demand vs. real estate offer), but allow fine-grained control, at least for generic postings.

The current approach is to send a warning about closing and then later to close the need. Users get confused because they have no way of recovery (=keeping the need active) when the warning comes unless they get new matches with which they can interact. This is an ok way to get rid of stale needs, but the recovery path needs to be improved.

My favoured solution is to set the matching interval based on the data entered on a per-usecase basis:
* if a time is set in the need, the matching interval starts now and ends at that time
* else if an interval is set in the need, the matching interval starts now and ends at the end 
* else the matching interval starts now and ends after a usecase-specific timeout
* if the user chooses to change the matching interval, the initial values are calculated based on the rules above.
* No more automatic deactivation by the WoN node
