### ISSUE TITLE
adapt matchers to respect won:hasSearchString

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1978]
`won:hasSearchString` must be respected by matchers, looking for the string in all fields

child of #1976

**Comment by peacememories** [comment]
I don't believe every matcher should be required to respect this. This is definitely a feature some matcher can fulfill easier than others.

**Comment by fkleedorfer** [comment]
Ok, SHOULD

**Comment by peacememories** [comment]
What I mean by that is that it’s enough for one matcher to recognize the flag
