### ISSUE TITLE
Hints are not displayed correctly in conversation

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1988]
In an ongoing conversation, it's possible that more hints are received. These are displayed as unrenderable messages from the counterpart:

![unbenannt](https://user-images.githubusercontent.com/551624/41649688-75ccd148-747c-11e8-8a51-d12fcf44adbb.PNG)

These messages are wrong and confusing and should either not be displayed at all or be explained properly, such that a user unfamiliar with WoN can understand what has happened.

Issues are:
* [ ] remove the sender icon or replace it with something that a) expresses 'this comes from a matcher' or b) is matcher-specific (e.g. identicon based on matcher url) or c) conveys 'this is from "the system" '
* [ ] the content of the message should be analyzed and its meaning conveyed in a human readable fashion
* [ ] it would be good if this message was also visually different from a counterpart message or somehow collapsed and rendered minimally

**Comment by quasarchimaere** [comment]
fixed
