### ISSUE TITLE
Location Suggestion Styling

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#1997]
is there a reason why we dont use the whole width for the suggestionbox? if not i think we should use the whole space. it looks rather weird imho
![screenshot_20180621-160548](https://user-images.githubusercontent.com/8503486/41724150-36cb99e2-756d-11e8-8af4-46f138b58dec.png)

**Comment by sigpie** [comment]
If I remember correctly, this was done to avoid the impression that the search results replace the map and to ensure that people can still close the search results (as they're only visible while the input field is focused) on mobile. If the margins on either side are enough for this, there's no reason not to make the results wider.

**Comment by fkleedorfer** [comment]
I think we can safely use the whole screen for that.
