### ISSUE TITLE
Add Notifications

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1999]
We should use notifications to alert users when something like that happens. I suggest implementing an aggressive setting first. When we see which notifications are too much, we can reduce them.

Any hint/open/connect/message/close received while the application is not shown should increment a counter (one per types hint/open/connect/connectionMessage/close).
After N seconds without new messages, a notification, such as: "X new Match(es), Y chats requests, Z chats accpted W chats closed" 
should be shown.

We need to filter hints that do not create new connections and hints that point to own needs.

Asking for permission should be done after posting the first need in each session.

**Comment by fkleedorfer** [comment]
docs: https://developer.mozilla.org/en-US/docs/Web/API/notification

**Comment by quasarchimaere** [comment]
not sure if we can implement this without putting the ws handling (messaging-agent.js) and rdf store in a webworker first so we can use these in a separate somewhat progressive webapp approach which can also enable notifications, so moving these things into a separate part that can run in its own thread is probably a necessary step before figuring out the notification system

**Comment by fkleedorfer** [comment]
@peacememories' research result: notifications are available on Android only using service workers, on IOS not at all. We're waiting with this.

**Comment by quasarchimaere** [comment]
closes #2284
closes #2658

**Comment by quasarchimaere** [comment]
we already have notifications... we might need a refactoring/adaptation to enhance the UX but for now this item is done
