### ISSUE TITLE
unread counters show incorrect values

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#2001]
I have a number of conversations in which the unread counters stay at 1, no matter how often I open them.

Cannot really say how to reproduce, trying a few conversations with the debugbot might do the trick

**Comment by quasarchimaere** [comment]
are there any messages in the state that are flagged as unread, it could be possible that there is an unread message that somehow was not flagged as read (maybe due to it not being visible in the gui ever)

**Comment by quasarchimaere** [comment]
might be fixed with the #2009 pull request, you or anybody else but me can test this again after the PR is merged

**Comment by quasarchimaere** [comment]
possibly related too #2137
