### ISSUE TITLE
Arbitrary RDF: show "non-displayable content" warning

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#2012]
...if there's RDF we don't have components for. This goes for needs (in post-info) and, even more important, messages! The latter already have a placeholder, but that only checks wether or not `won:hasTextMessage` is there. It's possible for a message to have a text-message _in addition to_ non-displayable content, which can be problematic if that message is part of a formal agreement (or even just normal interaction as the other persons owner app might be able to display it, hiding a potential communication mishap).

requires #1994

**Comment by fkleedorfer** [comment]
Keeping in mind that the predominant case currently is not the case in which people get hacked and some additional content is in the message, but in which e.g.,  it's a connect message or a hint message with non-displayable content that we choose not to display. It's not correct to show a warning in these cases. See #1988.

**Comment by fkleedorfer** [comment]
Depends on #1994

**Comment by quasarchimaere** [comment]
moved to internal kanban board
