### ISSUE TITLE
Proposal fold-out gets hidden on digest/component-update

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#2031]
When you fold out a 'Propose' or 'Accept Proposal' chat-bubble, it gets closed again on the next digest-cycle, e.g. when a new message arrives or an application tick happens. Especially the latter can seem random and rather annoying.

**Comment by quasarchimaere** [comment]
see comment on issue #2030

**Comment by quasarchimaere** [comment]
oh nvm i did not tackle this issue at all yet :-/
