### ISSUE TITLE
Parse arbitrary details

### ISSUE THREAD

**Issue by sigpie** [researchstudio-sat/webofneeds#2036]
To parse detail information, the `need-builder` requires knowledge of the structure of each specific detail. As a result, this and other files need to be edited to add support for a new detail type. To support arbitrary details, none of the files should need any hardcoded detail structure information.

This could be done by e.g. defining a template in `detail-definitions`, adjusting all detail-pickers to return valid JSON-LD, or implementing and exposing a parsing method in each detail-picker.

**Comment by fkleedorfer** [comment]
How about: each detail receives the whole jsonld structure and the json path indicating where its data is located, for parsing data and displaying the controls - and it writes the data back the same way?

**Comment by m0ru** [comment]
@whole jsonld structure: this would mean no (i.e. really bad) isolation between the pickers and allow spooky action at a distance -- it would basically be shared memory. I don't see a good use-case why the picker should see each others' data, so why invite a source of bugs?

I'm in favor of just letting each picker spit out jsonld (or a string-literal) plus a predicate under which it will be put into the is/seeks-node. Initializing from a draft can use the same predicate to select the right data and pass it to the component as jsonld object.
