### ISSUE TITLE
Post title handling

### ISSUE THREAD

**Issue by sigpie** [researchstudio-sat/webofneeds#2037]
When creating a new need, the title is currently saved in up to three places: on the root-level of the need, in the `is` part (if that part is present) and in the `seeks` part (if that part is present). This is a result of not treating the title consistently.

I think there are two options to handle the title:
* title is a top-level detail, not a part of either `is` or `seeks`. In this case, the title should be saved only in the need's root-level and the textfield for setting a title should be moved from `create-isseeks` to `create-post`.
* title is a detail of `is` and `seeks` and the parts can have different titles. In this case, the title should be edited via a new `title-picker` and shouldn't be saved in the need's root level. 

Pure search isn't a concern here, as the `searchString` for this use case is already saved as a separate property in the need's root-level.

**Comment by peacememories** [comment]
I think especially after introducing our usecases we won't need titles when authoring needs anymore. A `hasHumanReadable` or similar could be a predicate on the root element as a fallback if the client cannot infer a title for the need?
Although this is probably up for discussion under the umbrella of "do we put the smarts of our systems in the protocol or the infrastructure?"
Maybe we should start an issue just for that as well^^'

**Comment by m0ru** [comment]
We might just want to have one free-form text field in that case (atm it's title+description). The first line / $x chars might then be used as `hasHumanReadable`. Or just the entire thing as its cropped anyway. In any case, this would profit from some sort of preview mechanism so people can predict how their post will look to others.

**Comment by quasarchimaere** [comment]
title will be a detail that can be added to each usecase seeks/is "branch" but will not be a necessity anymore

**Comment by peacememories** [comment]
If this is a decision that has been made, I think the issue should be moved out of the "clarify" column.

**Comment by sigpie** [comment]
after title is changed to be just a detail, we'll need to find a way to get a `hasHumanReadable` or something else to display as "title" for posts. Otherwise, we'll have way to many places that depend on there being a title detail for displaying posts. Or all posts will show as having <No Title>.
