### ISSUE TITLE
Unknown provider: applicationStateServiceProvider

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#204]
"Error: [$injector:unpr] Unknown provider: applicationStateServiceProvider <- applicationStateService
http://errors.angularjs.org/1.2.23/$injector/unpr?p0=applicationStateServiceProvider%20%3C-%20applicationStateService
minErr/<@http://localhost:8080/owner/bower_components/angular/angular.js:78:12
createInjector/providerCache.$injector<@http://localhost:8080/owner/bower_components/angular/angular.js:3802:19
getService@http://localhost:8080/owner/bower_components/angular/angular.js:3930:39
createInjector/instanceCache.$injector<@http://localhost:8080/owner/bower_components/angular/angular.js:3807:28
getService@http://localhost:8080/owner/bower_components/angular/angular.js:3930:39
invoke@http://localhost:8080/owner/bower_components/angular/angular.js:3957:1
instantiate@http://localhost:8080/owner/bower_components/angular/angular.js:3977:23
$ControllerProvider/this.$get</<@http://localhost:8080/owner/bower_components/angular/angular.js:7274:18
nodeLinkFn/<@http://localhost:8080/owner/bower_components/angular/angular.js:6663:34
forEach@http://localhost:8080/owner/bower_components/angular/angular.js:332:11
nodeLinkFn@http://localhost:8080/owner/bower_components/angular/angular.js:6650:11
compositeLinkFn@http://localhost:8080/owner/bower_components/angular/angular.js:6098:13
compositeLinkFn@http://localhost:8080/owner/bower_components/angular/angular.js:6101:13
publicLinkFn@http://localhost:8080/owner/bower_components/angular/angular.js:5994:30
bootstrap/doBootstrap/</<@http://localhost:8080/owner/bower_components/angular/angular.js:1449:11
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://localhost:8080/owner/bower_components/angular/angular.js:12673:16
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:8080/owner/bower_components/angular/angular.js:12771:18
bootstrap/doBootstrap/<@http://localhost:8080/owner/bower_components/angular/angular.js:1447:9
invoke@http://localhost:8080/owner/bower_components/angular/angular.js:3966:14
bootstrap/doBootstrap@http://localhost:8080/owner/bower_components/angular/angular.js:1445:1
bootstrap@http://localhost:8080/owner/bower_components/angular/angular.js:1459:1
onGoogleReady@http://localhost:8080/owner/#/create-need/1/0:224:17
@http://maps.gstatic.com/maps-api-v3/api/js/19/2/main.js line 13 > eval:1:1
S/<@http://maps.gstatic.com/maps-api-v3/api/js/19/2/main.js:13:251
Yf/e<@http://maps.gstatic.com/maps-api-v3/api/js/19/2/main.js:26:639
If@http://maps.gstatic.com/maps-api-v3/api/js/19/2/main.js:25:568
Yf@http://maps.gstatic.com/maps-api-v3/api/js/19/2/main.js:26:620
@http://maps.gstatic.com/maps-api-v3/api/js/19/2/main.js:54:475
google.maps.Load@http://maps.google.com/maps/api/js?sensor=false&callback=onGoogleReady:21:5
@http://maps.gstatic.com/maps-api-v3/api/js/19/2/main.js:54:1
@http://maps.gstatic.com/maps-api-v3/api/js/19/2/main.js:1:1
"

**Comment by sbyim** [comment]
changed it to ng-app declaration, because we don't use google map anymore. closing.
