### ISSUE TITLE
Go To Full Description - Public Need Detail breaks in FF (and Chrome)

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#205]
Going to own Postbox, clicking on an owned need, then clicking "Go to full description" sometimes yields and empty page. Alternatively the script breaks (angular bindings aren't resolved).

The problem seems to be specific to Firefox (33.0)

**Comment by yanapanchenko** [comment]
fixed by d3b2f4f when implementing detail view as public link

**Comment by m0ru** [comment]
sleek :3
