### ISSUE TITLE
Styling seems to be broken in some places

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#2056]
- the contentside does not stretch to the height of the whole screen anymore (on mobile, when a chatview is open with only one or two messages for example)
- the styling of the search and post buttons (on mobile and only when no other content is present) is off:
![screenshot_20180704-070337](https://user-images.githubusercontent.com/8503486/42257787-94413718-7f58-11e8-937c-72cbb549a880.png)

**Comment by fkleedorfer** [comment]
Turned out to be a caching issue
