### ISSUE TITLE
Form Input textarea covers details

### ISSUE THREAD

**Issue by AndresJCremades** [researchstudio-sat/webofneeds#2072]
In the forms, when typing something in the textarea, this covers the next detail, and it's not possible to watch it.

![image](https://user-images.githubusercontent.com/3080768/42364787-b7644a00-80fc-11e8-9ec4-49e330804870.png)

**Comment by quasarchimaere** [comment]
afaik this issue only appears because of the grammarly plugin you are using, kevin had similar issues with it, i would close it if it doesnt appear without the third party plugin that messes up our styling

**Comment by peacememories** [comment]
We should probably still try to fix this issue, since most people use one extension or another with their browsers. While we obviously cannot render correctly in *every* case where an addon changes the dom, simple modifications like the one in grammarly should not break our interface.

**Comment by quasarchimaere** [comment]
i just installed the grammarly plugin and the bug is not present anylonger -> closing this issue and removing the plugin from my system again
