### ISSUE TITLE
Tags input is not empty

### ISSUE THREAD

**Issue by AndresJCremades** [researchstudio-sat/webofneeds#2073]
In the forms, tags input has already something typed, so it's not possible to see the placeholder with the example.

e.g:in this case was the word "question" already typed
![image](https://user-images.githubusercontent.com/3080768/42364902-1d75c814-80fd-11e8-9d91-7a91da76b6ae.png)

**Comment by fkleedorfer** [comment]
That's actually a feature - tags are pre-filled for certain kinds of needs. I'd say we leave it likt this for the time being
