### ISSUE TITLE
Post creation takes too much time

### ISSUE THREAD

**Issue by AndresJCremades** [researchstudio-sat/webofneeds#2074]
Yesterday when I tried to create a post for the CBI version, the app got stuck in "creating":

![image](https://user-images.githubusercontent.com/3080768/42364988-6bdda0e4-80fd-11e8-9dcb-5fb772fa2b8c.png)

**Comment by fkleedorfer** [comment]
It may have failed for some reason. Do you have the post now, or did you have it after a reload?

**Comment by quasarchimaere** [comment]
this issue is purely subjective and without any lead of a bug, its simply a statement and therefore we can close this issue
