### ISSUE TITLE
Title label in the forms

### ISSUE THREAD

**Issue by AndresJCremades** [researchstudio-sat/webofneeds#2075]
It would be very recommendable to create a "Title" label in the forms. When there's no an extern label along the input field, once the user starts typing, he/she may forget what the purpose for the input and at that point there's no placeholder anymore was. Best practices recommend always using a fixed label.

![post 5](https://user-images.githubusercontent.com/3080768/42365230-2c9e4284-80fe-11e8-937f-a430214f6f67.png)

**Comment by quasarchimaere** [comment]
i think that we should make the title usecase dependant anyway (it already has a viewer component, we would just have to extract it into a picker still, and then start to use it only within use-cases that it makes sense in, if we do that than we solved this issue as well

**Comment by peacememories** [comment]
The title has recently become an independent detail. Is this issue still relevant now?
