### ISSUE TITLE
Inconsistent handling of , in input fields

### ISSUE THREAD

**Issue by sigpie** [researchstudio-sat/webofneeds#2078]
In some cases (e.g. Tags), input is split only on whitespace. A input of `"foo, bar"` results in `["foo,", "bar"]`. In other cases (e.g. Skills for a Person), input is split only on `,`. `"foo, bar"` results in `["foo", "bar"]`.

`,` should be consistently handled, probably always as a separator.

**Comment by quasarchimaere** [comment]
i think that the person picker does not have the skills anymore, so i think this is in unison now, and can be closed
