### ISSUE TITLE
don't connect with own postings

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#208]
Nothing stops you from connecting two of your own postings. While that may make sense for some use cases in the future, currently this doesn't make sense.

However, only you (or your owner application) can know if two postings belong to you or not. Therefore, we can't keep matching services from sending hints. The only thing we can do is suppress the respective functionality in the owner application.

This should happen in the following places:
- Private link page: don't show matches to my own postings 
- Post detail page: don't show 'connect with this posting' option for my own postings.

**Comment by yanapanchenko** [comment]
'Post detail page: don't show 'connect with this posting' option for my own postings' is fixed in code now, but actually it is not specified in the storyboard yet.

**Comment by yanapanchenko** [comment]
'Private link page: don't show matches to my own postings' is also now fixed, but also it's not in the storyboard.

**Comment by fkleedorfer** [comment]
In such cases, the storyboard should be updated

**Comment by m0ru** [comment]
assign any story-board updates to me

**Comment by m0ru** [comment]
Issue related to old, deprecated prototype.
