### ISSUE TITLE
set RDF in the usecase definition

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#2084]
We need an option to define rdf:type triples for is and seeks

**Comment by peacememories** [comment]
I think adding this as a user-visible detail is overkill and might be confusing. Rather, usecases should add the proper types to the created need. If users really need this much control over the rdf directly ttl seems like a better interface than our unopinionated details picker.

**Comment by fkleedorfer** [comment]
Yes - it should be possible to set RDF in the usecase definition
