### ISSUE TITLE
Wrong need data when clicking other need detail view

### ISSUE THREAD

**Issue by yanapanchenko** [researchstudio-sat/webofneeds#209]
From private-link page: clicking on both my post detail view and on the matched need detail view, always displays my own post data:

![error-post-detail-wrong need](https://cloud.githubusercontent.com/assets/7224202/5411504/5a4c4f3c-8201-11e4-9a53-d21ed19de886.PNG)

**Comment by m0ru** [comment]
Will be fixed when public/private urls have been implemented.
