### ISSUE TITLE
Use-case icons in left colum too large

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#2120]
![image](https://user-images.githubusercontent.com/1730492/42517959-3e7ff3f6-8461-11e8-9244-c8568e87d77e.png)
^ these should have the same size and margins as the post/search icons or the title-icon above (pic below for reference)

![image](https://user-images.githubusercontent.com/1730492/42518016-5f8b4e6a-8461-11e8-9dbc-c989d13b1c5f.png)

**Comment by quasarchimaere** [comment]
we can tackle this issue once the original icons dont include padding within the svg
