### ISSUE TITLE
Change `WonMessage` into pure data-structure (+a module of util functions)

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#2121]
The class-structure as it is atm makes it impossible to e.g. make the messages immutable, which makes impossible to store them in our state or dispatch them in actions with immutable payloads. Also, it makes it easier to reason about the functions as they become pure, as long as input-parameters are never modified.

**Comment by m0ru** [comment]
This probably will be necessary for #1130 (anyway)

**Comment by m0ru** [comment]
When this is fixed, the hack/workaround in `wellFormedPayload` around `won-message-utils.js:30` can be removed and the related message handling in the need-reducer adapted.

**Comment by quasarchimaere** [comment]
moved to our internal kanbanboard
