### ISSUE TITLE
Npm package-lock.json is inconsistent across different environments

### ISSUE THREAD

**Issue by peacememories** [researchstudio-sat/webofneeds#2123]
Over the past few months we have run into situations where the [`package-lock.json`](https://github.com/researchstudio-sat/webofneeds/blob/master/webofneeds/won-owner-webapp/src/main/webapp/package-lock.json) would change in unexpected ways (sometimes even when the [`package.json`](https://github.com/researchstudio-sat/webofneeds/blob/master/webofneeds/won-owner-webapp/src/main/webapp/package.json) was not changed)

This seems to be because of a problem with `optionalDependencies` in npm (see https://github.com/npm/npm/issues/17722 ).
Ways we could deal with this:

* Migrate to [yarn](https://yarnpkg.com/lang/en/)

    Yarn does not seem to have the same problem and has been using lock files longer than npm. This could be difficult because npm is currently deep in our maven build process.

* Everyone uses `--no-save` except for the people who install packages.

    This doesn't fix the fact that if people on different machines install packages the optional dependencies in the lock file will change (for example, if someone on Windows changes the lock file `fsevents` will disappear because it is not supported on the OS).

* Ignore it (we don't depend on consistent locks *that* much)

    Not my favorite option, but possible^^'

**Comment by fkleedorfer** [comment]
Upon discussion with @peacememories : No really good options here. We'll wait till NPM fixes this.

**Comment by gaofeng0630** [comment]
现在有没有什么好的解决办法，只能使用npm install --no-save吗？这个办法到底可不可行啊！

**Comment by gaofeng0630** [comment]
npm install 之后package-lock.json 文件改变会直接影响项目的功能吗？
