### ISSUE TITLE
generate samples for real estate offers

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#2150]
Using the [RDF Import Bot] (https://github.com/researchstudio-sat/won-rdfimport-bot), we can import TRIG files, each containing one need. For testing the RE case, we need to generate TriG files representing apartments and use the bot to import them.

depends on #1817

**Comment by quasarchimaere** [comment]
i think before we tackle this, we should try and create the specific use cases with our usecase and detail definitions, in order to see if manually created posts have the necessary values. after this we can use the created post as a stub to automatically generate the real estate offers
