### ISSUE TITLE
Define 'Inner' Padding for SVG Icons to have a unison look and feel and visual-weight

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#2151]
The following svg icons have a padding within the icon itself, this makes it hard for us to change the padding within the style itself, these are the icons that need to change:

- ico36_search
- ico36_plus
- ico36_rdf_logo

There could be other icons too, but these are the ones that i found so far. @m0ru if you find or know about any other icons with internal padding please add them in the description or as a comment, so we can change and test them all

related to #2120
related to #1634

**Comment by fkleedorfer** [comment]
This needs to be discussed - @m0ru

**Comment by quasarchimaere** [comment]
discussed with @m0ru, we will not remove the padding in general but try to figure out a unified padding/styling based on the visual weight of each specific icon

**Comment by quasarchimaere** [comment]
no longer relevant due to #2778 and #2777
