### ISSUE TITLE
Make SPARQL matcher SHACL-aware

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#2153]
Here is a good starting point for thinking about this: https://github.com/researchstudio-sat/webofneeds/blob/06b180a34b3100d81eb4d772252106770f935b8a/documentation/designissues/draft-stating-information-requirements.md

**Comment by peacememories** [comment]
As we discussed, I think we should create a separate SHACL matcher rather than incorporate the feature into the SPARQL matcher. I am currently looking into converting shacl queries into sparql so we can run them on Blazegraph.
