### ISSUE TITLE
RDF in post-info overflows its content area 

### ISSUE THREAD

**Issue by sigpie** [researchstudio-sat/webofneeds#2154]
The RDF representation of a need isn't displayed in a scrollable container. As a result, a long RDF representation overflows the post-info content area. 

![post-info-rdf](https://user-images.githubusercontent.com/32930574/42814502-bbbf8e7c-89c4-11e8-84a5-4d4b67cf5c89.PNG)

**Comment by quasarchimaere** [comment]
i also saw this issue and fixed it within pr #2152
