### ISSUE TITLE
label on post-button

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#2156]
![image](https://user-images.githubusercontent.com/1730492/42816652-d5d8a3aa-89cb-11e8-9a25-d1305e087b0a.png)

^ dunno if this button label really gets across what the post-create view is for

**Comment by sigpie** [comment]
The > < part might also be not ideal.

**Comment by quasarchimaere** [comment]
@sigpie i think that for the use-case picker itself we could use the X instead of the < icon to go back
