### ISSUE TITLE
Design anonymous usage/'private link' behavior

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#216]
Write up the specification of how the whole functionality should work. 
Issues are:
- all postings have a private link
- An anonymous posting can be connected with an user account of the owner app
- If a posting is connected to an account, and its privat link is used - no other postings of the account be accessed!
- If a posting is connected to an account, and its private link is used, all settings of the posting be changed, and for each change (close, supply email address) the owner is notified.

**Comment by yanapanchenko** [comment]
Storyboard private link related summary as of v50:
1. Covered well in storyboard: Post Detail View - not loggid-in user does 'contact' to connect to other need - request-need with private link created
2. Covered bad in storyboard: How a not signed-in user can get his need's private link after creating a need (the private link is displayed in Settings section, but it will not be straightforward for the user to look for it there; would be better: when user clicks 'publish' offer him to sign-in, or ask for an e-mail to send him the link, or notify about the private link, similar to when he does 'contact'...)
3. Not clear: Do all needs have private link or only not logged-in user's needs do? For example, in Settings, the private link is mentioned for all needs, but in other places the private link is only mentioned in relation to not signed-in users.
4. Not clear: Should private link page have a private link address?
e.g.: http://localhost:8080/owner/#/private-link?id=hhZ3988893lk7mhw-hrhrhU7208d747-kdjfkjdk937zBnncksuh8e4-Polkkkse857mpivwd20K6jKbzZ1g

**Comment by fkleedorfer** [comment]
1.: agree
2.: agree - I added a description to the task in agilefant
3.: no - only needs that are posted anonymously have a 'private link'
4.: I'm not aginst it

**Comment by fkleedorfer** [comment]
We should remove the words 'private link' from the application entirely, except when we're actually referring to a URL.
So, the 'private link page' should be renamed.

I agree that the 'public' view of a posting should have a different name than the 'private' view. How about just naming them public view and private view?

**Comment by m0ru** [comment]
2: It's in the settings area (see figure 57 in storboard-v51) which will be almost at the top when there are no matches/messages yet. Also it should be in the browser's URL-bar. 
3. the way i had understood it an account atm would only be a list of private links (that could be exported / synched with any other app that's used, thus stimulating competition among app-devs by preventing lock-ins for users)
4. that would allow simply copy-pasting it from the URL-bar and most importantly bookmarking them. I would suggest sthg along the line of the following to suggest possible privacy and administration implications to people unaccustomed to the system.

* http://webofneeds.org/#/dont-share-1faf21234ac123
* http://webofneeds.org/#/admin-1faf21234ac123
* http://webofneeds.org/#/private-1faf21234ac123
* http://webofneeds.org/#/ownership-1faf21234ac123
* http://webofneeds.org/#/bookmark-me-1faf21234ac123
* ...

(none of the above make me too happy. these need more thought)

**Comment by m0ru** [comment]
Unrelated note: When clicking one of the links above the current webofneeds.org cmv-framework serves the default page but doesn't redirect (i.e. show a 404 / redirect notice, change the browsers URL) -> this might confuse people if specific sub-entries are linked (i.e. the person who made the link in the past and the person using it see different versions but don't know that)

**Comment by fkleedorfer** [comment]
ad 3. It has always been unclear what a 'private link' should actually be, your comment stresses that fact. As we'll be working on authentication and permissions later, we cannot address the use case you mention, yet. 
ad 4. I'm in favor of using the private/public nomenclature. @m0ru's suggestion for `http://webofneeds.org/#/private-1faf21234ac123` is best, I think. The corresponding public view URL would be something like `http://webofneeds.org/#/public-2345sdf09asf`

**Comment by m0ru** [comment]
mhm, good point.

the second link looks a bit unusual / confusing at first (containing two protocol prefixes and domains), but i like the implications. if other apps worked that way as well i could simple copy-paste the second uri over to view it in a different interface. though it's more of an advanced feature for people who figure out the url-scheme.
