### ISSUE TITLE
gender picker

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#2160]
![image](https://user-images.githubusercontent.com/1730492/42824721-b3485eba-89e0-11e8-82c9-f2c6d4d7a3e8.png)

^ no matter how many options you have in this thing, there'll always be one that isn't in there. we might consider making this a textfield. or adding a free-text-option.

**Comment by quasarchimaere** [comment]
i agree, the thing is that the genderpicker shouldnt even be a thing, it was just supposed to be a non abstract detail implementation of a dropdown picker... granted it was a really bad example and we should remove it again
