### ISSUE TITLE
Add transport demand/offer use case

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#2168]
As simple as possible:
transport demand
* from
* to 
* weight
* size
* content
offer
* area (location where it should be matched)
* title
* description

depends on #1817 (which is currently in progress and is altered the exact same file as we would need to edit here too, so for the sake of reducing merge conflicts or rebase issues i think we can hold off on this until the #1817 is ready to be merged and then branch away from it

**Comment by quasarchimaere** [comment]
Just to make the usecase creation easier i added the details that we should extend from for each item

transport demand
* from/to -> TravelAction
* weight -> Number
* size -> Number
* content -> Description
offer
* area (location where it should be matched) -> Not a picker yet!
* title -> Title
* description -> Description

**Comment by quasarchimaere** [comment]
i think issue #2186 could be handled right within this ticket too, maybe have a look @sigpie
