### ISSUE TITLE
Rename chosenMessage

### ISSUE THREAD

**Issue by yanapanchenko** [researchstudio-sat/webofneeds#218]
Flo pointed out that it would be good to rename chosenMessage that actually represents connection (used in private link and conversation page) to avoid confusion with actual messages such as conversation text message of a connection.

Currently, chosenMessage, holds the following data:
connection: Object
event: Object (i.e. last won message of this connection)
lastMessages: Array[3](i.e. last text messages of this connection if any)
remoteNeed: Object
typeText: "Conversation" (can also be Matches, Incoming Request, Outgoing Request, Incoming Closed, Outgoing Closed)

What would be a good name for such object? choosenConnection? But probably it also can be confusing because it in itself holds connection object.

choosenCommunication?
chosenConterneed?

**Comment by m0ru** [comment]
selectedConnection / displayedConnection come to my mind

(chosenCounterpart would suggest the counterpart's public view imho)

**Comment by fkleedorfer** [comment]
currentConversation?

**Comment by m0ru** [comment]
i like "conversation". selectedConversation maybe? ("current" is a bit more ambigious imho)

**Comment by quasarchimaere** [comment]
concerns the old ui -> close
