### ISSUE TITLE
Write range pickers for sparql queries

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#2181]
For querying numeric ranges, we need these input widgets:
- [ ] range picker with optional min and max settings
- [x] range picker with preset ranges in a dropdown

**Comment by quasarchimaere** [comment]
range picker for dropdown is not needed anymore, can be a simple dropdown picker

**Comment by quasarchimaere** [comment]
range picker with optional min and max settings will be implemented as won-minmax-picker that uses two number-pickers
