### ISSUE TITLE
Honor  Geolocation in Sparql-based matchers

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#2191]
This would have to be done using a sparql extension: https://wiki.blazegraph.com/wiki/index.php/GeoSpatial

**Comment by quasarchimaere** [comment]
i saw this addon already and we could profit immensly from it, we could implement whatsaround needs that actually dont have anything but needs from a specific area (afaik geospatial even works with polygon queries).

**Comment by peacememories** [comment]
The documentation states they have only implemented circle and rectangle searches so far.

**Comment by quasarchimaere** [comment]
maybe i was refering to this one: http://www.opengeospatial.org/standards/geosparql but i could be wrong i just browsed through this recently and probably didnt understand it

**Comment by peacememories** [comment]
I don't know if we should include this matching behaviour in the sparql-matcher directly, since it has no concept of how a location should be matched. Using it in the custom queries attached to needs and enabling the extension seems desirable though.

**Comment by fkleedorfer** [comment]
An additional problem is that this approach is specific to blazegraph. If we use it in embedded queries, those will not work for other matchers. We need some kind of translation or generation happening in the matcher in both cases (if it's the generic sparql matcher or another one).
