### ISSUE TITLE
Consistent avatar for "system"

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#2192]
![image](https://user-images.githubusercontent.com/1730492/43005913-8aa75c30-8c34-11e8-9881-8263634fd4a1.png)

![image](https://user-images.githubusercontent.com/1730492/43005924-94334a02-8c34-11e8-8320-e4ac9f265088.png)

We should give "system" a single, pre-defined avatar (e.g. an information-"i", the won-logo, or somesuch)

**Comment by quasarchimaere** [comment]
please dont do this, the avatar is consistent, tue avatar shows the identicon for the node/matcheruri, that way we can identify which matcher sent the hint
