### ISSUE TITLE
search input field in the search results page?

### ISSUE THREAD

**Issue by sbyim** [researchstudio-sat/webofneeds#220]
the current design only allows users to search for others post in the "others" page.

the user doesn't have the possibility to perform a new search without going back to "others" page.

Thus, considering introducing the search input field at the top of the search results page with the currenct search keyword could be a good idea, 
![won screenshot](https://cloud.githubusercontent.com/assets/5468024/5801409/f95d5416-9fea-11e4-865f-0fc5d1bb6498.PNG)
![googlesearch](https://cloud.githubusercontent.com/assets/5468024/5801420/1b3d1bd4-9feb-11e4-8df3-57682a9c1c83.PNG)

**Comment by m0ru** [comment]
+1

That got lost in the redesign somehow.

**Comment by fkleedorfer** [comment]
+1

**Comment by quasarchimaere** [comment]
no longer relevant -> ui changed
