### ISSUE TITLE
maximum number of search results displayed

### ISSUE THREAD

**Issue by sbyim** [researchstudio-sat/webofneeds#221]
currently, maximum number of search result to be displayed is not specified.
The storyboard doesn't mention pagination.
The view shall be specified more in detail.
![searchresults](https://cloud.githubusercontent.com/assets/5468024/5819037/de492b48-a0ba-11e4-9e4d-8a3a301981b0.PNG)

**Comment by m0ru** [comment]
As we're using js already anyway, dynamic loading (while scrolling down) is the nicer way to go, as it doesn't interrupt the interaction to load the next page. The best would be to start with 1.5 screen-heights worth of results.

**Comment by sbyim** [comment]
hmmm i agree with the dynamic loading on mobile devices, but when we view the page on a pc, i am not sure how it should look, because the post details shall also be displayed on the right of the screen?
should the post detail view slide down together while scrolling?

**Comment by fkleedorfer** [comment]
Isn't the simplest solution to dynamically create a new div next to the search result when a user clicks on it?

**Comment by sbyim** [comment]
@fkleedorfer hmmm yeah but that's not what we were talking about..
we were talking about loading the thumbnails on the left side.
how many thumbnails are to be displayed 
and whether to do it with dynamic loading as the user scrolls down or via pagination

**Comment by fkleedorfer** [comment]
I meant this to be used together with dynamic loading while scrolling.

**Comment by quasarchimaere** [comment]
old ui -> search results not applicable -> close
