### ISSUE TITLE
old svg icons differ from new ones

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#2211]
just saw that our old svg circle icons have a white background while ournew ones are ...translucent?!
![screenshot_20180724-201355](https://user-images.githubusercontent.com/8503486/43157824-5e9055c8-8f7e-11e8-8eb1-4dfe292c8372.png)

**Comment by quasarchimaere** [comment]
also tbh i like the ones with the white background even better

**Comment by fkleedorfer** [comment]
Good catch, of course all should have the same characteristics. I think it makes more sense for them to have transparent (=no) background. Alternatively, we could use a variable so we can style the 'inner' background, but that is more work
