### ISSUE TITLE
Related tags of a search input

### ISSUE THREAD

**Issue by sbyim** [researchstudio-sat/webofneeds#223]
related tags of a search input shall be displayed on the search result page.
how should we do this? 
we haven't implemented this functionality on the server side.

**Comment by m0ru** [comment]
we could extract the most frequent tags in the search results. this might conflict with pagination/dynamic reload though (as we don't get all the results immediately). On the other hand the tags of the best matches are probably more relevant anyway.

**Comment by sbyim** [comment]
yes.. we also need to specify how many tags we want to show..

**Comment by sbyim** [comment]
as to pagination.. the storyboard doesn't mention about it either.. See #221

**Comment by fkleedorfer** [comment]
Probably something that can be done with solr faceted search, but I'm unsure how, and if our modifications of siren allow it.

Best not to implement it in the GUI until we know how to solve it on the server. We have too many 'dangling features' already.

**Comment by quasarchimaere** [comment]
no longer relevant -> ui changed
