### ISSUE TITLE
Webofneeds.org Redirect

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#224]
http://webofneeds.org/#/non-existant-ressource-which-should-404

When clicking the link above the current webofneeds.org cmv-framework serves the default page but doesn't redirect (i.e. show a 404 / redirect notice, change the browsers URL) -> this might confuse people if specific sub-entries are linked (i.e. the person who made the link in the past and the person using it see different versions but don't know that)

**Comment by fkleedorfer** [comment]
Cleaning up old issues.
