### ISSUE TITLE
implement add attachment for messages

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#2245]
we want 3 options:
[ ] add a workflow
[ ] add an image
[ ] add a file

each option uses different RDF triples to link to the attachment.

**Comment by quasarchimaere** [comment]
includes #1262

**Comment by fkleedorfer** [comment]
You may  be able to figure out the proper RDF by looking at how it is extracted: 
won.protocol.message.WonMessage.java:getAttachments() in won-core

note: that code hasn't been used in some time, may have skipped a refactoring or two.
