### ISSUE TITLE
Detail/Usecase Parsing Issues

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#2253]
- generateHumanReadable of Rooms rangePicker with only one value shows undefined
- sending a message that have a xsdFloat type in the parseToRDF need to be resilient in the parseFromRDF (see tags parsing)

**Comment by m0ru** [comment]
There are others. Check all details.

**Comment by m0ru** [comment]
* [x] generateHumanReadable => resolved by #2271
* [ ] xsdFloat/parseToRDF
