### ISSUE TITLE
Create and Adapt Detail Icons

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#2255]
Create new Detail Icons and update the exisiting ones in a way that the circle around it will be removed

**Comment by sigpie** [comment]
Currently used details/progress in updating them

[x] description
[x] title
[ ] date
[ ] time
[ ] location
[ ] person
[ ] travelaction
[ ] tags
[ ] turtle
[ ] weight
[ ] length
[ ] width
[ ] height
[ ] floor size
[ ] number of rooms
[ ] features
[ ] rent/month
[ ] interests
[ ] skills
[ ] allergies
