### ISSUE TITLE
Right drawer menu - Mobile version

### ISSUE THREAD

**Issue by AndresJCremades** [researchstudio-sat/webofneeds#2275]
I think users will use Matchat on their phones mainly. To keep the screen clean and minimalist, I think it would be a good idea to develop a right drawer menu and place there options like "Sign Up", "Sign In" and possible future options. 

A hamburger icon is a good option due to its universality, and it would help to avoid users to think they have to sign up to use Matchat.

![option 5](https://user-images.githubusercontent.com/3080768/44200711-8b806e80-a147-11e8-8b3d-68f3e4b50fa2.png)

**Comment by quasarchimaere** [comment]
moved to internal kanban board
