### ISSUE TITLE
Add PersonaImage/Icon to Persona (old title: Add user's picture)

### ISSUE THREAD

**Issue by AndresJCremades** [researchstudio-sat/webofneeds#2279]
We should give the users the possibility of identifying themselves visually if they don't want to stay anonymous. That's a way of building trust. And in the case of social events (e.g., runners meeting) attendants might want to identify the author of the post at the time of the meeting.

My suggestion is enable the possibility of upload an image or take one in that moment when it comes creating the post.

![image](https://user-images.githubusercontent.com/3080768/44210317-69e2af80-a166-11e8-9d28-114a85b959b7.png)

requires #2520
requires #2374

**Comment by quasarchimaere** [comment]
maybe this is a part of identies #2374
