### ISSUE TITLE
Test Welcome Message

### ISSUE THREAD

**Issue by AndresJCremades** [researchstudio-sat/webofneeds#2280]
It'd be desirable to test the Welcome Message and see what idea users get. Does the message give a right idea about what Matchat is or doesn't help at all? Then modify it if necessary.

![image](https://user-images.githubusercontent.com/3080768/44211230-cb0b8280-a168-11e8-99cf-c3b5e01775a5.png)

**Comment by quasarchimaere** [comment]
moved to our internal kanbanboard
