### ISSUE TITLE
(Automatic) RDF-typechecking for debugging

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#2303]
Atm the RDF we generate doesn't adhere to the ontologies. E.g. when sending things, the `s:values` in `s:QuantititativeValue`s should be `s:Number`s, `s:Float`s or `s:Integer`s, not `xsd:float`s on commit <https://github.com/researchstudio-sat/webofneeds/tree/ad2bdb0d023b3dd5e3c777f124cf4621a7d32afd> (I'll fix that one bug in `fix__xsd-float-at-parse-to-rdf__#2253`, but there's bound to be other bugs like that, that will only become apparent when we'll try to interact with other systems and the later we fix these issues, the more bugs will have piled on and the higher the effort required to fix those.

It would be nice to have a tool that can check the adherence to and consistency with the ontologies we use, either automatically whenever a need is published in the local debug-setup, or even just manually by copy-pasting e.g. the need-trig into a tool that verifies it.

**Comment by quasarchimaere** [comment]
moved to our internal kanbanboard
