### ISSUE TITLE
Add Usecases 

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#2322]
Which use cases should we add to the owner webapp?
Take a look at the demonstrator at https://matchat.org/
Then add your ideas here!

... or, if you are *really motivated*, make a pull request for https://github.com/researchstudio-sat/webofneeds/blob/master/webofneeds/won-owner-webapp/src/main/webapp/config/usecase-definitions.js

**Comment by sigpie** [comment]
* classified ads equivalent (e.g. I want to sell this piece of furniture) - needs title, description, location, price, pictures

**Comment by jensitus** [comment]
Use Case: Bring Web Of Needs to the people!

**Comment by fkleedorfer** [comment]
@sigpie we'd probably need subcategories with different templates - you need different fields for a used cupboard than for a used bike.. but that does not make it a different use case, right?

**Comment by quasarchimaere** [comment]
@fkleedorfer i think that subcategories are currently not necessary if we want to keep it simple, i think that offering two options in the "Classifieds"-UseCaseGroup namely "Offer Goods" and "Offer Services" would suffice... maybe we need to add their search counterparts, but i feel like the simple search would do well enough for now

**Comment by sigpie** [comment]
Commissional work - finding/offering jobs is covered, but not commission based work, e.g. repairing or producing something

**Comment by peacememories** [comment]
This issue has been inactive for a month. Is this still to be discussed?

**Comment by quasarchimaere** [comment]
not sure if there is discussion necessary but we could start/implement the classifieds usecases imho

**Comment by quasarchimaere** [comment]
closing this issue in favor of #2512 and #2513
