### ISSUE TITLE
Special Characters in url executing controller twice

### ISSUE THREAD

**Issue by yanapanchenko** [researchstudio-sat/webofneeds#236]
If I enter an url with a query params containing url encoded special characters, e.g.
#/private-link?id=1%40TODO
the corresponding controller is executed twice.

While if I don't have such characters, or they are not encoded, e.g.
#/private-link?id=1@TODO 
the corresponding controller is executed once as expected.

This can be either bug or feature in angularjs...

**Comment by yanapanchenko** [comment]
similar problem:
http://stackoverflow.com/questions/18538620/special-characters-in-routeparams-executing-controller-twice-in-angularjs

**Comment by yanapanchenko** [comment]
What happens in case of  #/private-link?id=1%40TODO is that it starts to load this page (#/private-link?id=1%40TODO) and then it is changing the route to #/private-link?id=1@TODO and therefore loads the page again.

**Comment by sbyim** [comment]
yep.. 

See, http://www.w3schools.com/tags/ref_urlencode.asp
>URL encoding replaces unsafe ASCII characters with a "%" followed by two hexadecimal digits.

and [ASCII table](http://www.asciitable.com/)

**Comment by sbyim** [comment]
@yanapanchenko i think this is fixed now?

**Comment by yanapanchenko** [comment]
Yes, just because we don't use any of those special characters now in our urls. But this issue can happen again if we do.
