### ISSUE TITLE
Different text sizes for need details

### ISSUE THREAD

**Issue by sigpie** [researchstudio-sat/webofneeds#2364]
![d5799bd0-df34-47bd-a99b-ff3e529f49e1](https://user-images.githubusercontent.com/32930574/45414909-b1346100-b67c-11e8-9a2b-26b723f092ad.png)

**Comment by quasarchimaere** [comment]
seems to happen in safari, at least i can't reproduce the problem on chrome

**Comment by sigpie** [comment]
This might be related to automatic text size adjustment as documented by [Apple's support pages](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/AdjustingtheTextSize/AdjustingtheTextSize.html#//apple_ref/doc/uid/TP40006510-SW16) and in the [MDN web docs](https://developer.mozilla.org/en-US/docs/Web/CSS/text-size-adjust). If this is the case, this bug should also appear on other mobile browsers, not just Safari on iOS.

**Comment by peacememories** [comment]
This doesn't happen on my iPhone, probably since it has a larger screen size, and therefore the element bounds are different

**Comment by quasarchimaere** [comment]
@sigpie please try this on the new masterbranch as i can't reproduce this on android/chrome at all

**Comment by sigpie** [comment]
Seems to be fixed on the current master.
