### ISSUE TITLE
browsers crash on live

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#2367]
Probably caused by a lot of needs closed in the db only, bit connections still open, the application crashes the browser (ff and chrome alike). As we cannot guarantee data integrity we have to defend against such situations.

**Comment by quasarchimaere** [comment]
does it crash with your user? if so, i think my conversation with you that included proposals and images caused it, afaik there was some problem during the list sorting the connection list (it happened to me too)
