### ISSUE TITLE
currentNeedURI, currentConnectionURI in applicationStateService

### ISSUE THREAD

**Issue by sbyim** [researchstudio-sat/webofneeds#237]
we are currently storing currentNeedURI and currentConnectionURI in applicationStateService and using them in differnt controllers.
this is not really a good design. we should think about refactoring it.

**Comment by sbyim** [comment]
issues #234, #235 are related.

**Comment by sbyim** [comment]
maybe https://github.com/angular-ui/ui-router could help??

**Comment by quasarchimaere** [comment]
no longer relevant / "implemented" ->ngredux
