### ISSUE TITLE
request for conversation generated from search results

### ISSUE THREAD

**Issue by sbyim** [researchstudio-sat/webofneeds#239]
if some user searches for the same need and request conversations from the search results,

the user who owns that need gets multiple conversation requests with the same title, which can be irritating for the user if he wants to distinguish the different requests.
![request for conversation](https://cloud.githubusercontent.com/assets/5468024/6146824/1f9224aa-b1f1-11e4-9214-d10ea87912b8.PNG)

Maybe we should think about letting the owner user 'tag' the different requests.

**Comment by quasarchimaere** [comment]
old ui -> close
