### ISSUE TITLE
Use unique URI for each facet instance

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#2393]
Now:
* [x] adapt WON vocabulary and ontology
* [x] change connection model: add facetURI and keep facet type
* [x] change facet model: add facetURI and defaultFacet flag
* [x] change NeedModelWrapper: create/obtain facet differently
* [x] change Need creation: extract facet info and store in facet table
* [ ] change connection creation code:
  - [x] obtain facet type from connect message/target need
  - [x] adapt receiving hints: 
    + [x] use default facet if no facet given, as denoted by won:defaultFacet <facet>
    + [x] use OwnerFacet if no default specified
    + [ ] check compatibility of remote facet (maybe)
* [x] adapt connect/open
    - [x] same checks as for hints apply
    - [ ] ~~remove facet/remotefacet message properties and use facet URIs~~
 * [ ] adapt GUI
    - [x] create
    - [x] connect/open/hint
* [ ] adapt matcher
* [x] change need templates for bots
  - [x] debug bot
  - [x] mailbot
  - [x] taxi bot
  - [x] job bot

**Comment by quasarchimaere** [comment]
dont forget to remind @schokobaer to update the need template for the paymentbot as well
