### ISSUE TITLE
HyperGraphQL / GraphQL for JSON-LD

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#2408]
* http://www.hypergraphql.org/ federated graphql
* https://www.topquadrant.com/technology/graphql/

=> substitute for SPARQL + JSON-LD framing

Do we want to use this as part of the rewrite in November?

Related to #2409

**Comment by quasarchimaere** [comment]
@fkleedorfer close/later/soon/ready?

**Comment by quasarchimaere** [comment]
moved to our internal kanbanboard
