### ISSUE TITLE
Linked Data Fragments (LDR)

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#2409]
http://linkeddatafragments.org/ moves some of the query-processing load to the client, to lessen the strain on the server. Typically uses HDT as a format. Has client and server libraries at http://linkeddatafragments.org/software/ (a demo that also supports HyperGraphQL http://query.linkeddatafragments.org/#queryFormat=graphql; lib behind demo: https://github.com/comunica/comunica) 

Do we want to use this to move some load off the node?

Related to #2408

**Comment by fkleedorfer** [comment]
Currently infeasible, I think, because the node is not a standard RDF store that is queried with SPARQL.
