### ISSUE TITLE
Publishing / linking our data

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#2412]
Possible approaches to ease linking with other data-sets and get more reach in the process:

* Put (links to) our data on the DBpedia-databus?
* Link to other datasets and thus make it discoverable/crawlable
* Get Google-Dataset-Search to index our nodes. (https://developers.google.com/search/docs/data-types/dataset) 
* Add ourselves to DBpedia dataset index to get discovered
VoID-description for our dataset root on the node (http://semanticweb.org/wiki/VoID.html)

**Comment by quasarchimaere** [comment]
@fkleedorfer close/later/soon/ready?

**Comment by quasarchimaere** [comment]
moved to our internal kanban board
