### ISSUE TITLE
Automatically calculate dataset quality measures 

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#2413]
* Luzzu: (https://eis-bonn.github.io/Luzzu/) for our nodes. Luzzu-web: http://luzzu.adaptcentre.ie/ 
* Other quality assessment tools: RDFAlert, lodqa, SPARQLES, LIMES, Dynamic Linked Data Observatory
* to check and assess the quality, dereferenceability, logical consistency, link discovery...

**Comment by quasarchimaere** [comment]
@fkleedorfer close/later/soon/ready?

**Comment by quasarchimaere** [comment]
moved to our internal kanban board
