### ISSUE TITLE
API documentation and Agreements

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#2414]
To improve interop with our APIs we could:

* Use schema.org-actions as agreement subjects and offer entry-point declarations for APIs. “Buy-Action ⇔ Offer”
  * https://schema.org/Action
  * https://schema.org/docs/actions.html potential actions
  * https://schema.org/EntryPoint 
  * https://www.w3.org/wiki/images/1/10/PotentialActionsApril11.pdf 
  * https://actions.semantify.it/ respectively https://actions.semantify.it/api-docs/
* RestDesc description of APIs http://restdesc.org/ 
* Hydra description of APIs https://www.markus-lanthaler.com/hydra/ 
* Sitemaps (sitemap.xml)
* VoID descriptions
* TPF endpoints https://www.ibm.com/support/knowledgecenter/en/SSB23S_1.1.0.13/gtpd4/dd_endptgrp.html

**Comment by quasarchimaere** [comment]
@fkleedorfer close/later/soon/ready?

**Comment by quasarchimaere** [comment]
is in our internal kanban board now
