### ISSUE TITLE
Exception from share link component

### ISSUE THREAD

**Issue by sigpie** [researchstudio-sat/webofneeds#2427]
When the details of a post are viewed, an exception is thrown: 

![review-exception](https://user-images.githubusercontent.com/32930574/46861320-bbc84e80-ce12-11e8-8fed-685aedec3d7f.png)

As the resource not found is `https://localhost:8443/owner/{{ self.copied ? '`, a wrong URL seems to be added at some point. This string is only found in post-share-link.js:26, which refers to the clipboard icon used.

**Comment by quasarchimaere** [comment]
duplicates #2388
