### ISSUE TITLE
Adding message details does not work well on iOS

### ISSUE THREAD

**Issue by sigpie** [researchstudio-sat/webofneeds#2428]
The chat details drawer does not open properly on iOS devices (tested with iOS 12.0). 

When first accepting a connection, it opens sometimes, but not reliably. Tapping the `+` icon changes the icon to `x`, but mostly does nothing else. Rarely, the drawer opens after a delay. The drawer seems to conflict with the keyboard, as opening/closing the keyboard and/or starting to type in the message text field sometimes opens the drawer (if the `+` icon was tapped before). Occassionally, it seems as if the drawer is opened downwards as the top halves of the first buttons within the drawer can be seen at the bottom of the screen, but they can't be interacted with. 

It's possible to open the drawer by switching to landscape mode, but this breaks parts of the interface layout since the screen width is then above the responsiveness breakpoint but still to narrow to appropriately display all content.

**Comment by quasarchimaere** [comment]
@sigpie tried it now with android and chrome on the feat_gdpr_aboutpage branch, seems to work alright there, maybe the stylechanges made a difference, can you retest?

**Comment by sigpie** [comment]
The behaviour has improved a lot. There are still some glitches, but they are less prominent and do not prevent using details within a chat.
