### ISSUE TITLE
dummy needs generated when sending request to search results create new matches

### ISSUE THREAD

**Issue by sbyim** [researchstudio-sat/webofneeds#244]
when a user tries to connect to a search result, a dummy need gets created in order to connect to the search result.
This dummy need is handles as  'normal need' on the server and matches get generated for dummy need and other unrelated needs receive the dummy need as 'hints'
this is probably not what a user expects..
![car](https://cloud.githubusercontent.com/assets/5468024/6189618/4f573fd4-b39c-11e4-9c8c-ec7989b53241.PNG)

**Comment by m0ru** [comment]
Mhm. These should somehow be exempt from getting matches (via a "no matches, thx"-flag?)

**Comment by quasarchimaere** [comment]
no longer relevant, issue was solely with the old ui
