### ISSUE TITLE
Unclear Sorting of suggested Posts

### ISSUE THREAD

**Issue by sigpie** [researchstudio-sat/webofneeds#2448]
When suggesting a post in a conversation, it's unclear which posts are suggested in which order.  Own posts aren't shown first and posts seem not to be sorted by creation date.

**Comment by quasarchimaere** [comment]
the sorting is alphabetically, i thought it makes the most sense, however maybe we should split it into two groups

**Comment by sigpie** [comment]
It's only mostly alphabetical (or case-sensitive):

![sorting](https://user-images.githubusercontent.com/32930574/47106010-d0a74680-d245-11e8-90bf-8cf3efda157d.png)
