### ISSUE TITLE
Post AdHoc with persona

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#2471]
When connecting to a need N via WhatsX, it isn't possible to create the Re:N need with a persona, which is inconsistent with normal need creation.

**Comment by quasarchimaere** [comment]
i agree that this is an inconsistency, but i do not see this issue as a bug. imho we should tackle this as w "bigger" issue, namely let people connect with existing needs and or Re: persona needs, maybe we should opt to a point where we connect the persona directly to the need of the other person as the Re: need would not give any additional benefit for the "connect-to"-user anyway, and would also only clutter/duplicate information on the "connect-from"-user.
