### ISSUE TITLE
Create Personas Button within Need Publish opens new tab

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#2479]
I think its a good idea to let the user create a persona after need information is already entered, however i find the current implementation rather subpar because it opens up a new tab (obviously because otherwise one would lose all the info that has been entered before creating a persona) however i think its not an ideal approach to open up a new tab (tab/app duplication -> the user might just continue within the new tab and never look at the old one again....)

... with that being said, i have no clue how to make this any better.... maybe there could be a small discussion to put a little thought into that (whenerver there is a need or time to do so)

**Comment by peacememories** [comment]
We could:
* Make drafts persistent, so users don't lose their work if they navigate to a different part of the app.
* Add a smaller persona creation wizard to the personas dropdown.

**Comment by quasarchimaere** [comment]
i would opt for the smaller persona creation wizard, i think this would be the best option and would def.suffice once we can edit needs

**Comment by peacememories** [comment]
I'm okay with that. Could you change the need title and description, or create a new need, and move it to a todo-column?

**Comment by quasarchimaere** [comment]
closing this issue in favor of #2511
