### ISSUE TITLE
Browser freeze when adding details

### ISSUE THREAD

**Issue by sigpie** [researchstudio-sat/webofneeds#2484]
Might be related to #2367

I can get Chrome to freeze by:
1. opening the add files detail dialog
1. clicking on the drop-area to open a file browser
1. adding any file
1. clicking the "X" button on the file(name) to remove the file while the file browser is still open
1. closing the file browser

**Comment by peacememories** [comment]
I am not sure how to reproduce this.
When the file browser is open, I cannot interact with the page in my version of Chrome (Chrome 72, Ubuntu 18.04). Also the file browser closes when I add a file, so I am not sure how to remove the file while it is still open.

**Comment by quasarchimaere** [comment]
can't reproduce this either chrome/win10

**Comment by quasarchimaere** [comment]
reassigning this issue to @sigpie for further handling/instructions since both @peacememories and i(@quasarchimaere ) and  can't reproduce this

**Comment by sigpie** [comment]
Seems to be a Chrome bug on Windows specifically. This occurs also on other pages and only after a a file was dragged to the filedrop area. 

Closing this since it's not a Web of Needs issue.
