### ISSUE TITLE
New version of rdf-canonize does not need native build

### ISSUE THREAD

**Issue by peacememories** [researchstudio-sat/webofneeds#2493]
A new version of [rdf-canonize](https://github.com/digitalbazaar/rdf-canonize) was released, which does not require a native build. This would greatly improve the development experience on windows, since it should be our only dependency that needs to be built natively. (See https://github.com/digitalbazaar/rdf-canonize/issues/5)

Since we are not depending on the package directly, but through [jsonld.js](https://github.com/digitalbazaar/jsonld.js) we need to wait for it to update its dependencies.
I opened an issue here: https://github.com/digitalbazaar/jsonld.js/issues/272

**Comment by quasarchimaere** [comment]
will move this to clarify, so we can see it in a column to recheck occasionally if the update has been implemented on their end, and to add status comments

**Comment by davidlehn** [comment]
Released jsonld.js 1.2.0 using rdf-canonize 0.3.0.
