### ISSUE TITLE
`isAnonymousUser` only works when privateId is set in url

### ISSUE THREAD

**Issue by peacememories** [researchstudio-sat/webofneeds#2495]
This results in the settings menu displaying the private id instead of "Anonymous" in the account menu.

requires #2283
requires #2554

requires #2568

**Comment by quasarchimaere** [comment]
let us fix this by(or after) implementing #2283, since the current uri saved approach does not really work well i think (as seen with this issue)

**Comment by quasarchimaere** [comment]
Let us tackle this issue after the required issues/prs have been merged. What we should do is include the isAnonymousUser as a state attribute that is set on login/isLoggedIn (as a variable similar to acceptedTermsOfService) and display "Anonymous" (or isAnonymousUser) based on that value after a login.

After this we need to revisit the privateId login itself -> login if privateId is set in the state, and remove the parameter afterwards (isSignedIn will ensure being loggedIn on pageReloads anyway)
