### ISSUE TITLE
White screen while creating new need

### ISSUE THREAD

**Issue by maxstolze** [researchstudio-sat/webofneeds#2497]
On desktop view sometimes a white screen appears after clicking on a detail picker while creating a need (e.g. "Find Band" -> "Title")

![white screen](https://user-images.githubusercontent.com/32457902/48049544-4fd1cf80-e19f-11e8-9486-d6013c8a1c32.PNG)

**Comment by quasarchimaere** [comment]
can anybody reproduce this?

**Comment by peacememories** [comment]
I cannot reproduce this. Please add the browser and version you tested with, in addition to the facts @quasarchimaere asked for.

**Comment by maxstolze** [comment]
Update: Could not reproduce it anymore. Maybe fixed automatically
