### ISSUE TITLE
notification for users when the user gets automatically signedout

### ISSUE THREAD

**Issue by sbyim** [researchstudio-sat/webofneeds#250]
there are at least two cases when the user gets automatically signed out
1. #163 . session timout
2. when a signed in user opens a pre-copied private-link of an anonymously created post in a new tab.

we should consider how these cases should be handled.
do we want to notify the user that he has been signed out?

**Comment by heikofriedrich** [comment]
yeah, i also stumbled across that not really user friendly behavior when you didn't use the WON for some time (probably session time out in between) then you can just continue working with the page (e.g. creating a new need, filling in text and everything) but then at some point (e.g. publishing the need) all your "changes" are lost, and you are really logged out ...

**Comment by fkleedorfer** [comment]
Cleaning up old issues.
