### ISSUE TITLE
Email notification settings are not saved

### ISSUE THREAD

**Issue by heikofriedrich** [researchstudio-sat/webofneeds#252]
Email notification settings (checkboxes below) are not saved in a need: 

new conversation messages
new conversation requests
new matches (~ search results)

How to reproduce:
- create a need
- set checkboxes in settings for emails notifications etc
- log out
- log in 
=> checkboxes are not set anymore

**Comment by yanapanchenko** [comment]
the working version is not on the servers yes, I'll inform when it's there

**Comment by yanapanchenko** [comment]
On the devel servers email notifications are supported now. By default one will get Conversation Request and Conversation Message notifications. If one wants to get Match notifications, it is still possible to use old GUI to set it up in the need's settings.
