### ISSUE TITLE
Update FAQ section

### ISSUE THREAD

**Issue by sigpie** [researchstudio-sat/webofneeds#2528]
The FAQ (and the about page) currently contain no information about usecases or personas, we have a separate privacy policy the FAQs don't refer to and other information might be outdated, too.
Also, links are still formatted as markdown links, but don't work as such.

Related to #1577

**Comment by quasarchimaere** [comment]
@fkleedorfer close/later/soon/ready?

**Comment by quasarchimaere** [comment]
moved to our internal kanbanboard
