### ISSUE TITLE
Change Styling of DirectResponse Needs in the overview

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#2530]
Since a direct Response Need that is owned is not supposed to have more than one connection, we do not need the foldout need -> connection view here at all and could technically figure out a way to put these items in one single line, as well as close the DirectResponse need when we wont need it anylonger anyway.

requires #2505
requires #2529

**Comment by sigpie** [comment]
I agree that the foldout for direct responses is somewhat superfluous, but removing that makes our interface less consistent. Putting connections on the same level as posts would mean that there are two items with slightly different interactions on the main level and connections on two different levels with no really clear indication of why some are grouped under a need while others stand alone. 

We should do a user test with a mockup to determine whether getting rid of the foldout needs is actually beneficial.

**Comment by quasarchimaere** [comment]
moved to our internal kanban board
