### ISSUE TITLE
Save ToS Agreement serverside

### ISSUE THREAD

**Issue by sigpie** [researchstudio-sat/webofneeds#2533]
We need to be able to prove that users agreed to our Terms of Service. This might mean that we need to save this information server side. By doing so, we also document when consent was given/withdrawn, which is important as existing data does not need to be deleted after consent is withdrawn, only if a request for deletion is made.

If the ToS get updated, it should be still GDPR compliant if we ask users to agree to the new ToS without providing an overview on what exactly changed.

**Comment by quasarchimaere** [comment]
i think the scope of this item/issue should only contain saving the flag on the serverside and the handling of it in the ownerwebapp, for storing the actual ToS-yada-yada-yadas we should think about some form of administrative interface and live with the currently config-templated implementation
