### ISSUE TITLE
Filter in Postbox doesn't work

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#254]
![image](https://cloud.githubusercontent.com/assets/551624/6372446/953e692a-bd04-11e4-90e6-1c826700a270.png)

Entering text there doesn't filter.
In IE11 an 'x' occurs for emptying the field, but it doesn't do anything
In other browsers (chrome, FF), the 'x' is not displayed.

**Comment by sbyim** [comment]
fixed in c290922
