### ISSUE TITLE
spurious accept option

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#2561]
When you request a chat connection and the counterpart accepts, the GUI looks as if the coutnerpart was requesting a connection.

**Comment by fkleedorfer** [comment]
Update: A connection request (connect) and the subsequent accepting message (open) is always shown as if it was the initial request and only leads to another handshake message being sent. 

The problem goes away with a reload.


![grafik](https://user-images.githubusercontent.com/551624/49654577-8027ba80-fa38-11e8-9532-5d0aa56d9114.png)

**Comment by quasarchimaere** [comment]
@fkleedorfer can't reproduce this on current master, please try and update the reprosteps or add some console.log as an insight, currently i can send a request and accept it too and there is nothing that goes awry

**Comment by fkleedorfer** [comment]
Reproducible on live. Here's the console output coming along with the wrongly displayed option to accept 
```
senderConnectionUri was null or senderNeed is not ownedNeed, resolve promise with undefined -> ignore the connection messages-actions.js:159:6
Cant parse connection, data is an invalid connection-object (mandatory uris could not be retrieved):  
Object { isLoadingAgreementData: false, isLoadingPetriNetData: false, remoteConnectionUri: "https://node.matchat.org/won/resource/connection/idow8wac3an6q0vw5ay5", messages: {…}, uri: "https://node.matchat.org/won/resource/connection/nwc16dcgbbpx8bz2n66r", creationDate: Date 2018-12-10T09:28:37.914Z, lastUpdateDate: Date 2018-12-10T09:30:05.642Z, showPetriNetData: false, multiSelectType: undefined, unread: true, … }
parse-connection.js:84:4
senderConnectionUri was null or senderNeed is not ownedNeed, resolve promise with undefined -> ignore the connection messages-actions.js:159:6
Cant parse connection, data is an invalid connection-object (mandatory uris could not be retrieved):  
Object { isLoadingAgreementData: false, isLoadingPetriNetData: false, remoteConnectionUri: "https://node.matchat.org/won/resource/connection/idow8wac3an6q0vw5ay5", messages: {…}, uri: "https://node.matchat.org/won/resource/connection/nwc16dcgbbpx8bz2n66r", creationDate: Date 2018-12-10T09:28:37.914Z, lastUpdateDate: Date 2018-12-10T09:30:05.642Z, showPetriNetData: false, multiSelectType: undefined, unread: true, … }
```

**Comment by quasarchimaere** [comment]
@fkleedorfer `...(mandatory uris could not be retrieved)...`-connection-parse-error happens only if: belongsToNeed or hasRemoteNeed or hasRemoteConnection is not set in the retrieved jsonld, maybe this helps

**Comment by quasarchimaere** [comment]
@fkleedorfer probably we have to remove the hasRemoteConnection as the connection does not always have a remoteConnection-Counterpart... idk why the hints would work in general though if this is the case
