### ISSUE TITLE
messages are lost due to crashed websocket

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#2566]
Steps to reproduce:
* open a connection between two needs in the owner webapp
* send some messages back and forth to test it's working
* then wait for the websocket to crash (by disconnecting from wifi or something else to that effect)
* send a message in one of the disconnected owner webapps
* observe that the message is shown as being sent (not yet with two checkmarks)

There are multiple problems here:
* In this situation, obviously, a reload will cause the message to be lost. 
* Reconnecting from the slidein somehow also does not seem to work - possibly there is something wrong with the login state in that case. 
* It's easy for the user not to notice this situation.

Internally the message is queued and would be sent *along with the next message* - but if there is none sent after reconnecting, that won't help.

**Comment by quasarchimaere** [comment]
message handling is currently being refactored in the backend, and will include a bigger change in the front end as well, this issue will not be handled before the refactoring is done, i will close this issue
