### ISSUE TITLE
description text missing in "Request for conversation" 

### ISSUE THREAD

**Issue by heikofriedrich** [researchstudio-sat/webofneeds#257]
Request for conversation detail view:
![image](https://cloud.githubusercontent.com/assets/7766279/6373186/6d5c0804-bd09-11e4-811e-7a5039aca2c5.png)

How to reproduce:
- search for needs
- pick one and contact
- write a message in the field
- open this request from your inbox
=> description text (message) is missing

**Comment by sbyim** [comment]
this is not really a bug,
If a user requests a conversation to a post from search results,
a dummy post will be generated in the form of "Request for conversation to {post the user wants to connect to}" with no text description.
the request message the user has to put in the contact form is the "request" message, which can be checked in the "private-link" page.

**Comment by heikofriedrich** [comment]
ahh ok i see now, but what is still a bit confusing is that the "Request for conversation" is matched to other needs also, not only connected to the requested need

**Comment by sbyim** [comment]
yep.. that is a design decision we have to make and is described in #244

**Comment by heikofriedrich** [comment]
thx
