### ISSUE TITLE
anonymous login link not working

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#2572]
The 'privateId' link does not work anymore. Using it does not log you in, when you create a need, a new anon account is created.

**Comment by quasarchimaere** [comment]
try it with this approach https://stackoverflow.com/a/42416105

**Comment by quasarchimaere** [comment]
already works again on the branch i am currently working on, did not work regardless of the anon-slidein... wasnt working for some time already
