### ISSUE TITLE
"Tune matching behaviour"/matching context is too prominent in need creation

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#2573]
most users (see tests) dont seem to understand matching contexts or "tune matching behaviour" options, they take up too much space and should be an optional detail for some usecases or directly baked into the ownerapp as defaultmatching contexts that can be added to either all or some usecases by default but not by user interaction, i do not think that limiting our matches is a necessary feature right now and imho it only confuses people (cuz they are not sure what it does or why they should  limit the matches)

**Comment by quasarchimaere** [comment]
We also have the option to create needs with a (special) type already and therefore could limit or enhance matching that way, this would be more ideal as we could define if we should pair apples and oranges instead of adding another attribute that does the same. however if we want to limit matching needs within one owner webapp instance to other needs from this exact instance (this is what default context does) we should not let the user decide if they want to leave/remove or alter this option since the user has no idea what to write to get the result that the user wants (since he doesnt even know what to expect as a result to begin with)... additionally matching contexts make it easier to build island-solutions and i am not sure if we should or want to facilitate that out of the box

**Comment by fkleedorfer** [comment]
First step: remove it from create need view completely
