### ISSUE TITLE
verify slide in shown for anonymous user

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#2579]
Steps to reproduce:
1. post something without logging in on a mobile device
2. wait for both the verify and the anon slidein to show up

This does not seem to happen on desktop.

**Comment by quasarchimaere** [comment]
will be obsolete/already fixed in pr #2576

**Comment by quasarchimaere** [comment]
also slidein handling on mobile might be due to mobilecaching issues after redeployment, app does not handle specific state or slidein component any different in mobile

**Comment by quasarchimaere** [comment]
@fkleedorfer did merging pr #2576 fix this issue?

**Comment by quasarchimaere** [comment]
@fkleedorfer please retest, this should be fixed now

**Comment by quasarchimaere** [comment]
does not happen anymore -> close
