### ISSUE TITLE
Show information if counterpart need was archived/deleted

### ISSUE THREAD

**Issue by sigpie** [researchstudio-sat/webofneeds#2588]
When a need is deleted, all connections are deleted (for the deleted need) or closed (for its counterparts). From a user perspective, this means that sometimes connections just disappear with no indication that this happened because the other conversation participant archived or deleted their need. 

To prevent this, show connections that were closed with a state of e.g. `connectionClosedByCounterpart`

**Comment by quasarchimaere** [comment]
related to issue #2587

also: as of now this behaviour is not only shown when deleting a need, it is also happening all the time when a connection is closed or the corresponding remoteNeed is deactivated

**Comment by sigpie** [comment]
As mentioned in #2605 ad-hoc connection needs retain the title and icon of the closed need.

**Comment by quasarchimaere** [comment]
any (suggested) connection that contains a remoteNeed that has been deleted will stay open until the connection is closed, it is not limited to adhoc needs. any connection that references a deleted remoteneed but has no remoteconnection will stay open

**Comment by quasarchimaere** [comment]
@fkleedorfer any thoughts on this one?

**Comment by quasarchimaere** [comment]
no longer relevant, we dont hide closed connections anymore
