### ISSUE TITLE
Adjust JobBot - JobNeed Representation

### ISSUE THREAD

**Issue by maxstolze** [researchstudio-sat/webofneeds#2592]
Adjust JobNeed structure:

- [ ] Refactor job description representation (formatting)
- [ ] Filter out contact info
- [ ] Parse job type field

**Comment by fkleedorfer** [comment]
ad formatting:
* @m0ru says to replace newlines with BRs

**Comment by quasarchimaere** [comment]
@fkleedorfer, description detail is a markdown-enabled detail, br's wont do the trick

**Comment by quasarchimaere** [comment]
closed in favor of jobbot repo issue
