### ISSUE TITLE
Create need with persona fails with in memory database

### ISSUE THREAD

**Issue by maxstolze** [researchstudio-sat/webofneeds#2598]
Creating a need with persona on local machine using in memory database throws:

"won.protocol.rest.LinkedDataFetchingException"

**Comment by quasarchimaere** [comment]
@maxstolze, is the owner or the node running locally? because if its the owner then i did not experience the problem so far

**Comment by maxstolze** [comment]
Owner and node running on localhost with in memory hsql db.

**Comment by sigpie** [comment]
This might be related to #2626
