### ISSUE TITLE
Export "Data Encryption Password"-Label very very unclear

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#2606]
![pw_label](https://user-images.githubusercontent.com/8503486/50208714-36ad6880-0372-11e9-9fc4-090a54585e94.PNG)

As you see in the screenshot, neither the text NOR the label for the password describe what the actual input must be.

We are simply informed that All our account data will be sent to our email address.
But we do not make it clear that we actually have to input our current password here

**Comment by peacememories** [comment]
We... don't. You can use any password you like there, and it will be used to encrypt the data.

**Comment by peacememories** [comment]
I agree, though, that this could be communicated clearer

**Comment by peacememories** [comment]
Does this also count as resolved by #2790 ?

**Comment by peacememories** [comment]
Closed by #2790
