### ISSUE TITLE
Data Export Visibility for unverified Users

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#2608]
We should disallow the ability to export an account if the email of the user is not verified yet (`state.getIn(["account", "emailVerified"]) != true`)

Be aware that anonymous Users will never have a verifiedEmail address and therefore must be excluded from this handling as well. (=> anonymous User data export should be handled in #2607)

**Comment by peacememories** [comment]
Why should we disallow an unverified account from being exported? What are the possible cases for abuse?

**Comment by fkleedorfer** [comment]
You could create a lot of data and then have it sent to your personal enemy's email address, clogging their inbox

**Comment by peacememories** [comment]
The same concern would then mean that we shouldn't allow anonymous users to export their data, because they would have to be able to input any email address. That also means the backend service should be changed not to allow export for anonymous users, since this is freely available right now.

**Comment by fkleedorfer** [comment]
It's a loose end we should tie up. We can handle anonymous user gracefully later.

**Comment by quasarchimaere** [comment]
i would not let anonymous users export their account at all, they have the option to sign up and subsequently export their account later anyway (once they verified their email)

**Comment by fkleedorfer** [comment]
We discussed to let them export to an email address they verify before export without having to create an account. Simpler: create an account, export, then delete it - delete is a relevant feature anyway .

Am 11. März 2019 07:22:25 MEZ schrieb quasarchimaere <notifications@github.com>:
