### ISSUE TITLE
Wrong number of matches shown in postbox overview for need

### ISSUE THREAD

**Issue by heikofriedrich** [researchstudio-sat/webofneeds#261]
should be 3 unread matches:
![image](https://cloud.githubusercontent.com/assets/7766279/6394767/11863ea2-bdd4-11e4-850a-a826b0c8ba31.png)

but actually is only one:
![image](https://cloud.githubusercontent.com/assets/7766279/6394780/3223583e-bdd4-11e4-8a88-1fd5a68bb66b.png)

**Comment by heikofriedrich** [comment]
public link: 
http://rsa021.researchstudio.at:8080/owner/#/post-detail?need=http%3A%2F%2Frsa021.researchstudio.at%3A8080%2Fwon%2Fresource%2Fneed%2F1959637784323793000

**Comment by sbyim** [comment]
Two issues might be related to this one.

1. we don't handle "dead needs" at the moment. dead needs are needs which were indexed by solr but are not on the won node any longer. Thus, the data can't be retrieved from the node and cannot be displayed.
but the matcher based on solr index still fires an hint event, which will increase the notification counter.

Looking at the connections of the need.
http://rsa021.researchstudio.at:8080/won/page/need/1959637784323793000/connections/

there should be four hints and one request..
but two hints are not available("dead needs" on ther server) , so 2 hints shall be displayed on the list. and 4 hints in the notification counter.

the need with the title "Request for converstion to i have club mate 3" is missing in this case..

**Comment by heikofriedrich** [comment]
yes 2 hints are displayed now on the list since a clicked on the one match and read it, so 2 are left

**Comment by heikofriedrich** [comment]
now after signing out and signing in again i dont have any unread macthes anymore!??

**Comment by yanapanchenko** [comment]
That's also a 'feature', due to the fact that the owner application server-side doesn't store such information, only the client-side, which only can know about unread events as long as they are 'coming' and are 'unread' in the same session.

Which I agree is not intuitive from the user perspective. So maybe the information about unread events should be stored on the owner server-side in future implementations?

**Comment by quasarchimaere** [comment]
concerns the old gui -> close
