### ISSUE TITLE
Older users cannot log in

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#2621]
A user created before the email verification feature cannot log in and instead is presented with the verification warning in the login dropdown.

**Comment by quasarchimaere** [comment]
why is this a bug, this is exactly the behaviour that is to be expected

**Comment by quasarchimaere** [comment]
i will close this since this is clearly not a but -> users are able to resend their mail if they are not verified yet (after a login attempt)
