### ISSUE TITLE
Use connection status for connection ordering

### ISSUE THREAD

**Issue by sigpie** [researchstudio-sat/webofneeds#2628]
Currently, all connections for a need are treated the same, regardless of state. If there are many suggested connections, it's easy to overlook/hard to see sent requests or chat messages unless the user manually marked all suggested matches as read before. As an improvement, we could sort by connection status, moving connections in the states `connected` and `request_received` up.

**Comment by quasarchimaere** [comment]
I will close this issue, we might revisit this once we group connection-states (within all connections of a need) but for now it would not be received good from a ux standpoint, we already had implemented a reordering of the connections (based on lastTimestamp) and the jumpiness made connections very hard to (re)find
