### ISSUE TITLE
Archiving and reopening of ad hoc needs acts unexpectedly

### ISSUE THREAD

**Issue by sigpie** [researchstudio-sat/webofneeds#2633]
If an ad hoc need is created to connect with a need and that need is archived or deleted, the ad hoc need continues to exist, while the connection to the removed need is deleted. If the remote need is reopened, no new connection is established. As ad hoc needs don't get matches, any ad hoc need for a removed need can only be closed, as no other interaction is possible. 

The same state is reached by archiving and reopening the ad hoc need. 

I'm not sure what the expected behaviour would be, maybe a new connection between the reopened need and the ad hoc need.

**Comment by quasarchimaere** [comment]
i will move this to later, so we can figure out how to handle this gracefully
my thought in general:
- we should avoid creating adhoc needs and just use these as edge cases -> we should supply reactionUseCases within our useCase definitions for example

**Comment by quasarchimaere** [comment]
adhoc needs are not used/available anymore, the logic changed
