### ISSUE TITLE
Link persona to keybase

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#2636]
[Keybase](https://keybase.io/) allows verifying that a set of given accounts belongs to the same user (by publicly posting signed tokens). This could allow us to establish authenticity. Posting such a token should be a low hanging fruit for us. The largerst effort probably would be to make keybase understand our data-structure and visually communicating who personas belong to.

Side-note: apparently, since i've last been on they page, they've added a messenger and some sort of file-sync on top of this authenticity-scheme.

**Comment by quasarchimaere** [comment]
@fkleedorfer close/later/soon/ready?

**Comment by quasarchimaere** [comment]
closed this issue, is in our internal kanbabn board now
