### ISSUE TITLE
Slide-in is not counted for determining content height

### ISSUE THREAD

**Issue by sigpie** [researchstudio-sat/webofneeds#2649]
Having a slide-in visible means that the footer is always out of sight, even if the content would fit on the screen. This is due to the slide-in height not being counted when determining the needed content height to avoid scrolling. 

It's annoying to have to scroll to see the chat-input and footer while a slide-in is visible. Possible fixes would be a close button for the slide-in or changing the content height calculation to allow for the slide-in.

**Comment by quasarchimaere** [comment]
the option of including the height is not feasible since we cant know the height of the slide-in due to its different content.
