### ISSUE TITLE
Deleted Need still shows up in derivedData of a persona (holds needUri)

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#2652]

**Comment by quasarchimaere** [comment]
@maxstolze, not a reason for the slow app. the slow app is due to ohr angularjs two way binding on an immutable state. many watches and ng-repeats.

**Comment by maxstolze** [comment]
But could be a reason for the "Remote Need Loading Failed" Issue? Double loading of active persona holded needs?

**Comment by quasarchimaere** [comment]
yes
