### ISSUE TITLE
Chats do not scroll and snap to the bottom when sending messages

### ISSUE THREAD

**Issue by sigpie** [researchstudio-sat/webofneeds#2654]
~~When new messages are posted in a groupchat, the view does not scroll down automatically. Similar to #515 #1053 #1105 ~~

If one views a chat and is not scrolled completely to the bottom, sending a message does not induce a scroll to the bottom as well as snapping the scroll behaviour to the bottom again.

Fix Suggestion: try adding the snapToBottom() method within group-post-messages.js and post-messages.js to the function that sends the message (maybe that will fix the issue)

**Comment by quasarchimaere** [comment]
please retest this, i dont know if that is really the case if the group-chat is snapped to the bottom (e.g. scrolled to the bottom) it should automatically scroll to the bottom on subsequent messages until a user scrolls within the chat view (it will start scrolling to the bottom again once the user scrolls to the bottom to "snap" it again)

**Comment by quasarchimaere** [comment]
if it does not work as intended please move to the ready column

**Comment by sigpie** [comment]
For the receiver, scrolling to bottom works, for the sender it doesn't - the sender has to scroll down manually after posting a message.

**Comment by quasarchimaere** [comment]
just checked, the chat view does not scroll and snap to the bottom when sending messages (regardless of 1to1-chat or groupChat) -> will adapt issue description accordingly
