### ISSUE TITLE
Notifications when tabbed-away

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#2658]
Problem: nothing notifies me about new messages, when i'm tabbed away (save for mail-notifications)

Possible solution-parts:

* change page-title with notification count
* change favicon with notification icon
* show toast-popup if allowed (find a good point to ask ppl for consent; e.g. after post-creation)

child of #2000

**Comment by quasarchimaere** [comment]
closed, is in our internal kanban board now
