### ISSUE TITLE
Visitor view fails to load

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#2666]
Sometimes, the visitor view of a need does not load any data.
Here's a successful load:

![loading-worked](https://user-images.githubusercontent.com/551624/51519426-372d9900-1e21-11e9-88f7-1f426a8da1da.PNG)

Here's a failed load:
![loading-failed](https://user-images.githubusercontent.com/551624/51519433-3dbc1080-1e21-11e9-8e4a-9f1f5864404b.PNG)

**Comment by quasarchimaere** [comment]
try again with the new master (should show loading and failedToLoad UI) also set the loglevel in the console to verbose, otherwise it wont print anything of console.debug
