### ISSUE TITLE
Own needs don't get filtered from matches

### ISSUE THREAD

**Issue by sigpie** [researchstudio-sat/webofneeds#2668]
This is a reoccurence of #611 and maybe #1117

To reproduce: create two "Get breakfast" needs or other needs that could be matched together on the same account.

**Comment by quasarchimaere** [comment]
not a bug anymore -> we removed the removeConnection to own behaviour since then

**Comment by sigpie** [comment]
Definitely an issue on matchat right now

![ownneeds](https://user-images.githubusercontent.com/32930574/51540275-509d0800-1e56-11e9-9072-ca4b7f55f1b3.png)
