### ISSUE TITLE
picture upload doesn't work

### ISSUE THREAD

**Issue by cbusch** [researchstudio-sat/webofneeds#267]
Picture for upload can be selected from explorer, but only a selected frame is visible in GUI after "uploading" (see attached pic).

![pic upload_150320](https://cloud.githubusercontent.com/assets/1897633/6749906/4cba03c8-cef5-11e4-9cd9-2f2afe8f966c.JPG)

**Comment by m0ru** [comment]
After Discussion with @fkleedorfer:

Images will be uploaded as part of the message-passing for the create process. Images will be uploaded as separate documents/graphs so that e.g. matchers can choose not to download the images to save on traffic.

**Comment by m0ru** [comment]
Currently we've got code using [Media-Ont](http://www.w3.org/TR/mediaont-10/#core-property-definitions). However it's designed for multimedia applications (read: video+sound). We could switch to <schema.org>'s [ImageObject](http://schema.org/ImageObject) which is conceptualized for images as the name implies.

**Comment by m0ru** [comment]
The images can be embedded as literals as follows: `"/9j/4AAQSkZJRgABAQAAAQABAAD{...}"^^xsd:base64Binary`

**Comment by m0ru** [comment]
More ontologies:
http://dublincore.org/documents/dcmi-terms/index.shtml#terms-format

**Comment by m0ru** [comment]
implemented version: 
```js
{
     // attachment 1 of N
    '@id': 'http://.../resource/attachment/3827681755765819400',
    'cnt:ContentAsBase64' : {
         'cnt:bytes': 'iVBORw0{...}ORK5CYII=',
         'msg:contentType': 'image/png'
    }
}
```
with the namespace:
```js
'cnt' : 'http://www.w3.org/2011/content#'
```

**Comment by quasarchimaere** [comment]
close since this is a problem within the old ui
