### ISSUE TITLE
Anonymous account slide-in has a fake close button

### ISSUE THREAD

**Issue by sigpie** [researchstudio-sat/webofneeds#2676]
The anonymous account slide in shows a close button after the offered link was copied to clipboard or sent by mail. However, clicking on this close button just causes the original warning to reappear. 

While this is useful behaviour to always provide the option to save an anonymous account, it's unexpected for a close button to act this way.

**Comment by quasarchimaere** [comment]
we could include this in the slidein refac. process pr #2669

**Comment by sigpie** [comment]
If there is another slide-in shown (e.g. the disclaimer), using the close button will collapse both slide-ins. This is not necessarily a bug, but there might be a better way to handle this.

**Comment by sigpie** [comment]
The "Link copied to clipboard. X" message from the anonymous account slide-in stays visible after folding and expanding the slide-in - as closing this message and expanding again results in the message being reset, manually folding and expanding should do so, too.
