### ISSUE TITLE
adding time constraints blocks publishing

### ISSUE THREAD

**Issue by cbusch** [researchstudio-sat/webofneeds#268]
Adding a time constraint blocks option to go to the next step. Only clicking on "<previous" is possible. 

![time bug_150320](https://cloud.githubusercontent.com/assets/1897633/6749957/bfeafe88-cef5-11e4-924c-0240f58a1ea5.JPG)

**Comment by quasarchimaere** [comment]
problem within the old gui, in the new ui we do not have timeconstraints yet, therefore i will close this issue
