### ISSUE TITLE
Add invitation feature to group

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#2690]
Group owners currently cannot invite group members, requiring them to ask to join, and, having no option to auto-accept, to wait until the owner accepts. An invitation feature would lower the bar significantly

requires #2704

**Comment by fkleedorfer** [comment]
Possible: manage invite tokens on node, optional use count and deadline

**Comment by quasarchimaere** [comment]
i added the requires #2704, to the description since we are currently unable to send requests from the groupAdministration  -> invites on suggestions do not work (#2704)
