### ISSUE TITLE
GUI is slow

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#2693]
When too much data is present in an account, the GUI becomes too slow to use

**Comment by quasarchimaere** [comment]
"redux-ui-router" clicking on a loaded connection (if nothing is loading in the ui anymore) takes approx. 20sec between the click and until redux-ui-router adds the uri to the url -> reproducible on our klausur account on matchat.org.. idk where lack of performance within the redux-ui-router is located but it seems it is within the dependency itself
