### ISSUE TITLE
Add Persona Later

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#2695]
Adding/Changing Persona after posting should be possible.

**Comment by peacememories** [comment]
Where should we put that functionality, GUI-wise? I can think of the following methods:

* An option in the dropdown menu of a need "Add/Change Persona"
* A button/dropdown in the need description
* An "Edit" Button in the need description/dropdown.

    This would be a bit weird right now as there are no other editable attributes.

Users may also want to add a persona directly in a connection (to the need they made the connection from).
This could be done by sharing the persona, or an interface element in the connection need description or something like that.

**Comment by quasarchimaere** [comment]
here are my two cents:
need dropdown option "Add/Change Persona" (depending on the current state of course either add or change)

if the need doesnt have a persona we could display a button "Add Persona" that links directly to the new view (just so people notice that this is a possibility)

once we include more edit-possibilities we should just rename the dropdown button

adding a persona within a connection should NOT work via sharing a persona as a chat message, the intent seems to be too much of a special case for a connectionMessage and the result is not clearly communicated to the user who shares a persona (the sharing intent might be to reveal the persona for this connection only) -> so i wouldnt worry about this right now, we should make it possible to view our own need details within a connection view somehow though, then we would have access to the need dropdown from there keyword:viewNeedUri
