### ISSUE TITLE
Don't show title in need detail view

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#2699]
If there is a title, it is always used for the header of the view, repeating it is just clutter, especially when the 'title' label is next to it

child of #2687

**Comment by fkleedorfer** [comment]
child of #2687

**Comment by quasarchimaere** [comment]
not true e.g persona but i see the point

**Comment by peacememories** [comment]
I think personas shouldn't use the "Title" detail anywhere.
