### ISSUE TITLE
Group does not see incoming requests without reload

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#2705]
When you create a group, and others request to join, you only see that after a reload.

**Comment by quasarchimaere** [comment]
incoming requests are shown in the group administration and so are all groupconn related status..es?!, they are not reflected in our connection-indicators these are only for chatFacet connections

**Comment by quasarchimaere** [comment]
and where would you want to see "that" do you mean the groupicon? the connIndicators etc.

**Comment by quasarchimaere** [comment]
not a bug, just takes some time to be processed (or retrieved) -> seen with @fkleedorfer
