### ISSUE TITLE
Post this too! does not generate embedded query

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#2720]
When createing a need via 'post this too', the hasQuery property isn't set

requires #2715 (and if that is implemented this issue should have been resolved itself)

**Comment by quasarchimaere** [comment]
@fkleedorfer will be automatically handled after we implemented #2715 -> not a bug yet

**Comment by quasarchimaere** [comment]
also the hasQuery should be generated again based on the details the user chose, we cant and shouldnt use the already present query as there is a high chance it might not align with the details
