### ISSUE TITLE
See matches with own posts when publishing anymously

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#2751]
![image](https://user-images.githubusercontent.com/1730492/52805073-0f2eff80-3086-11e9-95a4-9f6b1461944d.png)

(has the same need-uri in both cases, i.e. is definitely the same need)

**Comment by quasarchimaere** [comment]
thats not an issue any longer, we removed the filter of own need matches due to the fact that we need to match and connect two owned needs together (e.g. group chat and member need) and we choose to remove the filter instead of adding yet another exception to the implementation
