### ISSUE TITLE
Sorting of need/connection lists within post-content/info -- As this shows post creation time instead of matching time, it's more visible that there is no useful sorting of suggested matches, as seen below.

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#2759]
As this shows post creation time instead of matching time, it's more visible that there is no useful sorting of suggested matches, as seen below. New posts are mixed with week- or month-old posts, even on What's New. This might be a general issue, not an issue with this PR though.

![sorting](https://user-images.githubusercontent.com/32930574/53015598-b8417580-344b-11e9-9af2-9b2bd3afc41c.png)

_Originally posted by @sigpie in https://github.com/researchstudio-sat/webofneeds/pull/2757#issuecomment-465113432_

requires #2757

**Comment by quasarchimaere** [comment]
info: this is also because we actually show the post-header as part of a suggestion item instead of the connection-header, it is to be determined if we want to continue to do so or if we would want to change it and use the connection-header instead

**Comment by sigpie** [comment]
This is still an issue with the new What's New view:
![whatsnew_sorting.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ac4930f28a2d6001126c852/125516c66e82c728ace21e0d46ff9c9b37918dac98d6ac4cb649f99a2e046b313916ac217586f76ae5002e565f0d4bfd420c5d17f4af8e79f4b63c708c5e0feb836a4d68d47f40f2ecdd42e64bef62994597b7bb804dc5ed3820e68c8d473a19021d9bb2.png)

**Comment by quasarchimaere** [comment]
sorting behaviour in chats view has changed (newest/most recently updated one first)
