### ISSUE TITLE
Refactor/Fix Rating View

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#2768]
The Rating component is currently based on the presence of the connUri within the url, this is already not working correct as we can see the rating-view within any post-Info already and thus making it impractical and impossible to rate/review a certain persona based on viewing the persona alone...

requires #2769
requires #2775

**Comment by maxstolze** [comment]
Also a "isRated" flag for rated connections in the state to hide rating option & show "rating status" of a connection is needed.

**Comment by quasarchimaere** [comment]
review/rating logic has changed, this issue is no longer relevant
