### ISSUE TITLE
Implement Review Text

### ISSUE THREAD

**Issue by maxstolze** [researchstudio-sat/webofneeds#2775]
Implement reviews including text in backend

**Comment by quasarchimaere** [comment]
probably has a mismatch of required issues, should have requires #2817 first, or maybe its possible that it can be done at the same time, idk what this issue is really intended to do, if there are any frontend changes its def. required to implement #2817 first

**Comment by maxstolze** [comment]
We should implement the reviews structure in the backend first, and then the owner application requirements for the new structure. I think it is necessary now to move the reviews out of the derived data and implement a new entitiy.

**Comment by quasarchimaere** [comment]
no longer relevant
