### ISSUE TITLE
Reopened connections break state

### ISSUE THREAD

**Issue by peacememories** [researchstudio-sat/webofneeds#2778]
When a connection is reopened, say, by attaching a persona to a need that was previously attached to it, the derived data belonging to that connection gets loaded correctly, but since the connection is blacklisted from loading in local storage, this results in inconsistent state.

Removing this blacklist would have a strong negative impact on performance.

**Comment by quasarchimaere** [comment]
A way to resolve this is to add DerivedData within the connectionContainer besides the already existing counters, probably best would be to have a set of uris for each connection state, so we can prioritize the connection based on the state (loading closed connections is not as important as others)

It would also be beneficial to have derivedData within the connection Container based on the Facet(s) -> of a connection, that way we could apply a priority on these groups as well
