### ISSUE TITLE
Description doesn't allow linebreaks

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#278]
Just pasted a longer list of items. In the preview the line-breaks are already gone, rendering the list almost unreadable, which is rather bad if we want people to add longer descriptions in that field.

**Comment by m0ru** [comment]
The linebreaks are there in the textDescription variable. The problem is that without using `<pre>` or parsing the text (to insert `<p>`s instead of the `\n`s), the linebreaks get swallowed as part of the default html-rendering-behaviour.

**Comment by quasarchimaere** [comment]
implemented and deployed on master
