### ISSUE TITLE
"Need a Lift" creation fails without route

### ISSUE THREAD

**Issue by maxstolze** [researchstudio-sat/webofneeds#2788]
Creating a "Need a Lift" post fails if route is not set.

![grafik](https://user-images.githubusercontent.com/32457902/54021096-a8d26400-418f-11e9-9ec2-e02cb3132446.png)

Route should be mandatory anyways.

**Comment by quasarchimaere** [comment]
maybe making the route mandatory isnt the best option for all cases, like what if one wants to hide the route from the public for example... maybe thats somewhat reasonable

**Comment by maxstolze** [comment]
Okay, good point. The Bug is now fixed without the mandatory changes.
