### ISSUE TITLE
Implement Change Password Backend/Frontend

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#2806]
* [x] implement change password back-end
    * [x] implement REST service
    * [x] implement actual password change and reencrypt keystore password
    * [x] raise passwordChangeEvent
    * [x] handle passwordChangeEvent and send mail

* [x] implement change password front-end

**Comment by fkleedorfer** [comment]
[  ] implement change password back-end
[  ] implement change password front-end
