### ISSUE TITLE
Image-picker: the drop-handler takes 1-2s to register the hover

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#2814]
This makes the interaction somewhat sluggish. And people might easily think that it doesn't work (see #2809)

**Comment by quasarchimaere** [comment]
works instantly on my browser (chrome and win10) might be valuable to know

**Comment by quasarchimaere** [comment]
drop interaction on firefox (win10) works instantly as well
@m0ru which browser system do you experience this on?
