### ISSUE TITLE
Edit Need Frontend

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#2825]
child of #822

possibly the easiest approach will be to define a new mode parameter (currently we have DUPLICATE and CONNECT -> maybe EDIT) and simply call the create component/interface/page with that parameter and a fromNeedUri to indicate which need is going to be edited, then we would only have to rename the publish button (maybe prefilled with the persona, if the need was held by one before edit, and omit changing the set persona for now)

On "publish/save" we should then adapt to created message to represent the structure defined in #2824

requires #2824

**Comment by fkleedorfer** [comment]
Change request: in Post detail menu: "Edit Need" -> "Edit"
