### ISSUE TITLE
add deletion to matcher protocol

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#2842]
In MatcherApplicationListenerRouteBuilder, MatcherProtocolMatcherServiceImplJMSBased, MatcherProtocolMatcherService and related classes, need deletion is not handled. 

Would be a valuable addition, along with handling the modifications, when they become available.

I'll label it as a bug as it is caused by the incomplete implementation of a new protocol feature

**Comment by fkleedorfer** [comment]
This causes a log message in matchers and bots (acting as matchers): 
```
Message Type Not Supported : Exchange[ExchangePattern: InOnly, BodyType: String, Body: ...
```
followed by the complete unsupported message

**Comment by quasarchimaere** [comment]
@fkleedorfer isnt this fixed now?

**Comment by fkleedorfer** [comment]
Fixed
