### ISSUE TITLE
Cursor changes to hand over non-interactive maps

### ISSUE THREAD

**Issue by sigpie** [researchstudio-sat/webofneeds#2883]
This happens in the what's new view

**Comment by quasarchimaere** [comment]
happens even though need-map component was initialized with "disable-controls”-attribute. what needs to be done is find a config for leaflet that prevents the cursor to change, (hovering over a marker changes the cursor to a pointer which should probably be prevented as well)

**Comment by quasarchimaere** [comment]
maybe the `user-select: none;` in the need-map css could be used by adding a special css class to the leaflet div inside the components
