### ISSUE TITLE
Uncomfortable handling of What's New view

### ISSUE THREAD

**Issue by sigpie** [researchstudio-sat/webofneeds#2885]
The What's New view behaves unintuitively: 

* no indication that the What's New button opens a new view instead of creating a post/opening an edit interface like all other buttons
* no obvious way back to the default view
* no obvious way back to the What's New interface after viewing a need
* no obvious way back to the What's New view from the default interface
* do discernible method of sorting (see #2759 )
* invisible needs are shown
* personas are shown as new needs
* own needs are shown but there is no indication that they are own needs

requires #2876 (for preloading timestamps and types so we can sort before fetching the actual needs)

**Comment by quasarchimaere** [comment]
> The What's New view behaves unintuitively:
> 
> * no indication that the What's New button opens a new view instead of creating a post/opening an edit interface like all other buttons
> * no obvious way back to the default view
> * no obvious way back to the What's New interface after viewing a need
> * no obvious way back to the What's New view from the default interface
this is a general ux-concern (the need of a dedicated back button in the interface, until recently we have decided that simple back buttons would not make sense as there is already a browserback button that handles the exact same functionality, if we change this behaviour we would have to add this to every other view too (e.g. settings page)

> * do discernible method of sorting (see #2759 )
depends on impl of #2876
> * invisible needs are shown
depends on impl of #2876
> * personas are shown as new needs
not sure if this is necessary personas are needs just like posts, why should new members or modified members get hidden from other users... anyway still requires #2876
> * own needs are shown but there is no indication that they are own needs
noted, needs clarification or discussion if we a) want to hide owned needs within these lists or b) if we want to display them in a certain way, and if so what would they look like in comparison to non owned needs
> 
> requires #2876 (for preloading timestamps and types so we can sort before fetching the actual needs)
