### ISSUE TITLE
Docker - wonnode and owner connection refused

### ISSUE THREAD

**Issue by mszkb** [researchstudio-sat/webofneeds#2919]
I use the docker-compose.yml from won-docker/deploy/local.
Maven full build worked fine.

deploy_host is set to 127.0.0.1
base_folder is set to ~/won and gets filled with files.

Wonnode and owner cannot connect to Postgres.
[Pastebin - Java Exceptions wonnode and owner](https://pastebin.com/PyUeCzGc)

Postgres itself is working fine and I can also connect to that container via docker exec bash and list the created databases. Postgres is also reachable via Pings.

**Comment by quasarchimaere** [comment]
deploy_host cant be set to localhost or 127.0.0.1, otherwise the docker containers will not be able to connect with eachother (as seen in this issue)

fix: deploy_host needs to be set to the (current) ip of the deployed machine
