### ISSUE TITLE
map markers broken since change to parcel builder

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#2938]
![Screenshot_20190520-212619](https://user-images.githubusercontent.com/8503486/58046577-03038400-7b46-11e9-97d5-5407ad926f7d.png)

**Comment by quasarchimaere** [comment]
wasnt able to reproduce on desktop (win10, chrome), happened in chrome on android(9)

**Comment by fkleedorfer** [comment]
this seems fixed now (on current master) - can you please check again @quasarchimaere?

**Comment by fkleedorfer** [comment]
Sorry, false alarm: still broken on master server, but working fine on integration-test.
