### ISSUE TITLE
multiselect checkboxes missing since change to parcel build

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#2939]
![Screenshot_20190520-220745](https://user-images.githubusercontent.com/8503486/58048851-d3f01100-7b4b-11e9-9524-a090515185a6.png)

how to test:
- connect and establish chat with debugbot
- exchange a couple of messages
- try to make proposal (+ button left of msgfield) see that no checkboxes appear next to the individual messages (neither checked nor unchecked)

**Comment by peacememories** [comment]
I can't find any code that should create these checkboxes
