### ISSUE TITLE
Useless back button on Create view

### ISSUE THREAD

**Issue by sigpie** [researchstudio-sat/webofneeds#2954]
The `Create` view still has a backbutton (`<`) that serves no clear purpose. Currently it redirects to the `Inventory` view, which duplicates the navigation bar above. This button should be removed.

**Comment by quasarchimaere** [comment]
i agree the backbutton is not necessary. we can remove it

also i suggest to remove the backbutton of an open chat in mobile also (serves no purpose and should be handled with browserback anyway), maybe we can change it to the close icon in non mobile view also.
