### ISSUE TITLE
Embedded query missing in cycling plan 

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#2957]
Steps to reproduce
1. Create a cycling interest
2. Create a cycling plan
3. look into to generated RDF - there is no embedded query

**Comment by quasarchimaere** [comment]
any indication why this happens? e.g. browser error log entry, uc missing hasQuery parameter...

**Comment by fkleedorfer** [comment]
I've looked but did not notice anything helpful. It does not seem to be caused by specific inputs, I've tried quite a few combinations
