### ISSUE TITLE
Enabled use case should use persona of enabling use case.

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#2958]
When creating an "enabled use case", the persona holding the "enabling use case" should be preselected as the persona for the new "enabled use case". 

The user should be given the option to select another persona or none at all.

**Comment by quasarchimaere** [comment]
not a bug

**Comment by quasarchimaere** [comment]
should we prevent creation withdifferent persona or no persona at all, for all enabled usecases?

maybe people dont want to publish that they are the owner of a groupchat atom (or any other enabled usecase), i would suggest preselecting the persona of the enablingUseCase with the option to change it if need be...

please adapt description accordingly

**Comment by fkleedorfer** [comment]
> not a bug
Yes and no: If you create a persona, then add the interest, and then make the plan, in the current form it is really easy to forget to add the persona to the plan - especially when you are new to the system and are still learning it - and if matching depends on the persona's buddies, that leaves you with a dysfunctional plan. So I would call it a UX bug. But it works as designed and is not a programming bug, we agree on that I guess.
