### ISSUE TITLE
New connections are hard to see

### ISSUE THREAD

**Issue by sigpie** [researchstudio-sat/webofneeds#2966]
When creating a new ~~issue~~ atom, suggestions are very visible in the inventory view, but there is little indication that there are new chats available (only a small blue dot on the chats tab). 

If there are already existing and known chats, the notification is good enough to indicate the presence of new messages, but notifications for new chat requests should be at least as visible as suggestions.

![chat](https://user-images.githubusercontent.com/32930574/60091226-65066900-9744-11e9-9779-ddf99f894d64.png)

^ in this screenshot, there are 2 requested and one active chat connected to the needs shown, but this is not very visible in the interface.

**Comment by quasarchimaere** [comment]
> [...] When creating a new issue, [...]
:-) seems about right analogy to our atom-creation
