### ISSUE TITLE
Deep-Link to suggested connection does not load remote atom data

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#2985]
Required for linking from notifications and emails:
Linking into `https://satvm05.researchstudio.at/owner/#!/post/?postUri=[posturi]&viewConnUri=[connuri]` yields this:

![grafik](https://user-images.githubusercontent.com/551624/60665052-b52bac80-9e63-11e9-8bab-f18f328d5752.png)

**Comment by fkleedorfer** [comment]
Additional bug here: clicking `x` for close does not work when getting to this view with the 'deep link'

**Comment by quasarchimaere** [comment]
clicking the x induces a browser.back, which is somewhat alright but i would like to get rid of that overlay view anyway so i might just do that when handling these bugs, just have to think about a somewhat "smart" solution
