### ISSUE TITLE
Cannot connect to a specific job offer

### ISSUE THREAD

**Issue by sigpie** [researchstudio-sat/webofneeds#2987]
Currently it's not possible to directly connect with a Job Offer from the `What's New` or `What's Around` perspectives or from the detail view of a job offer. 

The atom suggests creating a `search a job` atom to connect with the job offer, but the newly created atom does not create a connection to the original atom. Instead, a general job search atom is created that gets suggestions for all similar job offers. After creating a new atom, the page redirects to `Chats` which suggests that a chat should have been created.

To reproduce: Open the `What's new` view, click on a job offer, select `Search a Job` and publish the new atom.

**Comment by quasarchimaere** [comment]
browser log entries?

**Comment by sigpie** [comment]
Log created on a new account from opening a job offer to just before general matcher suggestions came in. `https://node.matchat.org/won/page/atom/fxmyppq8tups` is the atom created as a response to the offer.

![joblog](https://user-images.githubusercontent.com/32930574/60791935-00480700-a165-11e9-85aa-d5d17a0e5e67.png)

**Comment by quasarchimaere** [comment]
probably caused by the same underlying problem in #2988

**Comment by sigpie** [comment]
When another connection is opened from the new atom (e.g. via a suggestion), a connection to the first job offer does appear in the chat messages. So the problem seems to be that the chat is not displayed, not that it does not exist.
