### ISSUE TITLE
link to previous messages and to communicating needs

### ISSUE THREAD

**Issue by yanapanchenko** [researchstudio-sat/webofneeds#299]
implement: each message is linked to either at least one previous message via msg:hasPreviousMessage relation, or, if it is the first message in the conversation, to both communicating entities via the msg:hasOrigin relation.

**Comment by yanapanchenko** [comment]
implement: comparison of signature values referenced thereof with actual values of processed messages/fetched needs

**Comment by fkleedorfer** [comment]
Has been implemented in a similar way
