### ISSUE TITLE
What's Around only works after What's New

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#3019]
Steps to reproduce:
1. Navigate to what's around.
2. Reload the page
-> the map does not load, no atoms are shown
3. Navigate to what's new
4. wait until you see the breakdown by type
5. Navigate to what's around
-> the map and atoms are now displayed

**Comment by quasarchimaere** [comment]
idk what happens on your end, i just tried this and it works for me... reload on the whats around page should present you with an info and a call to action button labelled "see whats around" it does so for me on matchat.org

**Comment by fkleedorfer** [comment]
Ok. I am logged in, I am on What's around and I see the map and the atoms.
I reload. Then I see this:
![grafik](https://user-images.githubusercontent.com/551624/62787117-4b3a9e80-bac4-11e9-8f57-f882b518b148.png)

**Comment by fkleedorfer** [comment]
Cannot reproduce the empty what's around page, but the 'location access warning' screen is there on each reload on https://www.matchat.org/owner/#!/map

**Comment by quasarchimaere** [comment]
thats not a bug, this screen is so that there is a userinteraction before querying the location, shich is what one is supposed to do

**Comment by quasarchimaere** [comment]
also the "see whats around"-button on the map page after reload is clickable...

**Comment by fkleedorfer** [comment]
Ok, I guess that's right - the map actually does load, it just takes time.
Its' a pure UX problem then:
* There is no indicator showing that the map is loading
* The 'location access' widget wrongly states that access rights need to be granted when actually we only require user interaction. How about showing the location picker in this case, so I can enter a location or use the current location from the dropdown?

**Comment by quasarchimaere** [comment]
seems to work
