### ISSUE TITLE
Check "remember me" by default

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#3022]
Users I interact with say that they want 'remember me' on by default. Users who don't want that will remember to uncheck it. I think we should set it by default.

**Comment by jensitus** [comment]
This would be a first rate improvement!

**Comment by quasarchimaere** [comment]
i don't agree

**Comment by fkleedorfer** [comment]
why not?

**Comment by quasarchimaere** [comment]
checking the remember me by default will FORCE anybody who doesn't want the option to actively deselect it, everytime they perform a login (forgetting once would cause another action or worse, they might not even notice and others can gain access to their account that way)

not checking it by default (which is the SECURE current state) has a negative outcome only for the users who would want to be remembered but forget, the effect is that they simply have to login the next time (no security risk) and check the remember me box

closing this issue
