### ISSUE TITLE
Atom inactivity is not evident

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#3024]
The fact that an atom is inactive is not made explicit anywhere in the atom's views, except for the icon color. There should be some kind of explanation or tag or status displayed, saying that the atom is inactive. I'd go for 'archived', as this is the wording we use for the respective menu action and inventory drawer.

**Comment by m0ru** [comment]
Like this?

![Screenshot from 2019-10-04 17-27-00](https://user-images.githubusercontent.com/1730492/66220252-fc2c7680-e6cc-11e9-983f-54507d154f5f.png)

**Comment by fkleedorfer** [comment]
Bit subtle, but ok

Am 4. Oktober 2019 17:33:03 MESZ schrieb "Renée Singer" <notifications@github.com>:

**Comment by quasarchimaere** [comment]
i dont think that this is a sufficient solution

**Comment by pheara** [comment]
![archived-titlepics](https://user-images.githubusercontent.com/1730492/66391868-8b3bd600-e9ce-11e9-96f9-aad2262117a7.png)

**Comment by quasarchimaere** [comment]
i suggest changing the color saturation of the whole atom-info to black and white as well as adding "This post is archived" text as well as a smaller "ReOpen" atom button in the (call to action) footer

**Comment by quasarchimaere** [comment]
TODO:
- Add grayscale to the whole atom-info content
- Add a "Archived" label in the call-to-action footer, as well as a button next to it to ReOpen the atom

This Atom has been archived [Reopen]

**Comment by pheara** [comment]
state atm:
![Uploading Screenshot from 2019-11-26 14-24-32.png…]()

for a clean way to "gray out"/disable the elements i'd need to pass a flag through all involved components, amongst others:
- disabling the won-atom-menu persona button (as there can't be any personas associated with the atom anymore)
- changing the mixin used by the detail widgets to allow for varying the text-color and icon-color

Any quick workarounds, like setting the overall opacity (resulting in inconsistent background colors) or setting the text color for all descendants (and thus entering specificity battles) are rather suboptimal and most certainly would be the cause of bugs later on.

For these reasons "graying out"/disabling was postponed for now.
