### ISSUE TITLE
Change default tab in inventory-persona view

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#3025]
When showing the inventory, there is a box for each persona. Such a box has 'Detail', 'Posts', Buddies', 'Suggestions' tabs. By default, we show the 'Detail' tab. We should show the 'Posts' tab, as this one holds the most relevant information.

**Comment by quasarchimaere** [comment]
please adapt this as follows:
- look at the parsed child-elements within atom-info.jsx (WonAtomHeaderBig/WonAtomMenu/WonAtomContent/(maybe) FooterElement)
   - and refactor in a way that there are sep. Components for individual the following individual UseCases (Persona & OtherAtom), that way we can individually style the Atom-Info page for each useCase

Hint: Look at `atom-card.jsx` and the subfolder `cards/` to see how it is done for card Views already
