### ISSUE TITLE
[REACT] trig.jsx jsonld handling

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#3029]
trig.jsx does not display jsonld (used for trig of atoms) since there is a async method to parse the jsonld content and that cant be used in the component for now

**Comment by peacememories** [comment]
There doesn't seem to be a `trig.jsx` file anymore. Was the mentioned functionality moved somewhere else or is this issue obsolete?

**Comment by peacememories** [comment]
Looking through the git history it seems the functionality in `trig.jsx` was plainly removed. Is it okay to close this issue?
