### ISSUE TITLE
[REACT] Known create-atom issues

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#3031]
Create-Atom issues:
- create-atom does not set the isValid state of the publish button correctly (info needs to be put in/persona needs to be changed so that the button becomes valid)
- create-atom for duplicate/edit atoms does not handle a reload on the page for now (does not display the atom at all if its not owned and loaded in the background)

**Comment by peacememories** [comment]
Can you clarify the first point? A preliminary test shows that the button does become active

**Comment by peacememories** [comment]
Starting duplication of a post ("Post this too") and reloading the page seems to work also

**Comment by quasarchimaere** [comment]
i think this should be a stray issue that has been fixed...

**Comment by peacememories** [comment]
Seems that way. In that case, I'll close this now
