### ISSUE TITLE
[REACT] chat messages and group-chat-messages unsnap to bottom

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#3032]
If the user scrolls in the chat, the chats automatically jump to the bottom every time a new message comes in, this might bother people if they want to look for a certain message above

**Comment by peacememories** [comment]
This does not seem to be true anymore. While I've noticed the chat thrashes a bit on the first message received when not scrolled to the bottom, it does not snap to the bottom as long as the viewport is scrolled at least a bit up
