### ISSUE TITLE
[REACT] adapt account-settings wrapper to work with REACT

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#3054]
settings-wrapper.js must be rewritten to work

The current settings-wrapper.js is still just for angularjs, this must be rewritten into a jsx component to create the proper react<->elm connection.

Use `elm-react.jsx` as a guideline for the changes

Remove `settings-wrapper.js` after the transfer into a jsx react component has been made.

See `pages/react/settings.jsx` to find out where the old settings-wrapper was included in the template -> basically exchange the currently commented component with the one that has been created

**Comment by fkleedorfer** [comment]
As far as I can tell, the settings view is broken. I get a blank view on matchat as well as ownergreen.

**Comment by quasarchimaere** [comment]
@fkleedorfer the issue is the description of what causes the problem... settings page is empty because nothing is included yet

**Comment by quasarchimaere** [comment]
Updated ToDo (@pheara ):
- Remove/Comment the whole "Persona" Section from the account-settins (does not need to be there anymore)
- Change the Link target for all "Create Persona" buttons (within the persona picker/publish button, and the "Add Persona" atom-info tab to the create-atom page with the parameter `usecase=persona`
