### ISSUE TITLE
[REACT] Rework UI for email-verification process

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#3055]
Please check out the email verification process on the current master, you will notice that the ui handles it very fidgety (e.g. does not automatically display the correct verification message...). Try clicking the verification link both while being logged in as well as while logged out (-> if one is logged out it should display a "please log in now message" or something.... i dont know the correct behaviour anymore)

**Comment by m0ru** [comment]
There's two parts to this:

- while querying `GET /isSignedIn` during app-startup the server responds with with `{..."emailVerified": false...}` even for accounts where I've clicked the link.
- when clicking the link while the app is running, nothing is send to the browser indicating verification has happend.

I'm investigating both of them on the server now.

Side-note: I've found an option to enable stack-traces in the redux-devtools that show where actions have been triggered :3

**Comment by m0ru** [comment]
back to the owner-application: clicking the verification link has no effect as far as i can tell.

**Comment by quasarchimaere** [comment]
afaik the problems must be solely on the frontend side, i assume that it is not even related to the backend of the frontend but actually just a condition that happens because react does not execute the proper verification dispatch or doesnt dispatch at all. i think that react does not respond when the verificationparam is in the url and thus does not call the verification endpoint/dispatcher
