### ISSUE TITLE
Possibly concurrency issues when writing need's key to owner's keystore

### ISSUE THREAD

**Issue by yanapanchenko** [researchstudio-sat/webofneeds#306]
Sometimes, e.g. when running some bots and then stopping them before they finish, the owner's key store becomes corrupted and the keys cannot be read any more from there.

**Comment by yanapanchenko** [comment]
Have not seen it for a long time already, could be already fixed. The keystore can become corrupted when multiple instances of owner or bot or matcher that use the same keystore are run - because different apps are not synchronized for the same keystore. If you run only one owner, or only one bot, or one matcher, or they work on different keystore files, and you still encounter this error - it means it is not fixed yet.

**Comment by fkleedorfer** [comment]
we'll see if this pops up again. Not useful like this
