### ISSUE TITLE
Change owner-webapp build back to webpack

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#3072]
**Is your feature request related to a problem? Please describe.**
parcel bundler is unable to bundle our webapp on windows environments, since we our webapp is developed within unix and windows environments it is essential that it also bundles in both environments

**Describe the solution you'd like**
Change the bundle from parcel back to webpack

**Describe alternatives you've considered**
lets not waste more time on alternatives

**Additional context**
none

**Comment by pheara** [comment]
very temporary work-around: use the linux-subsystem to build on windows:

detailed instructions: https://docs.microsoft.com/en-us/windows/wsl/install-win10

tl;dr:

1. cmd/powershell as admin: `Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux`
2. reboot
3. install distro of choice from windows store (e.g. ubuntu, suse, debian, kali, arch, fedora)

**Comment by quasarchimaere** [comment]
https://gist.github.com/quasarchimaere/e9fe71e049a520c55b9adaa1b78a2d25

**Comment by keshrath** [comment]
So I have to install everything in Sublinux? (maven, npm, etc) or can I somehow access the project on the Windows system and just build inside the subsystem.

**Comment by quasarchimaere** [comment]
> So I have to install everything in Sublinux? (maven, npm, etc) or can I somehow access the project on the Windows system and just build inside the subsystem.

afaik, you should only execute the build (npm run build) from your sub-system, (you only have to go to the correct directory (the one where your webapp project is stored subdir. `src/main/webapp`) everything else can be done outside of the subsystem
