### ISSUE TITLE
Bot should not thrown exception for un-owned atom events

### ISSUE THREAD

**Issue by sigpie** [researchstudio-sat/webofneeds#3078]
When running multiple bots on a system, matcher callback events may be sent to multiple bots, which causes `IllegalStateException`s to be thrown. This should not happen as this occurence is not an illegal state for the bot to be in. 

Possible solutions: 

* only send events concerning bot-owned atoms to each bot via the matcher callback interface
* handle events concerning atoms owned by other users appropriately inside the bot

**Comment by quasarchimaere** [comment]
fixed
