### ISSUE TITLE
Secure Keystore

### ISSUE THREAD

**Issue by yanapanchenko** [researchstudio-sat/webofneeds#308]
Our Keystore used for storing needs' and nodes's private and public keys is not secure; so far it is intended to be used only for developement purposes:
1. Password is hard-coded. Should be changed: move to config file instead, and make it secure.
2. Same passord is used for the whole store, i.e. for accessing keys of all the needs. Should be changed: make it different per user, i.e. dependent on the corresponding user account.

**Comment by yanapanchenko** [comment]
1st point is fixed: now the password is taken from config

**Comment by fkleedorfer** [comment]
longe done
