### ISSUE TITLE
Elm-debugger and the endless lines of GotDimensions port messages

### ISSUE THREAD

**Issue by pheara** [researchstudio-sat/webofneeds#3095]
**To Reproduce**
1. Create new atom
2. Fill out atom
3. Open elm-debugger
4. See the elm port-comm rolling down, one line per frame

**Expected behavior**
Either disable the debugger, as it's unusable as is, or change the communication initialization responsibility and have the wrapper push updated sizes only if they change (instead of Elm sending commands requesting the size)

**Comment by quasarchimaere** [comment]
afair @peacememories told me that the debugger will not be available in production builds anyway, but we could def. alter some of the checks depending on if we need to retrieve the dimensions or not (e.g. if a drop-down/up would even be available) -> but i will mark this as later and also with prio low for now

**Comment by quasarchimaere** [comment]
nlr
