### ISSUE TITLE
Certicate Renewal Link is dead

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#3114]
**Describe the bug**
https://github.com/researchstudio-sat/webofneeds/blob/5aa0f7f046950ba362136127d1b81eb7327a6a87/documentation/building.md#exception-in-owner-webapp-log-pkix-path-building-failed -> the certificate renewal link, does not go anywhere (i think the reference has been lost due to the refactoring, i think we should fix this)

**Comment by sigpie** [comment]
fixed on master
