### ISSUE TITLE
Convoluted workflow to send a buddy request with no existing personas

### ISSUE THREAD

**Issue by sigpie** [researchstudio-sat/webofneeds#3116]
**Is your feature request related to a problem? Please describe.**
I think interacting with personas is currently rather cumbersome and not intuitive. This was my workflow as a person who has experience with using the interface:

1. see a persona you want to be buddies with
1. see no way to send a buddy request (someone not used to the interface might try using the Chat option)
1. click on `Create`
1. see that only new atoms can be created
1. remember the new persona button in the `Inventory`
1. create a persona
1. go back to the persona you wanted to be buddies with
1. send buddy request

**Describe the solution you'd like**

It would have been useful to be able to create a new persona from the details view of another persona. Alternatively, it would be very useful to be able to create new personas from the `Create` tab.

**Comment by quasarchimaere** [comment]
adding a new persona as a buddy of some other persona works now, closing this issue
