### ISSUE TITLE
Link in postal-address

### ISSUE THREAD

**Issue by MaxPodpera** [researchstudio-sat/webofneeds#3150]
When recieving an postal-address via Chat from our Bot. The address is highlighted as an link, the link however does not link to the postal-address but rather to https://hackathon.matchat.org/owner/

![IssueUnbenannt](https://user-images.githubusercontent.com/51529246/70544978-2e46d280-1b6d-11ea-9516-36d2b831ca43.PNG)

**Comment by quasarchimaere** [comment]
what exactly did the bot send as a message, this seems that our markdown parser interprets the message as some link, should it do that or what was the intended purpose of the message?

**Comment by melemalex** [comment]
We accidentally sent the address in square brackets and didn't notice this got interpreted as markdown. 
Issue can be closed! @MaxPodpera @quasarchimaere
