### ISSUE TITLE
Regression: Attaching Location to ChatMessage does not work

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#3153]
**Describe the bug**
The owner-webapp allows you to attach a location to the message you're composing. When you do that, no location data ends up in the message.

**To Reproduce**
1. Create a conversation in the owner-webapp
2. When sending a message, hit '+' and add the location

**Expected behavior**
In the message RDF, there should be some triples representing the location

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser firefox current

**Comment by fkleedorfer** [comment]
Nothing conspicuous in the JS console

**Comment by quasarchimaere** [comment]
probably a hickup due to the new graph uris,not sure if thats the case but i will look into it tomorrow and dispatch accordingly

**Comment by quasarchimaere** [comment]
seems to work fine with me, i guess it works now
