### ISSUE TITLE
The constructor of CreateAtomCommandEvent never uses its default value, leading to exceptions when null is passed

### ISSUE THREAD

**Issue by LeazeDev** [researchstudio-sat/webofneeds#3154]
**Describe the bug**
[Line of the bug-source](https://github.com/researchstudio-sat/webofneeds/blob/781dbf6301f68037142751e5348c71016619ac0e/webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/event/impl/command/create/CreateAtomCommandEvent.java#L42)
Since in the "main"-constructor (the one called by all the others), the uriListName is set to the parameter value whenever `this.uriListName != null`, which is always the case since `this.uriListName` has a default value, this.uriListName will be null if null is passed.
This can lead to exceptions later on, when uriListName must not be null.
This also always occurs, when constructors are used where the uriListName is not explicitly passed (since then the "main"-constructor is called with the uriListName parameter set to null)

**To Reproduce**
1. use, for example, `new CreateAtomCommandEvent(someDataset);`

**Expected behavior**
uriListName of the `CreateAtomCommandEvent` should be the default value, not null

**Comment by quasarchimaere** [comment]
we will fix this for version 0.8, for the time being (or to avoid use of snapshot dependencies) we suggest you use the default uri list name(defined in the CreateAtomCommandEvent) as a constructor parameter to circumvent the npe

**Comment by quasarchimaere** [comment]
fixed in 0.9
