### ISSUE TITLE
Documentation BUG - Bot HowTo: Remembering Your Atoms Across Sessions

### ISSUE THREAD

**Issue by tyriis** [researchstudio-sat/webofneeds#3157]
**Describe the bug**
The documentation shows an invalid command to initialize the won mongo database. In Section: "Bot HowTo: Remembering Your Atoms Across Sessions".

**To Reproduce**
```
> use won
switched to db won
> db.runCommand({createUser:"won", pwd: "won", roles=["dbOwner"]})
2019-12-16T09:52:17.738+0000 E  QUERY    [js] uncaught exception: SyntaxError: missing : after property id :
@(shell):1:50

```

**Expected behavior**
`> use won
switched to db won
> db.runCommand({createUser:"won", pwd: "won", roles:["dbOwner"]})
{ "ok" : 1 }
> 
`
#3158

**Comment by fkleedorfer** [comment]
Thanks for the contribution!

**Comment by tyriis** [comment]
@fkleedorfer yw, thanks for merge :)
