### ISSUE TITLE
ServiceAtomBehaviour Constructor for custom Content of Service Atom not working

### ISSUE THREAD

**Issue by michaelkhuber** [researchstudio-sat/webofneeds#3159]
**Describe the bug**
Me and @svchostdotexe encountered an issue: When a ServiceAtom is created using the ServiceAtomBehaviour, the use of the constructor `public ServiceAtomBehaviour(EventListenerContext context, ServiceAtomContent serviceAtomContent)` with a ServiceAtomContent Object containing Custom Tags the created atom does not contain the tags.

**To Reproduce**
1. In a bot application, create a new ServiceAtomContent and fill it with the content the service atom should have:
`ServiceAtomContent content = new ServiceAtomContent("TestBot");
ArrayList<String> tags = new ArrayList<>();
tags.add("#Test");
content.setTags(tags);
content.setDescription("This is a test.");
serviceAtomBehaviour = new ServiceAtomBehaviour(ctx, content);
serviceAtomBehaviour.activate();`
2. [Check the RDF of the created ServiceAtom](https://hackathonnode.matchat.org/won/page/atom/upeg0yybxqnmkseoqql7) - the Description shows up, but the Tag doesn't.

**Expected behavior**
I wanted to give my ServiceAtom a Tag for identification, so the expected result would have been an RDF which contains the tag.

**Comment by quasarchimaere** [comment]
fixed with won-bot 0.10
