### ISSUE TITLE
User verification stops working after too much time has passed

### ISSUE THREAD

**Issue by Marc-Goritschnig** [researchstudio-sat/webofneeds#3161]
**Describe the bug**
I did not verify my account and after a few days i tried to get a new verification mail but the page responded with "user not found"

**To Reproduce**
1. Go to https://hackathon.matchat.org/owner
2. Signup and do not verify your email
3. Do not verify for a few days
4. Go again to https://hackathon.matchat.org/owner
5. Try login again
6. You are promted to verify your email click on resend, because the last verify token in the first email is out of date.
7. The website responds with user not found and sends no email.

**Expected behavior**
The website should send a  new verification email.

**Screenshots**
![Fail](https://user-images.githubusercontent.com/43956528/70900902-0a1a4400-1ffa-11ea-8eb9-cb073da34539.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 77.0.3865.120

**Additional context**
After like 30 minutes i got the Email but only one... i clicked several times on the resend button within the half hour and every time with the response user not found.

**Comment by maxstolze** [comment]
Could not reproduce the Error and checked the functions. Seems to work properly.
