### ISSUE TITLE
Deleting Atom in bot failes

### ISSUE THREAD

**Issue by maxstolze** [researchstudio-sat/webofneeds#3164]
**Describe the bug**
When deleting an atom with a bot, no success response, but atom is deleted. 

**To Reproduce**
Let a bot delete an atom and check for success response.

**Expected behavior**
Seems to receive SUCCESS_RESPONSE, but also FAILURE_RESPONSE  by trying to retrieve atom again?

**Comment by RobertObkircher** [comment]
Wir haben im Success-Listener eine IllegalStateException geworfen. Anscheinend wird er ab und zu doch aufgerufen (siehe [output.txt](https://github.com/researchstudio-sat/webofneeds/files/3972575/output.txt)).

**To Reproduce**
https://github.com/WoN-Hackathon-2019/won-airqualitybot für längere Zeit ausführen.

**Comment by quasarchimaere** [comment]
fixed in 0.9
