### ISSUE TITLE
ChatSockets Naming Convention

### ISSUE THREAD

**Issue by svchostdotexe** [researchstudio-sat/webofneeds#3165]
**Describe the bug**
The ChatSocket naming convention is pretty inconsistent. Sometimes it is named "ChatSocket", in other instances "chatSocket" is used.

**To Reproduce**
1.  Let the skeletorBot create its first atom.
2. Create a custom post via the web interface.
3. Compare the two different spelling conventions.

**Examples**
chatSocket: https://hackathonnode.matchat.org/won/page/atom/dt65mxps0d2s
ChatSocket: https://hackathonnode.matchat.org/won/page/atom/bl7myk6oppjhfxbf4j9y

**Comment by fkleedorfer** [comment]
Agreed, this could be more consistent. It is not something one should rely on, anyway. The important thing is that they have the triple

```
{socketURI} won:socketDefinition  <https://w3id.org/won/ext/chat#ChatSocket> .
```
The name of {socketURI} is more like a variable name. Sometimes, '{atomURI}#socket1' is a chat socket.

**Comment by quasarchimaere** [comment]
naming convention of a uri is not a bug, see explanation above
