### ISSUE TITLE
Own Section for Service Atoms

### ISSUE THREAD

**Issue by legarou** [researchstudio-sat/webofneeds#3173]
When starting a bot one generates a service atom that is located in the "Other" section of the web interface. 

**Problem**
It is difficult to find one's bot if there are many other bots or other atoms in that section, especially if those are generated regularly - for example the weather bot posts atoms every few seconds and one's own bot might soon get "lost" since only the last 200 or so atoms are shown.

**Solution**
A solution could be to make an own section for sevice atoms.

**Comment by Zai-shen** [comment]
Another soultion could be to futher separate the "Other" section, to enable at least some kind of classification - e,g Chatbots | Locationbots etc.
