### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#318]
# Comparision of Methods

I'll try to compare between a set of alternative approaches for including the icons in this issue:

* every svg on it's own
* icon fonts
* inline-svg + `use`-syntax
* css-referenced svg sprite maps
* `<use>`-referenced svg-sprite maps
* using defined `<view>`s and referencing them via fragment identifiers

The comparisons in [Inline SVG vs Icon Fonts](https://css-tricks.com/icon-fonts-vs-svg/) by Chris Coyier (2014/04) make a strong point against icon fonts in favour of inline svg. His later article [SVG `use` with External Source](https://css-tricks.com/svg-symbol-good-choice-icons/) (2014/05) also suggest externalising the inline-svg again but still referencing it via `<use>`.

The main points boil down to:

* every-svg-on-it's-own is straight-forward to use but results in a large number of http-requests, which weighs heavy on page-load-performance.
* icon-fonts cause undesired rendering issues (e.g. blur, glyph sizes unequal to the svg-sizes,...)
* inline-svg has better semantics and styling capabilities than icon-fonts
* css-referenced sprite maps have worse semantics than inline-svg but better caching behaviour (as they're external to the html)
* external sprite-maps referenced via `<use>` combine the best of inline-svg and css-based sprite maps in that they have good semantics and good caching behaviour.
* `<view>` seems have all the advantages of `<use>` but with a simpler syntax for referencing it.

**Comment by m0ru** [comment]
# How To

## SVG-sprites

* https://kartikprabhu.com/articles/inline-svg-icons

**Comment by m0ru** [comment]
## Summary

For the sake of being able to switch the type of sprite I'd recommend using *SVG-Sprite* and for ease of use the "`<view>`+`<img>`"-syntax.

**Comment by quasarchimaere** [comment]
this ticket is no longer relevant, the new gui facilitates a sprite map
