### ISSUE TITLE
Template Parsing Performance

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#319]
Currently we use template strings (either inline or as seperate template-html) which require runtime-parsing. We could use jsx which is now supported by babel by default. However it needs virtual-dom to create real dom-elements from the compile-time virtual-dom-elements. 

There is an experimental virtual-dom-driver for angular 1.X: https://github.com/teropa/angular-virtual-dom. Which probably is not suited for production use.

Beyond that I'd need to research this properly if time permits and this added run-time performance is required.

**Comment by fkleedorfer** [comment]
Cleaning up old issues - Out of scope
