### ISSUE TITLE
Post as [persona] unreliable

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#3199]
**Describe the bug**
This is a regression. When you post as [persona], in about 30-50% of the cases, the post is not added to the persona. 

**To Reproduce**
1. post something with a persona. Probably it will work as expected
2. do it again until the post is created, but not added to the persona

**Expected behavior**
Post is always added to the persona

**Comment by quasarchimaere** [comment]
? this was the exact behaviour that was supposed to have been fixed within the pr that you merged -> see issue #3195 , i am pretty sure i fixed this because i was able to reproduce it, find the error fix it, was this not tested or where did this issue arise?

**Comment by fkleedorfer** [comment]
Well a) it seems I didn't test it thoroughly enough and b) the atoms don't disappear - they just don't have a persona attached.

**Comment by fkleedorfer** [comment]
No I remember, I found this issue during testing but a) the PR fixed a lot of bugs that I was waiting for and b) what I was seeing did not strike me as being one of the fixed bugs, which, to be fair, it seems I did not review closely enough.
