### ISSUE TITLE
Unread indicators don't disappear when read

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#3204]
**Describe the bug**
For many of my conversations, the unread indicators don't disappear when I view the conversation.
Group conversations don't seem to have that problem.

**To Reproduce**
1. Have some atoms and make sure they are connected.
2. Close the window and send them some messages from their counterparts
3. Log in again for your user, look into the inventory. You should have some unread indicators
4. click on one of those. The conversation opens, but the 

**Expected behavior**

Once I read a message, there should not be any more indicators about it. If this does not work across multiple browsers, it's ok for now .

**Screenshots**

I don't know how many times I've viewed this conversation, it's still highlighted:

![grafik](https://user-images.githubusercontent.com/551624/74745592-6b61cc00-5264-11ea-9a87-17fb71d74255.png)

![grafik](https://user-images.githubusercontent.com/551624/74745517-4e2cfd80-5264-11ea-9917-4bf144a553ac.png)

**Desktop (please complete the following information):**
- Windows 10
- Firefox and Chrome

**Comment by quasarchimaere** [comment]
already fixed in branch `feat__connect_with_existing`, can be tested once the Pull Request is open
