### ISSUE TITLE
First login does not work

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#3212]
**Describe the bug**
When you log in with a new browser or in a new incognito mode window, the login fails. Instead of logging you in, the webapp reloads into the not-logged-in state. Subsequent login attempts then succeed.

**To Reproduce**
1. (in Chrome) open a new inkognito window
2. try to log in with an existing account
3. the webapp reloads and you are not logged in

**Expected behavior**
You should be logged in

**Desktop (please complete the following information):**
- Windows 10
- Chrome

**Comment by fkleedorfer** [comment]
Possibly, you need to remove all your stored data for matchat.org to reproduce this. I did that prior to describing the bug. However, logging in with a normal (non-inkognito) window did not change this behaviour.

**Comment by fkleedorfer** [comment]
The console log starting with the reload
```

usecase-utils.js:20 useCasesImm:  
Tt {size: 41, _root: Ht, __ownerID: undefined, __hash: undefined, __altered: false}
usecase-utils.js:21 useCaseGroupsImm: 
Tt {size: 10, _root: Pt, __ownerID: undefined, __hash: undefined, __altered: false}
usecase-utils.js:22 allDetailsImm:  
Tt {size: 53, _root: Ht, __ownerID: undefined, __hash: undefined, __altered: false}
usecase-utils.js:23 allMessageDetailsImm:  
Tt {size: 20, _root: Ht, __ownerID: undefined, __hash: undefined, __altered: false}
app.js:59 
{WON_ico_header: "#WON_ico_header", ico-filter_list: "#ico-filter_list", ico-filter_map: "#ico-filter_map", ico-filter_tile: "#ico-filter_tile", ico16_arrow_down: "#ico16_arrow_down", …}
owner-api.js:339 GET https://www.matchat.org:444/owner/ net::ERR_CONNECTION_REFUSED
w	@	owner-api.js:339
A	@	state-store.js:13
s	@	load-action.js:34
(anonymous)	@	load-action.js:24
Promise.then (async)		
(anonymous)	@	load-action.js:23
(anonymous)	@	index.js:9
(anonymous)	@	router-middleware.js:40
(anonymous)	@	app.js:159
Promise.then (async)		
(anonymous)	@	app.js:157
invoke	@	angular.js:5040
(anonymous)	@	angular.js:4842
C	@	angular.js:410
Ze	@	angular.js:4842
i	@	angular.js:1949
Mt	@	angular.js:1970
(anonymous)	@	app.js:180
load-action.js:70 No User Logged in yet, continuing with the initialLoad


```

**Comment by fkleedorfer** [comment]
Cannot reproduce this locally. So far, only on live, and hardly ever with Firefox, but consistently with Chrome: just open an inkognito window and try to log in.

**Comment by peacememories** [comment]
The `signin` request gets canceled right after it is started, and then the page gets reloaded. I assume this can't be reliably reproduced locally because the request finishes too quickly, resulting in the reloaded page being in the logged in state.

My assumption is that this is caused by the normal submit handler of the form firing when it is submitted because there is no `preventDefault()` called in the event handler. I'm not sure how to test this properly other than making the change and redeploying to live, though...
