### ISSUE TITLE
Suggestions view does not show all suggestions

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#3214]
**Describe the bug**
When you have multiple suggestions (say, 30 - but I don't know if there is a lower limit for this behaviour), the view only shows a few. Changes to the number of suggestions by removing or receiving new hints causes unexpected changes to the subset shown.

**To Reproduce**
1. on inttest, post a Pokemon GO interest
2. make sure the Pokemon GO bot is running
3. open the suggestions tab, observe unexpected removals as hints come in, and additions as you remove suggestions

**Expected behavior**
the suggestions tab should show all suggestions

**Screenshots**
30 suggestions:

![grafik](https://user-images.githubusercontent.com/551624/75039941-030c2800-54ba-11ea-8fd0-40a7b8d17d51.png)

after removing 10:

![grafik](https://user-images.githubusercontent.com/551624/75039907-ef60c180-54b9-11ea-9384-39c6ae92d625.png)

**Desktop (please complete the following information):**
Windows 10
Chrome

**Comment by quasarchimaere** [comment]
fixed now due to refactoring/change in suggestions handling
