### ISSUE TITLE
Conversation scrolls to newest message when unread indicators disappear

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#3216]
**Describe the bug**
In a conversation with unread indicators at an earlier point in the history, unexpected and confusing scrolling down to the latest message is triggered by the removal of unread indicators. This is not an issue if the window is already scrolled all the way down when that happens, but extremely annoying when you scroll up to see what you missed, and the moment you found it, the unread indicator disappears and you're back at the bottom. 

There are two use cases for this and in both cases the behaviour is very annoying: a) I really missed something and I want to know what it was. b) I just want to mark all messages read in order to clear the unread indicators.

The second use case is much more frequent than the first, currently, and this is just a hint that a 'clear all' button at the conversation level (or even globally) would be welcome.

**To Reproduce**
1. Have a conversation with more messages than fit in your conversation view
2. open that conversation in an inkognito window - where your unread status is wiped and everything is unread
3. scroll up a bit to an unread message and wait
4. the unread indicator is removed and the conversation scrolls to the latest message

**Expected behavior**
Removing an unread indicator should not be linked with auto-scrolling

**Comment by quasarchimaere** [comment]
we do not have the "unsnap" scrolling behaviour implemented in react yet, what we need to do here is to deactivate the automatic "scrollToBottom" everytime there is a user induced scroll, and activate the autoscroll again if the user scrolls to the bottom of the chat.

affected components: atom-messages.jsx and group-atom-messages.jsx
