### ISSUE TITLE
Email-links and push-notifications into conversations or to matches don't open properly

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#3219]
**Describe the bug**
You get an email or push notification about, say, a new message. You haven't used the webapp in a while. The link opens, but you are not logged in and you get to an empty chats view. I believe in this case you have to log in, reloading does not help.

**To Reproduce**
1. Provoke a 'new Conversation' or 'new Message' email, or maybe you have one already
2. click the link to take you to the conversation
3. if you did not have a live session prior to this, you'll end up with an empty view, not logged in.

**Expected behavior**
At least if the remember-me option is active, you should get logged in and see the conversation.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/551624/75111462-64f39b80-563a-11ea-98aa-a39c856c13d8.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
I suspect this is related to #3212

**Comment by maxstolze** [comment]
Resolved in #3373 & #3355
