### ISSUE TITLE
Retracted message of partner shows up as normal

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#3229]
**Describe the bug**
In the owner webapp, when you retract a message, your conversation partner will not see it as retracted.

**To Reproduce**
1. Have a conversation (you need access to your partner's screen)
2. send a message
3. retract the message
4. look at the screen of your conversation partner

**Expected behavior**
The retracted message should be shown as retracted and should not allow proposing or claiming.

**Screenshots**
Here's what the partner sees:
![grafik](https://user-images.githubusercontent.com/551624/75707846-f197fc80-5cbf-11ea-923a-2eaba9c5f6bb.png)
Consequently, the propose/claim buttons are still there:
![grafik](https://user-images.githubusercontent.com/551624/75707933-1be9ba00-5cc0-11ea-815d-7d405508d35f.png)

**Desktop (please complete the following information):**
- Windows 10
- Chrome

**Comment by quasarchimaere** [comment]
see code changes in pr #3228, seems to me like reject and retract still use "old" behaviour, maybe a similar change as we did for claims fixes those also
