### ISSUE TITLE
Owner Webapp: endless connection loading loop 

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#3239]
**Describe the bug**
Once you view a conversation, that connection is loaded over and over again, in a few seconds intervals.

**To Reproduce**
1. Load the webapp with an existing account that has an ongoing conversation
2. open the conversation
3. observing the network activity shows the connection is loaded over and over

**Expected behavior**
Data should only be loaded once

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome

**Comment by quasarchimaere** [comment]
should be fixed since the last PR onto live/master
