### ISSUE TITLE
owner webapp cannot connect to default won node after startup

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#324]
If the owner webapp is started before its corresponding won node webapp, it will fail to connect to the configured default won node upon startup (obviously), and it will not attempt to connect to it later on, effectively making it unusable.

Mitigation: make sure the won node is started first. 
Required fix: regular attempts to reconnect

**Comment by quasarchimaere** [comment]
If the owner app is not connected to the WoN node, it will be able to send messages to it but not receive any, because it is not registered to listen at its dedicated message queue. 

The fact that the owner application that just sent a message is not registered at its dedicated queue is not logged as an error by the WoN node, which makes debugging harder. Should be fixed, too.

**Comment by yanapanchenko** [comment]
was fixed with changes in registration/messaging related to security, e.g. in c421d4e79602ea64406b37eeb3fadaa88453ef67
