### ISSUE TITLE
bestfetch 4.0.0 used

### ISSUE THREAD

**Issue by jamesplease** [researchstudio-sat/webofneeds#3253]
Hey team!

I noticed you're using `bestfetch@4.0.0`. Unfortunately, that library is not ready to be used, so I would **strongly** discourage you from using it at the moment. I accidentally published a stable and am unable to unpublish npm packages which is why it's on the registry.

There's a note at the top of the README saying it's not ready for use yet. Sorry for the confusion!

Once you see v5 out, then that means it's ready to go. You can follow along with that work here: https://github.com/jamesplease/bestfetch/pull/59

James

**Comment by quasarchimaere** [comment]
thx, @jamesplease, we tried using it for fetch deduplication and it seemed to work fine for some fetches but performance lagged if the duplicate fetches became too many at once >10, afterwards we saw that it is clearly stated that bestfetch is not to be used in production, so we excluded it from our fetching process again. thx for the info
