### ISSUE TITLE
Externalize Elm resize events to create fewer messages

### ISSUE THREAD

**Issue by peacememories** [researchstudio-sat/webofneeds#3255]
Currently the elm based publish button checks the size of the window every frame to decide whether its dropdown should be placed above or below it. This is done because the Elm api does not offer an event-based check for the window size.
Alternatively, we could listen for size changes in the Elm component javascript and send that to the application. This would make elm more debuggable since the event log would not be flooded with messages, and it would probably help a bit with performance.

**Comment by quasarchimaere** [comment]
nlr
