### ISSUE TITLE
Android and https

### ISSUE THREAD

**Issue by yanapanchenko** [researchstudio-sat/webofneeds#330]
When we enable HTTPS on ownerweb app server, most probably our owner android app client needs to be set up to trust the owner server certificate. I've just encountered an alternative that seems to be quite useful: https://github.com/ge0rg/MemorizingTrustManager

**Comment by fkleedorfer** [comment]
That sounds interesting, @quasarchimaere what do you think?

**Comment by quasarchimaere** [comment]
if there will ever be a android native client in the future it will be based on a android version higher than 7 and therefore the authentication authorities will be managed differently
