### ISSUE TITLE
Documentation-generator

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#337]
- [JSDoc vs YUIDoc vs Doxx vs Docco – Choosing a JavaScript documentation generator](http://blog.fusioncharts.com/2013/12/jsdoc-vs-yuidoc-vs-doxx-vs-docco-choosing-a-javascript-documentation-generator/) (2013/12)
- [The best JavaScript documentation generator tools and reference builders ](http://www.lsauer.com/2013/05/javascript-documentation-generator.html) (2013/11)

--> **jsdoc** uses the javadoc-syntax that most of us are already accustomed to and that intellij provides auto-completion for, is the easiest to skin among the reviewed tools and allows adding additional tutorial documents.

**Comment by m0ru** [comment]
If you don't have auto-completion for the document structure, [Smartcomments](http://smartcomments.github.io/) provides an online-tool, that generates YUI-style syntax that is relatively similiar to jsdoc (just drop the `@method` and `@class` annotations)

**Comment by m0ru** [comment]
Apparently angular uses it's own flavour of jsdoc callged [ngdoc](https://github.com/angular/angular.js/wiki/Writing-AngularJS-Documentation).

**Comment by m0ru** [comment]
Seems jsdoc has issues dealing with ES6. An alternative list of tools supporting ES6 can be found here: <http://stackoverflow.com/questions/27334309/ecmascript-6-documentation-generators>

**Comment by m0ru** [comment]
[postcss-style-guide](https://github.com/morishitter/postcss-style-guide) would allow us to write the css-styleguide directly next to the css-classes, which should make it easier to keep them in-sync.

**Comment by fkleedorfer** [comment]
maybe someday
