### ISSUE TITLE
Multiple Tabs

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#347]
Javascript state isn't shared across multiple tabs per default. we need to synch it ourselves, either via the server or via local-storage to allow people to use multiple tabs in their browser (without constantly refreshing the app). Or multiple sessions on multiple devices.

Maybe there's an option to move the redux-store (minus the routing information) to local-storage.

**Comment by m0ru** [comment]
There's a redux-falcor connector: <https://github.com/ekosz/redux-falcor>
Once falcor get's a websocket-driver (or we write one) this could solve the synching issues mentioned above.

**Comment by fkleedorfer** [comment]
Cleaning up old issues.
