### ISSUE TITLE
Implement ForgotPassword

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#363]
see todo login.js

Don't forget:
* [ ] when changing passwords, invalidate old recovery keys

**Comment by quasarchimaere** [comment]
unfortunately we can't just reset the password and ask for a new one, because otherwise we lose the ability to encrypt the keystore password, and therefore the user would lose control over the created needs and respective connections....

however a somewhat feasible solution would be that we encrypt and store the keystore password with a generated keyphrase that we will not store on the server but send to the user as a link parameter, and therefore the user could reset the password with that special link.

1) we could renew the link on occasion (every month or so) to enhance security
2) we could send the real password reset link to the email account that is registered on demand (via accessing the previously sent link) and therefore the proper reset link is only accessible if the caller has access to the email account itself -> enhances security

**Comment by peacememories** [comment]
To be able to send a reset link capable of reencrypting the keystore on demand would mean storing it in the server, which would kind of defeat the point of having the encrypted store in the first place, no?

**Comment by quasarchimaere** [comment]
@peacememories yes i see your point, which alternatives do you see that enable the user a password change (if forgotten) that would not make all userneed interactions inaccessible?
