### ISSUE TITLE
Create Post » Image Dropzone Background doesn't render correctly on Chrome

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#372]
For some reason when using the svg-spritemap fragments (our icons in our case), e.g. `icon-sprite.svg#illu_drag_here`, as css backgrounds, they don't render correctly. The div shows another fragment instead (influenced by other interactions on the page).

Opening the svg-fragment directly with the browser however shows the correct fragment.

**Comment by m0ru** [comment]
Apparently there's [some security concerns](http://stackoverflow.com/questions/16042387/svg-spritesheet-targeting-with-css) around using those fragments from CSS and Chrome (as well as Opera) won't be implementing these. Thus it leaves us to either use `<img src="...#...">` for all icons or switch to a different sprite-map setup.

**Comment by quasarchimaere** [comment]
image dropzone is not a part of the create-post component anymore -> no longer relevant will be reimplemented at some point in the future
