### ISSUE TITLE
[TopNav:Post] Not clear what the count number is.

### ISSUE THREAD

**Issue by sbyim** [researchstudio-sat/webofneeds#379]
Is it supposed to be "unread messages"?
![posts](https://cloud.githubusercontent.com/assets/5468024/12329121/0fc0bef4-badf-11e5-8267-c89b07fdce65.jpg)

**Comment by quasarchimaere** [comment]
rather generic question, the implementation that is currently chosen is the implementation that the counter will represent -> for now (number of open posts), if this will ever change we will implenent it in a different user story -> close
