### ISSUE TITLE
add primary image

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#38]
The need RDF structure and code accessing it (NeedBuilder etc) require adding images. One image must be settable as the primary image.

**Comment by m0ru** [comment]
It should be possible to define a square crop-area in the image-picker in create-post. We assume that there'll be large images (e.g. of a couch, a portrait with surroundings) that won't work well when sized down in the square-image-component. This way users can specify the most significant portion of the image. Ideally there should be preview-function in the picker, that shows the image at the size it later will appear at.

In the absence of this mechanism, we might also consider zooming just a bit (e.g. 10%) on any attached photos.

**Comment by fkleedorfer** [comment]
Thinking about this when we are not planning to do it is a waste of time.
