### ISSUE TITLE
Post Title/Short description with line breaks breaks post-overview

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#391]
These line breaks people currently can enter into the short-description/title field during post creation break the GUI in other places later on (e.g. the posts-overview). Alternatively the line breaks (inserted as `<div>`s by default) could be concatenated there. Also in posts-overview the displayed characters need to be limited to what fits the screen or the design must be changed to accomodate for multiline posts (which is probably better anyway, as there's very slim screens out there, i.e. mobile devices)

**Comment by quasarchimaere** [comment]
post overview has been removed -> no longer relevant
