### ISSUE TITLE
post visitor - contextual information

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#394]
Atm the post-visitor view (except for the url-scheme) doesn't show from which own need a connection would be made, thus requiring on the user to remember which post of theirs the counterpart was matched to. Relying on people's memory creates a workflow prone to errors due to natural forgetfulness.

I think we need to update the view with that information.

(Somewhat) related to:
- #191 (finding a link on the web -> visitor view -> connect with own need)
- #216 (private links)

**Comment by m0ru** [comment]
already discussed in a design meeting. need to find the protocoll again

**Comment by quasarchimaere** [comment]
post visitor page is only accessible via a direct link now, so there is no connection between the visible post and one of your posts -> no longer relevant
