### ISSUE TITLE
front-end: displayed order of text messages sometimes wrong

### ISSUE THREAD

**Issue by yanapanchenko** [researchstudio-sat/webofneeds#402]
Possible reason:
at least in the old GUI, when querying the text messages for displaying in conversation view, the messages are ordered by received timestamp of local message and of the corresponding remote message at the same time. If the messages are hosted at different nodes that have time differences, it might lead to the wrong ordering of messages.

**Comment by yanapanchenko** [comment]
reletaed issues #304 and #299

**Comment by fkleedorfer** [comment]
This is still an issue, reproducible in the integration-testing system. The ordering is consistent within each sender but inconsistent between senders.  As @yanapanchenko points out, the possible cause is that the two servers' clocks are not synchronized and ordering uses timestamps of both nodes (but they should only use the timestamps of the owner's node)

**Comment by heikofriedrich** [comment]
![chat1](https://cloud.githubusercontent.com/assets/7766279/16228062/f8092884-37b4-11e6-80b3-8dff11ecfb0a.png)

Also experienced that, my message are sorted all to the top while the bots messages are added at the bottom while we talk ...

**Comment by m0ru** [comment]
Might be caused by how `won.getEvent` is implemented. If it encounters multiple timestamps, it uses the latest (which is flawed if they're from different servers). It should always use the the timestamp from the own owner.

**Comment by fkleedorfer** [comment]
A while ago, we wrote a SPARQL query that takes care of this for the mailbot, @quasarchimaere and I can help

**Comment by fkleedorfer** [comment]
This is still an issue btw, however, it seems, only when the two needs are on different nodes.

**Comment by m0ru** [comment]
We can use the `hasPreviousMessage` triples to get a rough order of messages without looking at the timestamps (and only use the latter as secondary sorting where messages where send at almost the same time and thus have the same previous and next message)

This will be easier to debug once #1092 is resolved. The daisy chaining is also needed for #1056.

**Comment by m0ru** [comment]
https://github.com/researchstudio-sat/webofneeds/pull/1124/files#diff-56522a221b044535f52269b176b6d230 contains a sparql-query for retrieving the messages in a sorted fashion. This should give us an initial sorting; new messages received via the websocket would only need to be inserted at the right position. We'd have to rerun the query whenever "show more" is used though.

**Comment by m0ru** [comment]
Ah, I forgot to run `mvn clean`. It's good now.

**Comment by m0ru** [comment]
here we go again:

> The message ordering is not correct, not even after reloading. We are reading the wrong timestamps, it seems.
- @fkleedorfer (in #1173)
