### ISSUE TITLE
Implement a simple way to re-crawl WoN node

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#408]
Sometimes it may be desirable to make a matcher re-crawl a WoN node or portions of its data. For example, after a matcher downtime, this is required. A mechanism to achieve that might raise the overall system quality. 

A simple command line tool that sends the WoNNodeController an akka message may be sufficient at first

**Comment by heikofriedrich** [comment]
done this be regular recrawling now
