### ISSUE TITLE
Letters shouldn't be filtered/escaped

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#412]
`viele umlaute äöüßó` -> `viele umlaute &#228;&#246;&#252;&#223;&#243;`

same goes for non-latin alphabets

**Comment by quasarchimaere** [comment]
is this still an issue?

**Comment by m0ru** [comment]
Nah, seems fixed now:

**Comment by m0ru** [comment]
![image](https://user-images.githubusercontent.com/1730492/40976801-80420084-68cf-11e8-9466-a877f6588d2d.png)
