### ISSUE TITLE
Matches/Hint Messages arrive at Owner-Server & -Client before Creation was ACK'd

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#413]
When using the EchoBot matches arrive so fast, the owner-server and -app hasn't finished persisting and acknowledging the post yet. As a result the client gets stuck after clicking the publish button while running the bot.

I guess we could fix this by making the owner-server delay the matches until the post has been persisted and the client notified. The websocket guarantees us that they'll arrive in that order at the client.

**Comment by fkleedorfer** [comment]
Should be fixed on the server as well as on the client (making it more resilient against this type of error)

**Comment by fkleedorfer** [comment]
Fixed
