### ISSUE TITLE
Posting doesn't work in FF

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#414]
During the posting process, something fails in firefox. The need is created on the node, a success response is received on the client and the redirect works as well. however the need isn't put into the list of owned needs.

Processing dies somewhere between the log messages "got response for CREATE:..." and "Dispatching action..." in [actions.js:228 to :245](https://github.com/researchstudio-sat/webofneeds/blob/feat-ld-paging/webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js#L228)

**Comment by m0ru** [comment]
cbb079aff60bd7821ab2c8a8f5beba7f5d112315 reduces it to some weird cursor jumping during pasting―if there’s a difference between the raw and the sanitized text, the text-field-content is overwritten with the sanitized version, causing the cursor to reset. Firefox jumps to the start of the field, Chrome to the end.

**Comment by fkleedorfer** [comment]
can we close this?
