### ISSUE TITLE
"Incoming Request"-events, duplicate timestamps

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#419]
@fkleedorfer said that it is probably a bug, so here's [the event](https://gist.github.com/m0ru/ef32276033508ef9e4d3) i crawled after getting a request from our echobot. the graph contains two nodes with `msg:ReceivedTimestamp` but differing times. note that this already is the event from the receiving need's eventcontainer.

first occurance:

``` json
{
      "@id" : "event:az7246a8xpd64cgcd8gf",
      "@type" : "msg:FromExternal",
      "msg:hasReceivedTimestamp" : {
        "@type" : "xsd:long",
        "@value" : "1455539803179"
      },
```

second occurance:

``` json
{
      "@id" : "event:az7246a8xpd64cgcd8gf",
      "@type" : "msg:FromExternal",
      "msg:hasReceivedTimestamp" : {
        "@type" : "xsd:long",
        "@value" : "1455539803129"
      },
```

full json-ld of the event: https://gist.github.com/m0ru/ef32276033508ef9e4d3

**Comment by fkleedorfer** [comment]
won't investigate for now
