### ISSUE TITLE
FF's caching and systemjs don't like each other

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#420]
When the sources are transpiled on the fly, reloading in FF breaks the app. Open a new tab instead and copy-paste the url.

The related git-issue in systemjs' tracker: <https://github.com/systemjs/systemjs/issues/861>

Until they fix it, we should use pre-transpiled sources in FF. (we should anyways, as this is the way we should serve the app in production).

**Comment by Luixo** [comment]
Seems like loading libs that have amd registration included also crash FF with following error:
_Unexpected anonymous AMD define._
Also this behaviour can be triggered by setting any breakpoint in modules (and it's a nightmare!).

**Comment by m0ru** [comment]
Apparently it has something to do with jspm’s dynamic compiling. Now that the app get’s pre-bundled it’s not an issue anymore.
