### ISSUE TITLE
Duplicate functions in LinkedDataService

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#422]
our `linkeddata-service-won.js` contains several sets of functions that seem to do (roughly) the same thing - an opportunity to refactor and simplify the whole thing so it doesn't take more than a day to become confident in making changes there.

this redundancy atm is a potential cause for hard-to-track-down bugs. e.g. several of the functions were missing a requesterWebId, which has been necessary to query events of a need for quite a while now.

e.g.

``` javascript
won.getConnection = function(connectionUri) {...}
won.getconnectionUrisOfNeed = function(uri) {...}
won.getConnectionWithOwnAndRemoteNeed= function(ownNeedUri,remoteNeedUri){...}
won.getConnectionsWithOwnNeed= function(ownNeedUri){...}
won.getConnectionInStateForNeedWithRemoteNeed = function(uri,connectionState) {...}
won.getConnections = function(uri) {...}
won.getConnectionContainerOfNeed = function(needUri) {...}

won.getRemoteConnectionUriOfConnection = function(connectionUri){...}
won.getRemoteneedUriOfConnection = function(connectionUri){...}

won.getLastEventOfConnection = function(connectionUri, requesterWebId) {...}
won.getLastConnectionEvent = function(connectionUri, requesterWebId) {...}
won.getConnectionEvent = function(eventUri, requesterWebId) {...}
won.getEventsOfConnection = 
won.getAllConnectioneventUris = function(connectionUri, requesterWebId) {...}
won.getLastConnectioneventUri = function(connectionUri, requesterWebId) {...}
won.getLastEventOfEachConnectionOfNeed = function(needUri, requesterWebId) {...}
```

**Comment by quasarchimaere** [comment]
is this still an issue after linting and code refactoring?

**Comment by m0ru** [comment]
Yep. Linting can't find non-trivial redundancies and code-duplication for us. Also it can't deal with the way the `won.js` and `linkeddata-service.js` are declared, i.e. it can't autocomplete and find usages etc  Generally, unused functions are only found within a file.

The solution here would be to switch those two files to es6-style `export` statements, remove unused functions (atm this means searching the codebase for each function-name), and lastly to make sure the functions reuse each other instead of solving the same problem over and over again.
