### ISSUE TITLE
Matcher doesn't sign its messages

### ISSUE THREAD

**Issue by yanapanchenko** [researchstudio-sat/webofneeds#440]
The message signing functionality can be added to the matcher when we decide on how do we expose matcher's public key, and implement it. See #307 for possible approaches.

We should then add signature verifier and wellformedness processor into the node routes that deal with incoming from matcher messages (see related todo in WonMessageRoutes).

When matchers have their web identities and sign their messages, we could also think of some matcher-trust/rating mechanisms based on their identities and related hint feedbacks.

**Comment by fkleedorfer** [comment]
Cleaning up old issues. This issue relates to a big change in the way matchers are communicating with WoN nodes. We'll do that, eventually.
