### ISSUE TITLE
Application of Owner outgoing message processors, in particular, signature adder.

### ISSUE THREAD

**Issue by yanapanchenko** [researchstudio-sat/webofneeds#442]
For node, in WonMessageRoutes, we have for incoming and outgoing messages all processors specified, icluding those responsible for signing and verifying. For owner, in OwnerApplicationListenerRouteBuilder, we have processors for incoming messages specified, including signature verifier. For outgoing messages of Owner though, the signing processor is specified in OwnerWonMessageSenderJMSBased (see doSigningOnOwner method). This might not be an optimal design. 

Note: if design is changed, make sure the processors apply for both Bots and Owners.

**Comment by fkleedorfer** [comment]
Cleaning up old issues. We've improved this situation a bit since.
