### ISSUE TITLE
Json-LD Error causes cache-misses

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#458]
However the jsonld we get from the node contains a small mistake that prevents even further caching―the event and connection container's URIs don't end with slashes when they’re used as predicate. I’ve the response-json here: https://gist.github.com/m0ru/31513f9e8c3d731794e6ead11bc43f35

**Comment by fkleedorfer** [comment]
isn't this fixed now?

**Comment by fkleedorfer** [comment]
Fixed
