### ISSUE TITLE
Potential Problem(s) Arising From Need ID Collisions

### ISSUE THREAD

**Issue by fsalcher** [researchstudio-sat/webofneeds#49]
Need IDs will be randomly generated at the client (owner application) and therefore it is possible (but very unlikely) that two clients generate the same ID.

**Implications:**
- The WON Node must check for duplicate entries and respond with a "duplicate ID - create need not accepted" message.
- In the success case such a response will find its way back to the sender via the new need ID but this ID is ambiguous in the duplicate case.

**Solutions:**
- all the participants in the communication keep their low level addressing information until a proper response (or a time out) has occurred
- the response will be send back to all receivers but the one which is already confirmed just drops the message (works only if the need creation is not happening simultaneously)
- the response contains the signature of the initial message so the receivers know if they are meant
  - in this case only a really minor chance of an undefined situation is left, which is that the same owner creates the completely same need twice and two identical IDs are generated

**Comment by yanapanchenko** [comment]
We currently use UriAlreadyUsedCheckingWonMessageProcessor before starting processing the message at node, - it returns failure response in case an already used uri (of need or message) is used. There is still a tiny chance though, for simultaneously incoming several messages/needs with the same uri - that one of them is past this check but not saved yet, then the other one will pass this check as well, - this case we haven't addressed yet in the implementation. 

Solution: we should make the need and messagevent repositories through an Exception in case a need or message with already saved in that repository uri is being saved.
