### ISSUE TITLE
messages panel doesn't scroll to latest message

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#493]
The messages panel gets a scroll bar when more messages are exchanged, but it doesn't scroll to the latest message.

**Comment by m0ru** [comment]
Brain-dump before leaving for today:
I need a way to trigger the scroll-position-update after the scroll-container and the messages have finished rendering as updating requires knowing the former's height.
Ways *not* to do this:
* the link function, which is only called once in the beginning, not after every $digest
* evalAsync: is called after the $digest but before the rendering is finished
* timout: 0 timeout doesn't work. Angular is queueing some promises itself probably. More timeout requires guessing how long angular will need to do its thing.

Interesting refs to check out:
* http://stackoverflow.com/questions/11125078/is-there-a-post-render-callback-for-angular-js-directive
* http://stackoverflow.com/questions/16066239/defer-angularjs-watch-execution-after-digest-raising-dom-event
* http://stackoverflow.com/questions/35218129/call-a-callback-function-after-rendering-the-anchor-in-angularjs
* https://github.com/angular/angular.js/issues/734
* http://stackoverflow.com/questions/24615103/angular-directives-when-and-how-to-use-compile-controller-pre-link-and-post
* http://odetocode.com/blogs/scott/archive/2014/05/07/using-compile-in-angular.aspx

**Comment by puregold117** [comment]
I faced the same issue.
could you plz let me know what was the solution?
