### ISSUE TITLE
unable to log back in after long period of inactivity

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#499]
After playing around a bit, I leave the tab open for a few hours. When coming back to it I realize the session is lost (somehow broken GUI), so I reload the tab and try to log in, but the result is 'no such username/password combination found' displayed below the login form. 

After I close the browser tab and open a new one, I can log in again.

browser: firefox, branch: devel

**Comment by quasarchimaere** [comment]
is duplicated by #1789 -> close this issue
