### ISSUE TITLE
Show previous Messages in received Message Mails

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#514]
it would be beneficial to show the (lets say) last 4-5 messages of the conversation when a user receives an email with a new message, this would improve the value of the received mail

**Comment by heikofriedrich** [comment]
also i dont need to receive a mails at all for messages where i just had a live conversation with someone

**Comment by fkleedorfer** [comment]
the last idea is connectd to #661

**Comment by fkleedorfer** [comment]
Cleaning up old issues. This is out of scope for now
