### ISSUE TITLE
Enable direct link to need

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#517]
The goal is that people can simply copy-paste the url in their address-bar and send the link to one another and the other party will see the post question.

The three alternatives I could find or come up with can be found below. For all of these options, the post in question will always be placed in `['needs','theirNeeds']`. Should the user log in at a later point we can still simply merge over the list of needs. `theirNeeds` is never iterated over directly. In general it would be nicer to have a single map of needs and a seperate list of owned needUris―but that’s a extended refactoring story for another day.

## Option: One Root-View

Use one root-view for everything that is shareable―`/post/?postId?connectionUri?openTab`. When get a link with that pattern and `postId` isn’t owned by you, the `<post-visitor>` component will be `ng-show`n. This approach requires an additional, custom load action-creator with access to the state/urlParams that loads the post in question into the rdfstore and dispatches an action so it’s also in the state.

## Option: Custom Wrapper for `stateGo`

Write a custom action-creator that wraps `stateGo`, makes sure everything’s loaded and then calls the `stateGo`-creator with the orignal or a redirect-URL. For shared posts it would redirect to the existing visitor’s view in all cases and to the landing page if it can’t find a post-Uri to use. However this either requires to trick all `ui-sref`s into using the wrapper or replacing all of them with `ng-click`s that use the new action-creator.

## Option: Route Change Interception

Lastly, there’s the quick’n’dirty solution found [here](http://stackoverflow.com/questions/27212182/angularjs-ui-router-how-to-redirect-to-login-page), that bypasses the whole architecture, registers a custom listener on the `$rootScope` and can change route-changes in progress. I'm not sure we can use the asynchronous `won.getNode` in there however and be sure that the route-change will wait till the need is loaded. There’s the [`resolve`-property](https://github.com/angular-ui/ui-router/wiki#resolve) in state-config that allows asynchronity but can’t get access to `$ngRedux` and thus our state. 

Probably we can forego this constraint anyway and dispatch a hacky `publicNeedLoaded` action once that’s done. The user would see an empty visitor’s view until it happens.

EDIT: [seems to be possible](http://weblogs.asp.net/dwahlin/cancelling-route-navigation-in-angularjs). Just always supress the event and refire it as soon as the asynchronous task finishes.

EDIT2: Apparently resolve can [get injections anyway](http://stackoverflow.com/questions/22537311/angular-ui-router-login-authentication), so we can simply inject `$ngRedux` there and do this the way ui-router was designed to be used. :)   (not that it makes this variant less hacky from the redux viewpoint ;p)

**Comment by fkleedorfer** [comment]
Team decision: option1
