### ISSUE TITLE
nicer urls via html5mode in ui-router

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#520]
Routing-schemes after the fragment-identifier `#` are a bit ugly imo. To have nicer urls, we could tell the ui-router to use the html5-history-api. Instead of http://matchat.org/owner/#/create-need/ we’d have the much more standard-conform http://matchat.org/owner/create-need/. Besides, we would be able to add server-side (pre-)rendering more easily at some point in the future, maybe even have the app work when javascript breaks for the sake of graceful degradation.
- Enabling it in the javascript-app: `$locationProvider.html5Mode(true)` in configRouting.js
- [Configure your server to work with html5Mode](https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#how-to-configure-your-server-to-work-with-html5mode) (for Apache, Nginx, Azure, Express, ASP.Net)
- [Why and how to use the html5 history API](https://css-tricks.com/using-the-html5-history-api/)

**Comment by fkleedorfer** [comment]
Cleaning up old issues.
