### ISSUE TITLE
URLs in conversation emails dont work

### ISSUE THREAD

**Issue by heikofriedrich** [researchstudio-sat/webofneeds#526]
Hi there,

The person behind 'cola 
<https://www.matchat.org:8082/owner/#/post/visitor/info/?theirUri=https://www.matchat.org/won/resource/need/4445728037821597700>' 
wants to contact you 
<https://www.matchat.org:8082/owner/#/post/owner/info?myUri=https://www.matchat.org/won/resource/need/8066727529762994000>. 
They wrote:

hello

[Click here to pick up the conversation] 
<https://www.matchat.org:8082/owner/#/post/visitor/messages/?myUri=https://www.matchat.org/won/resource/need/8066727529762994000&theirUri=https://www.matchat.org/won/resource/need/4445728037821597700>

Best Wishes,
Owner application team

**Comment by fkleedorfer** [comment]
connected to #517

**Comment by heikofriedrich** [comment]
connected to #502
