### ISSUE TITLE
Right column after incoming request has been accepted

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#552]
Switch to the next open requests if there's one or switch tabs if there isn't one. We could also add a redirect for when you try to access an empty tab. The alternative would be to keep it enabled but add a placeholder text: 

"No $x at the moment. [Post]() something to get more $x".

**Comment by m0ru** [comment]
![screen-shot of broken gui](https://cloud.githubusercontent.com/assets/1730492/16233502/e3ce297c-37ce-11e6-9a2d-8030b0055355.PNG)

**Comment by quasarchimaere** [comment]
view does not exist anymore -> no longer relevant
