### ISSUE TITLE
Spinning wheel while posting

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#555]
The static "Pending..." gives the impression that the app has frozen. Vis versa if something's moving, the app communicates clearly that it is processing (i.e. the browser-tab hasn't frozen).

Even better would be a rough upper time-estimate (hard-coded from experience or measured over the last few requests) and/or a progress bar (using that time or the nodes' success-responses)

**Comment by fkleedorfer** [comment]
Or why don't we redirect to another view, like the Posts view, and optimistically display the new post there?

**Comment by m0ru** [comment]
yeah, that and maybe a small icon or something that states that it's still optimistic and turns e.g. into check-marks or something once it's finished. a mouse-over could show a progress bar that derives of the number of success responses / has text or a simple graphic describing where it's currently stuck.

**Comment by fkleedorfer** [comment]
re-posting this with a new title
