### ISSUE TITLE
non-symetrical match?

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#563]
Just created the following two posts on two accounts:

* "chat a while"
* "let's chat :3"

the former got the match, the latter didn't.

**Comment by fkleedorfer** [comment]
@heikofriedrich I think that works as intended, currently. No?

**Comment by heikofriedrich** [comment]
yes, i can remember that for some reason (which i cannot remember anymore right now) this was intended. its not a bug, its a feature. We wanna change it?

**Comment by fkleedorfer** [comment]
closing
