### ISSUE TITLE
Sent text-msg not showing

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#568]
Neither in the own chat\* nor on the receiving side.

\* for the own chat this should have been fixed a while ago. is matchat.org on an old commit?

EDIT: Nvm, there's an exception occuring on the sending side after the send-button has been clicked:

```
TypeError: events.add is not a function app_jspm.bundle.js:1508:36
```

**Comment by fkleedorfer** [comment]
@m0ru still an issue?
