### ISSUE TITLE
Layout problem for long titles

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#570]
This title isn't even that long—we allow got up to 140 characters(!)—however the layout already breaks horribly:

![not enough space for title](https://cloud.githubusercontent.com/assets/1730492/15508893/9a23696c-21d1-11e6-8c4e-ee35dba7fac6.png)

Either we need a way that it can continue over the tab-titles or start with the responsive layout at relatively wide viewport widths. This is a good example for why mobile-first is a better approach when designing. It's always easy a low-effort option to do something with the extra-space when you go from small viewport to large viewport, but things quickly break design-wise and cause a lot of unavoidable work the other way around.

**Comment by m0ru** [comment]
![140 character title in post-view](https://cloud.githubusercontent.com/assets/1730492/15676190/9651ef06-2745-11e6-83f2-f4ea8502393c.PNG)

**Comment by m0ru** [comment]
## Titlebar – Status quo

![default_long](https://cloud.githubusercontent.com/assets/1730492/15679914/fa8cc0e6-2753-11e6-96bc-a5388398ae7b.PNG)
![default_short](https://cloud.githubusercontent.com/assets/1730492/15679915/faacf78a-2753-11e6-94e8-0572ae7b7661.PNG)

**Comment by m0ru** [comment]
## Titlebar – Variant A

![version_a_short](https://cloud.githubusercontent.com/assets/1730492/15679925/02ae41c8-2754-11e6-9e85-15edd5c8dcb5.PNG)
![version_a_long](https://cloud.githubusercontent.com/assets/1730492/15679926/02b2ab96-2754-11e6-9dc6-c07c3d1c9a19.PNG)

**Comment by m0ru** [comment]
## Titlebar – Variant B

![variant_b_long](https://cloud.githubusercontent.com/assets/1730492/15679935/0818985c-2754-11e6-8367-b64986867126.PNG)
![variant_b_short](https://cloud.githubusercontent.com/assets/1730492/15679936/081b4110-2754-11e6-9087-091231e41d4a.PNG)

**Comment by m0ru** [comment]
I think B is slightly better. The design doen't work for the long title in either, though :|
We probably need to reduce the length of the title and implement the need-description soon.

**Comment by m0ru** [comment]
Also the view doesn't work when there are no pictures attached to the post.

**Comment by fkleedorfer** [comment]
UH is on it.

**Comment by m0ru** [comment]
UH: Use variant B. Also we could reduce the font size after the first X characters.
