### ISSUE TITLE
Email not registered but in use

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#574]
If I reload the app a lot occassionally I run into the problem that the sign-in causes an error somewhere in the promise-chain; the gui displays "no such username registered". However when I try to sign it up again, that promise chain also fails and the gui displays "email already in use."

**Comment by m0ru** [comment]
I can't reproduce this locally. If you run accross this error, give me a poke.

**Comment by m0ru** [comment]
Steps to reproduce:
1. sign up with one account
1. sign out
1. sign up with another
1. sign out
1. try to sign in with first account

**Comment by fkleedorfer** [comment]
@quasarchimaere might that be an effect of the behaviour improved by your solution to #632 ? In that case, we may close the issue because it is in essence the error message that is wrong.

**Comment by quasarchimaere** [comment]
i will close this issue since it was related to #632 and only displayed a wrong errormessage
