### ISSUE TITLE
Speed up build

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#577]
Building the whole project takes quite a while. We should take a small amount of time to look into ways to speed it up. It will probably save us a lot of waiting-time in the end.

One of worst scoundrels in our build atm is `jspm install`, as it also checks for package updates.

**Comment by fkleedorfer** [comment]
+1

**Comment by m0ru** [comment]
Resolved by switching to webpack. Build's ~2s now.
