### ISSUE TITLE
handle error cases

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#586]
When 'create need' does not work, show the error views, see
page 29 of R:\02 projekte aktuell\1305-USS WON-COIN\03 work\Usability\GUI Ulf Harr\1511 Design\WON-mockups-draft-20151109.pdf

Tasks:
- send text message
- accept request
- send request
- create need
- check possible error cases
- implement error handling

**Comment by fkleedorfer** [comment]
cleaning up old issues
