### ISSUE TITLE
Design GUI for showing connections in different states

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#593]
Ulf design does not explain where 
- closed connections will be listed
- hidden connections will be listed
  and 
- how to re-open a closed connection
- how to un-hide a hidden connection

We need a design for that. We can use the old GUI as a model.

see NOTE in http://satsrv03:8080/agilefant/qrq.action?q=story:813

Tasks:
- Design GUI & Update Storyboard
- Review GUI & Storyboard
- make new GUI work

**Comment by peacememories** [comment]
This has been open for two years without any changes, should we close this for now?

**Comment by quasarchimaere** [comment]
i am going to close this now, since it does not have any relevance
