### ISSUE TITLE
ReferenceError: connectionListToSet is not defined

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#604]
Happens in current master (4f7b80), after reloading with ctrl+r

```
case actionTypes.login:
                        var ownNeeds = action.payload.get('ownNeeds');
                        ownNeeds = ownNeeds ? ownNeeds.map(function (need) {
                            return connectionListToSet(need);
                        }) : Immutable.Set();
                        var theirNeeds = action.payload.get('theirNeeds');
```

I can't find that function anywhere in the project.

**Comment by m0ru** [comment]
It's part of a896708e5703bf20ee3fa21c5b3af0bfe15653ab: "Fixed reduction of `hasEvents` and `hasConnections`. " which is part of the pull request "Fix receiverequests #566".  Probably I've overlooked the usage while splitting the edits into commits and this half already got merged into master. Sry.
