### ISSUE TITLE
Hit (Ctrl+)Enter to publish

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#606]
It should be possible to submit the need, by hitting ctrl+enter in any of its form fields to submit it (like with any other web form), especially in the title-textfield. This should considerably speed up the interaction for experienced users.

**Comment by m0ru** [comment]
@ waffle discussion column tagging: what's the question to be discussed here? :)
(this is design work that's open imo)
if the question is whether or not we should (given time) then that's a definitive yes :)

**Comment by peacememories** [comment]
Since this has not had any discussion for 2 years and our need creation design has changed dramatically recently I would suggest closing this and opening a new issue for now.
