### ISSUE TITLE
Matches view in FF – should be grid, is single column

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#609]
something bork:
![should be a grid, is a single column](https://cloud.githubusercontent.com/assets/1730492/15707723/8d3f1d70-27fa-11e6-977e-127f6046e0a8.PNG)

**Comment by m0ru** [comment]
seems to be firefox specific

**Comment by fkleedorfer** [comment]
I can confirm this behaviour in FF
