### ISSUE TITLE
Match to own post

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#611]
Hmm, I thought the matches view was filtering these out. The filter probably got lost somewhere along the way:
![matched with own post](https://cloud.githubusercontent.com/assets/1730492/15708098/e2d689e2-27fc-11e6-95f4-d80c524f5969.PNG)

**Comment by m0ru** [comment]
Probably the best point to fix this in one/only a few places, would be in the reducers. They shouldn't save connections and their events between two owned needs to the state. This requires changes to the `need-reducer` (skip the connectionUri), `connection-reducer` (ignore the connection) and `event-reducer` (ignore the events of that connection)

**Comment by m0ru** [comment]
the better way probably is to remove them in the combined reducer to avoid the interdependencies

**Comment by fkleedorfer** [comment]
This needs to be fixed on the server side of the owner webapp

**Comment by m0ru** [comment]
That would save the client from doing the filtering every page load (though it's not that much effort probably) ^_^
