### ISSUE TITLE
View isn't updated after opening a connect

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#630]
Create a need, wait for the debugbot to send a connect. Then accept the connection. The view stays the same even when the second SuccessResponse is received.

**Comment by m0ru** [comment]
Flow: Follow a request to conversation tab after accepting?

Good for people who don't get many requests and want to go straight to chatting, bad for people who want to sort through hundreds of requests. The former are probably more prevalent. Also, *declining* a request doesn't need to trigger a redirect anyway.

This issue imo highlights the importance to get started with the feed, as everything happens in-place there / in-context there without requiring to change the route/view.
