### ISSUE TITLE
unread counters do not count down

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#631]
Create a need and wait for the debug bot to send hint and connect. The unread counters in the overview will count up but when view the new connections (or even accept or decline), the counters do not count down.

**Comment by m0ru** [comment]
Currently the events aren't marked as read at all, so they just stay in the list of unreadEvents till the next page-reload.

I think it should be possible to make the event-reducer update the state during the state-go actions, in particular for the following views:

* incoming request: entirely folded out with conversation on the right side
* messages: entirely folded out with conversation on the right side
* in matches-list: an entry entirely opened (the popup is visible)
* matches grid/tiles-view?

The process should be the same for the overview and non-overview variants. Also, all unread events for the connection should be marked as read (unless we want to factor in how far down people have scrolled in a conversation).

**Comment by fkleedorfer** [comment]
partly done in #744
however: these are still TBD
* does not count down matches when I click the matches tab. (may be ok)
* does not count down matches when I decline a match (but I feel it should)
* does not count down messages for a need when I open the conversation view
* counts messages up while I receive them in the conversation view
* does not count down requests when I click 'requests' and accept a request.

**Comment by quasarchimaere** [comment]
implemented -> no longer relevant
