### ISSUE TITLE
Second need not displayed in gui when creating 2 needs of the same type after another

### ISSUE THREAD

**Issue by heikofriedrich** [researchstudio-sat/webofneeds#638]
log in, create need "do something together" => Publish => need is created in "posts overview" => then create another need in "do something together" => second need does not occur in gui "posts overview" (but is available in won node) => only if another need is created afterwards the second one also occurs

**Comment by heikofriedrich** [comment]
Page reload also displays the second need then

**Comment by heikofriedrich** [comment]
after page reload the need is displayed

**Comment by quasarchimaere** [comment]
Checked Today (on integration-test) does not appear to be an issue anymore, i will close this issue
