### ISSUE TITLE
conversations tend to hang at some point

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#651]
I feel this is reproducible every time although it is not every time exactly the same:

Work with 2 browsers and 2 accounts.
1. create a need in one account and one in the other
2. wait for the match, then connect
3. exchange messages

During this process, at least once, each webapp will stop receiving messages and you'll have to reload

**Comment by m0ru** [comment]
Works with the bot, "only" seems to occur between two actual users. Interesting. ^^

**Comment by fkleedorfer** [comment]
I actually think I also had this with the bot. Maybe it has been fixed already

**Comment by fkleedorfer** [comment]
seems connected to #691

**Comment by fkleedorfer** [comment]
I'm going to look into it

**Comment by fkleedorfer** [comment]
This is unexpected: 
I am testing locally with the debugbot. I start conversations with the hint and the connect need, and I add another one using the hint command. 

In one of these conversations, I keep getting the bot's messages, the other two seem to hang. Upon a reload, though, I can see that the bot always responded, I just don't see the messages. I suspect that the messages are sent to the browser but not displayed correctly.
