### ISSUE TITLE
Pasting doesn't work in the mediumjs textfields (e.g. create post)

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#664]

**Comment by fkleedorfer** [comment]
same as #680?

**Comment by m0ru** [comment]
Yep it is.

**Comment by m0ru** [comment]
Medium.js seems to have a fix on it's master-branch. I've added that to our jspm dependencies instead of the npm-package (that's still at 1.0.1)

**Comment by m0ru** [comment]
Trying to get that master-branch to initialize properly. Importing seems to be a bit tricky and I usually run into an error, that `window.rangy` isn't defined:

```

Error: (SystemJS) Cannot read property 'rangePrototype' of null
	TypeError: Cannot read property 'rangePrototype' of null
	    at eval (https://localhost:8443/owner/jspm_packages/github/jakiestfu/Medium.js@master/medium.js:2567:6)
	    at eval (https://localhost:8443/owner/jspm_packages/github/jakiestfu/Medium.js@master/medium.js:2576:4)
	    at eval (https://localhost:8443/owner/jspm_packages/github/jakiestfu/Medium.js@master/medium.js:2587:4)
	    at eval (https://localhost:8443/owner/jspm_packages/github/jakiestfu/Medium.js@master/medium.js:2589:3)
	    at eval (<anonymous>)
	Evaluating https://localhost:8443/owner/jspm_packages/github/jakiestfu/Medium.js@master/medium.js
	Error loading https://localhost:8443/owner/jspm_packages/github/jakiestfu/Medium.js@master/medium.js as "github:jakiestfu/Medium.js@master/medium.js" from https://localhost:8443/owner/jspm_packages/github/jakiestfu/Medium.js@master.js
	    at eval (https://localhost:8443/owner/jspm_packages/github/jakiestfu/Medium.js@master/medium.js:2567:6)
	    at eval (https://localhost:8443/owner/jspm_packages/github/jakiestfu/Medium.js@master/medium.js:2576:4)
	    at eval (https://localhost:8443/owner/jspm_packages/github/jakiestfu/Medium.js@master/medium.js:2587:4)
	    at eval (https://localhost:8443/owner/jspm_packages/github/jakiestfu/Medium.js@master/medium.js:2589:3)
	    at eval (<anonymous>)
	Evaluating https://localhost:8443/owner/jspm_packages/github/jakiestfu/Medium.js@master/medium.js
	Error loading https://localhost:8443/owner/jspm_packages/github/jakiestfu/Medium.js@master/medium.js as "github:jakiestfu/Medium.js@master/medium.js" from https://localhost:8443/owner/jspm_packages/github/jakiestfu/Medium.js@master.js
```

Gotta research a way to ensure rangy is loaded and attached to window-scope before mediumjs starts.

**Comment by m0ru** [comment]
Currently, on the branch, they're imported via `<script>`-tags. I'm trying to find a way to keep them as part of the bundle.

The [systemjs-docu on modules](https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md) might hold a solution. If no better way to do this is found, [this snippet](https://github.com/jakiestfu/Medium.js/issues/104#issuecomment-71995117) might also work.

**Comment by m0ru** [comment]
Some resources:
    * https://github.com/systemjs/systemjs/issues/666
    * https://github.com/jspm/jspm-cli/issues/689
    * https://github.com/jspm/jspm-cli/issues/1993
    * https://github.com/systemjs/systemjs/blob/master/docs/system-api.md#systemregister-name-deps-declare
    * https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm#map-configuration
    * https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md
    * https://superdevelopment.com/2016/04/14/a-dive-into-systemjs-loading-and-translating/
    * https://github.com/systemjs/systemjs/blob/master/docs/config-api.md
    * https://github.com/systemjs/systemjs/blob/master/docs/es6-modules-overview.md
    * https://github.com/systemjs/systemjs/blob/master/docs/overview.md

**Comment by m0ru** [comment]
Currently trying to get in touch with the jspm-developers over at <https://gitter.im/jspm/jspm>
```
So far I've tried putting these in meta['Medium.js'].globals, including
a commonjs-based helper-script that would usually load them and 
Medium.js in order, and having the dependencies in an amd-based
helper script and have that as dependency via:

    meta['jspm_packages/github/jakiestfu/Medium.js@master/medium.js'].deps
    meta['jspm_packages/github/jakiestfu/Medium.js@master.js'].deps
    meta['github:jakiestfu/Medium.js@master'].deps
    meta['Medium.js'].deps
    reinstalling Medium.js via ./node_modules/.bin/jspm install Medium.js=github:jakiestfu/Medium.js@master -o "{shim:{'Medium.js': ['medium-import-helper']}}"

In each case the executed bundle would first execute the main script 
and crash there, before the dependencies are loaded. If, for testing
 purposes, I use another module that can finish initialization without
 the dependencies, I can see that they get loaded after the main
 script (judging by when I reach the respective breakpoints)
```

**Comment by m0ru** [comment]
Currently trying to get in touch with the jspm-developers over at <https://gitter.im/jspm/jspm>
```
So far I've tried putting these in meta['Medium.js'].globals, including
a commonjs-based helper-script that would usually load them and 
Medium.js in order, and having the dependencies in an amd-based
helper script and have that as dependency via:

    meta['jspm_packages/github/jakiestfu/Medium.js@master/medium.js'].deps
    meta['jspm_packages/github/jakiestfu/Medium.js@master.js'].deps
    meta['github:jakiestfu/Medium.js@master'].deps
    meta['Medium.js'].deps
    reinstalling Medium.js via ./node_modules/.bin/jspm install Medium.js=github:jakiestfu/Medium.js@master -o "{shim:{'Medium.js': ['medium-import-helper']}}"

In each case the executed bundle would first execute the main script 
and crash there, before the dependencies are loaded. If, for testing
 purposes, I use another module that can finish initialization without
 the dependencies, I can see that they get loaded after the main
 script (judging by when I reach the respective breakpoints)
```

**Comment by m0ru** [comment]
Reverting to the `<script>`-style import for now, to get on with this issue. However, this means that these three scripts aren't contained in the bundle and won't go through any linting, should we ever decide to use such. Should the people on jspm/jspm get back to me, I'll fix this.

**Comment by m0ru** [comment]
Places to change: 
* [index.html:33-35](https://github.com/researchstudio-sat/webofneeds/blob/fix_copy-paste_%23680/webofneeds/won-owner-webapp/src/main/webapp/index.html#L33)
* [jspm_config.js:16ff](https://github.com/researchstudio-sat/webofneeds/blob/fix_copy-paste_%23680/webofneeds/won-owner-webapp/src/main/webapp/jspm_config.js#L16)
* [jspm_config.js:56-57](https://github.com/researchstudio-sat/webofneeds/blob/fix_copy-paste_%23680/webofneeds/won-owner-webapp/src/main/webapp/jspm_config.js#L56)
* [the amd-style helper](https://github.com/researchstudio-sat/webofneeds/blob/fix_copy-paste_%23680/webofneeds/won-owner-webapp/src/main/webapp/app/medium-import-helper.js]
* [the commonjs-style helper](https://github.com/researchstudio-sat/webofneeds/blob/fix_copy-paste_%23680/webofneeds/won-owner-webapp/src/main/webapp/app/mediumjs-cjs.js)
* [the previous helper](https://github.com/researchstudio-sat/webofneeds/blob/fix_copy-paste_%23680/webofneeds/won-owner-webapp/src/main/webapp/app/mediumjs-es6.js) that shouldn't have done much.
