### ISSUE TITLE
Improve crawler performance

### ISSUE THREAD

**Issue by heikofriedrich** [researchstudio-sat/webofneeds#665]
- crawler does not perform well, since the "sparqlService.updateNamedGraphsOfDataset(ds);" call is much slower (up to several second when crawler runs under load) than the crawling call "ds = linkedDataSource.getDataForResource(URI.create(uriMsg.getUri()));" (few millisenconds) and they depend on each other

**Comment by heikofriedrich** [comment]
using an accessor or bundeling the queries together doesnt speed up the querying

**Comment by heikofriedrich** [comment]
use 2 different rdf store instances for crawled data and crawling meta data? => should be easy to configure and try out

**Comment by fkleedorfer** [comment]
Cleaning up old issues. I think this is better now.
