### ISSUE TITLE
Error msg when events don't load

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#692]
Occasionally events are referenced by connections but didn't load / there's a bug with storing them, that motivated 
51de48ffd719d3f2a8004ad9bbff9ea60700a83f.

If something fails to load, an error message should be in the log.

Related to #691

**Comment by fkleedorfer** [comment]
Agree that the toasts should be used for errors

**Comment by fkleedorfer** [comment]
Fixed
