### ISSUE TITLE
Denormalize stored events / messages

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#693]
Currently the `hasCorrespondingRemoteMessage` B are stored as childs of an event A in the state under A's URI. In some cases B might actually be the event referenced by the user's connection. This might lead the select not finding the events (see #691, #692 and 51de48ffd719d3f2a8004ad9bbff9ea60700a83f)
To resolve this, A should be next to B in the state and the `hasCorrespondingRemoteMessage` property should only contain an Uri pointing to the respective sibling.

Related to #691
Related to #692

**Comment by fkleedorfer** [comment]
Fixed
