### ISSUE TITLE
Node performance should be improved

### ISSUE THREAD

**Issue by heikofriedrich** [researchstudio-sat/webofneeds#698]
On our test setup cluster the wonnode cannot handle the load off one needcreator bot that creates 1 need every 3 seconds if the wonnode is connected to two matching services that generate approximately 20 hints / need => ca 40 hints / sec and send them back to the wonnode => hint messages as well as need creation messages cannot be handled anymore by wonnode under such load => is there performance improvement possible or do we even need a design change here?

**Comment by heikofriedrich** [comment]
seems to be a memory problem => won log:

 java.lang.OutOfMemoryError: GC overhead limit exceeded
18.7.16 12:07:54.006 [Camel (wonNodeCamel) thread #0 - JmsConsumer[OwnerProtocol.in]] WARN  o.a.c.c.jms.EndpointMessageListener - Execution of JMS message listener failed. Caused by: [java.lang.OutOfMemoryError - GC overhead limit exceeded]

**Comment by fkleedorfer** [comment]
Fixed
