### ISSUE TITLE
Current use of getLocalName might cause name-clashes

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#712]
# The use of `won.getLocalName` strips the uri in front of a predicate. thereotically it's possible that a node might contain two predicates with the same name but with different namespaces (e.g. in prefix-style: `won:location` and `geo:location`). In the objects that `getNode` and `getNeed` build, the one occuring later would overwrite the other property in this scenario, which might cause bugs down the line.

We should convert from uri-style to prefixed versions (assuming that we have constant prefixes) at least for clashes or – if nothing else – throw an exception if a clash occurs, so we can figure out case-by-case solutions.

**Comment by fkleedorfer** [comment]
Cleaning up old issues. I think this is fixed.
