### ISSUE TITLE
Flatten content-node of needs

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#719]
We can drop the `won:hasContentDescription` (and maybe even the `hasContent`?) to flatten the rdf-structure and thus make using the json-ld directly less painful.

@fkleedorfer mentioned that next to the _js-client_ this also requires changes in the _matcher_ and the _needmodelbuilder_.

**Before:** accessing via `need['won:hasContent']['won:hasContentDescription']['won:hasLocation']`

``` javascript
{
  "@id": "https://satsrv04.researchstudio.at:8889/won/resource/need/818203947167131600",
  "won:hasBasicNeedType": { "@id": "won:DoTogether" },

  "won:hasContent": {  // <-------

    "@id": "_:b6",
    "@type": "won:NeedContent",
    "dc:title": " asdf",

    "won:hasContentDescription": {  // <-------

      "@id": "_:b0",
      "@type": "won:NeedModality",
      "won:hasLocation": {
       // ...
      }
    }
  },
  // ...
```

**After:** accessing via `need['won:hasContent']['won:hasLocation']` maybe even `need['won:hasLocation']`

``` javascript
{
  "@id": "https://satsrv04.researchstudio.at:8889/won/resource/need/818203947167131600",
  "won:hasBasicNeedType": { "@id": "won:DoTogether" },

  "won:hasContent": {  // <-------

    "@id": "_:b6",
    "@type": "won:NeedContent",
    "dc:title": " asdf",
    "won:hasLocation": {
     // ...
      }
    }
  },
  // ...
```

**Comment by fkleedorfer** [comment]
No longere applicable
