### ISSUE TITLE
DebugBot: deactivating the need connection doesnt close it

### ISSUE THREAD

**Issue by heikofriedrich** [researchstudio-sat/webofneeds#725]
- used the debug but to test this
- after typing "deactivate" the debug bot does not respond anymore and says iit will close the connection, but the connection is still there on the gui. Also further messages can be send
- the connection can still be closed by clicking on the "close connection" button which really closes the connection

**Comment by quasarchimaere** [comment]
not only can further messages be sent, the debugbot also responds to these messages -> this imho indicates that even the remote connection stays open, thus this is an issue from the backend and not from the frontend

**Comment by quasarchimaere** [comment]
please recheck if this problem still exists
