### ISSUE TITLE
Allow flagging with `won:UsedForTesting` in GUI

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#726]
We introduced the flag `won:UsedForTesting` in order to be able to separate test content from real content.

Currently there is no way in the GUI to add this flag.

Currently there are two ideas for what can be done:
# allow magic hashtag `#UsedForTesting`
pro: easy to implement, easy to learn
con: has to be entered every time, which is tedious if you are REALLY testing

# toggle 'test mode' in user settings. 
When test mode is `on`, all newly created needs get the `won:UsedForTesting` Flag
con: makes creating one single UFT need harder
con: harder to implement
pro: makes longer testing sessions easier

# toggle 'test mode' in GUI 
Actually, there is no need to go all the way to the user settings. It would suffice to have a 'test mode' toggle button (or something similar) somewhere where normal users don't really look (say, the bottom left corner of the page). Test mode should be associated with the session, and default to `off` in a new session.
pro: easy to implement
pro: makes creating many test needs easier
pro: makes creating only one test need only marginally harder
con: test mode has to be re-enabled upon login, which one may forget during testing

**Comment by fkleedorfer** [comment]
when this is implemented, the following steps need to be taken:
* All our bot-created needs must get the usedForTesting flag
* The debugBot must only send hint/connect to needs flagged with usedForTesting
* the matcher must honor the usedForTesting flag

**Comment by heikofriedrich** [comment]
still todo: adapt debug bot
