### ISSUE TITLE
Need creation: post-processing

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#739]
The new way of editing the need content seems to have a few quirks.

We should post-process the need content before sending it in the create message:
- remove any leading nonbreaking spaces
- remove any empty title, description, or tags

**Comment by fkleedorfer** [comment]
@quasarchimaere seems like this is done, right?

**Comment by m0ru** [comment]
As far as title and description are concerned, this should be resolved by #938

**Comment by m0ru** [comment]
Seems to be fixed for tags as well.
