### ISSUE TITLE
Helping people discover and formulate what they need

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#754]
Realizing for oneself and formulating in words what you need can be a difficult task at times. The creation-view has the job of helping people figure that out and specify it in a way that allows the matcher to do a good job. However, currently only the "additional details" – additional input masks – provide any crutch whatsoever. 

@soheilh, @fkleedorfer and i recently had a discussion-branch about this and here are the notes:

Instead of limits also provide inspiration during writing, e.g.:
- sample matches
- a word cloud from similiar needs
- question-response with a chatbot (that would require insanely good world- and language-models)
- (model-based) randomly generated example needs with the option to fix fields and then continue randomizing.

For (non-material) needs this process/experience might be a minor journey of self-discovery. The design and communication should support that to be delightful and engaging.

**Comment by fkleedorfer** [comment]
Definitely an important topic, hopefully we can take that up soon. 
Cleaning up old issues.
