### ISSUE TITLE
Open Solr matching issues

### ISSUE THREAD

**Issue by heikofriedrich** [researchstudio-sat/webofneeds#759]
Currently (23.08.2016) the Solr matcher matches like this:
- default query matches content terms (of fields title, description and tags) with different weights, for title and description fields stemming and synonyms are used and for tags are matched with other tags with synonyms or stemming and with exact matching
- gives an additional multiplicative boost for geographically closer needs
- add filters to the query: right need type, need status active, creation date overlap 1 month, geographical distance < 50 km

What can be improved still:
- It has been observed that queries from needs with longer texts (title, description, tags) will in average get higher Solr score for matching needs, since more terms (absolute not relative to text length) will match other needs. This could be normalized on the query side (?) too, since Solr should already normalize this on the index side (?) => has to be found out and tested
- Currently the Solr matching results (f-score ~ 0.25) are not as good as the optimal COSINE (f-score ~ 0.38)  matching results on the freecycle dataset. It is not really clear why cause different settings have been tested for Solr matching (stemming, stopwords, synonyms, different weights, different elbows and thresholds). The reason should be found out. It could be however that the threshold parameter tuning is easier for COSINE since we have a fixed value range between 0 and 1 while we have a raw unlimted value range for Solr score queries which makes it hard at which threshold to cut the results (this is why we implemented Kneedle algorithm)
- Currently there is a geo filter in the query that means a need that has location specified generates a query that will not match any other needs that have no location specified => however if the filter is removed far away needs will be matched if their descriptions match very good (since the location boost is only between 1 and 2)

**Comment by fkleedorfer** [comment]
partly fixed. Cleaning up old issues.
