### ISSUE TITLE
Sorting of needs and connections

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#760]
It would be nice if the node would add aggregation-infos to the connection containers, e.g. "timestamp of latest event of type X", that together with the list of unread-events allow sorting the feed-entries without fetching every single event.

The same applies for needs and fetching connections. However then the owner would also need to be able to persist and serve information about unread events per connection.

Particullarly when using paging and on the feed this is of critical importance as it determines which entries people get to see at all.

**Comment by fkleedorfer** [comment]
connected to #723

**Comment by fkleedorfer** [comment]
The part about the unread events is postponed.
