### ISSUE TITLE
HTTP Batching

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#764]
Requests that go the same node could be collected and sent in one http-request to improve performance. The node's API endpoint would need to be able to take a list as parameter. Alternatively HTTP/2 should be a more standard-conformous way to do this. On the client, the linkeddata-service would need to collect all requests over a certain period of time: e.g. wait for 200ms after the latest request with max 1000ms after the first in the batch, then send everything.

**Comment by m0ru** [comment]
Falcor's batching might be interesting as reference: <http://netflix.github.io/falcor/video-tutorials/batching-requests.html>

**Comment by fkleedorfer** [comment]
Cleaning up old issues.
