### ISSUE TITLE
Heuristic Evaluation

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#769]
When the next design-iteration comes around, we could also do a heuristic valuation, i.e. evaluate the design against sets of best practices / guidelines in interface design. 
- very high-level: https://www.nngroup.com/articles/ten-usability-heuristics/
- https://www.nngroup.com/articles/how-to-conduct-a-heuristic-evaluation/ <- method on nngroup
- https://en.wikipedia.org/wiki/Heuristic_evaluation <- the method and Gerhardt-Powals' and Weinschenk-Barker's list
- https://www.usability.gov/how-to-and-tools/methods/heuristic-evaluation.html <- method usability.gov
- http://www.userfocus.co.uk/resources/guidelines.html <- focused on web-design but a bit older afair (so your mileage may vary)
- https://www.nngroup.com/articles/113-design-guidelines-homepage-usability/ <- focused on web-design, by norman-nielsen-group
- http://www.uxmatters.com/mt/archives/2014/06/an-overview-of-expert-heuristic-evaluations.php <- article on method by uxmatters
- others that might be interesting:
  - Jakob Nielsen’s “Top 10 Mistakes in Web Design
  - Arnie Lund’s “Expert Ratings of Usability Maxims
  - Bruce Tognazzini’s “Principles of Interaction Design”
  - Ben Shneiderman’s “Eight Golden Rules of Interface Design” 
  - https://developer.apple.com/ios/human-interface-guidelines/
  - https://material.google.com/
  - most slide-sets from usability courses on universities

In all cases these evaluate how far the app conforms to best-practices (and not how well it _actually_ performs when people use it)

**Comment by m0ru** [comment]
@ waffle discussion column tagging: I guess the question here is which of the sets of heuristics we want to use? Otherwise, this is a task for 3-5 of us to go through and log issues somewhere (e.g. in a spreadsheet and as GH-issues) and maybe write a report.

And if a question is whether or not we should (given time) then that's a definitive yes :)

**Comment by peacememories** [comment]
If we "should do this given the time" and there is no discussion on it at all I would move it to "later".

**Comment by quasarchimaere** [comment]
moved to our internal kanbanboard
