### ISSUE TITLE
"Loading"-indicators (e.g. spinners)

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#782]
I made some animation-sketches for "loading"-indicators, that you can find in this zip: [spinners.zip](https://github.com/researchstudio-sat/webofneeds/files/452273/spinners.zip)

Three of the more interesting ones are the triangular, bouncy one – that's good for when there's enough space, but is a bit more effort to implement – and the horizontal ones that communicate "networking" a bit better.
- [won_spinningwheel_tribounce](https://cloud.githubusercontent.com/assets/1730492/18206738/44f5a6ac-7128-11e6-9976-885291f1b1f2.gif)
- [won_spinningwheel_snaking](https://cloud.githubusercontent.com/assets/1730492/18206806/a261de5a-7128-11e6-8396-73c0121ecfd4.gif)
- [won_spinningwheel_snaking_blink](https://cloud.githubusercontent.com/assets/1730492/18206807/a264194a-7128-11e6-9023-6c33c8791c5e.gif)

Note that the "tribounce" one is a really rough animation-sketch. It's not going full-circle and the animation needs to be smoothed out.

**Comment by m0ru** [comment]
Atm the "snaking" variant is used as gif :| 

Using <http://cssanimate.com/> we should be able to port these to css-animations :)

**Comment by quasarchimaere** [comment]
also see issue #1823
