### ISSUE TITLE
Close of connection doesnt work

### ISSUE THREAD

**Issue by heikofriedrich** [researchstudio-sat/webofneeds#801]
Created two needs on different accounts. requested a connection and chattet a bit with both. then i close the connection from one side. => the other need doesnt get notified that the connection was closed and can still write messages etc to it

**Comment by quasarchimaere** [comment]
is this still an issue? please let us retest this

**Comment by heikofriedrich** [comment]
![sending.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5714a67d0019b11300f6d9bf/125516c66e82c728ace21e0d46fb9194278b8daecda5fd53b652fa912a5265296b51f47b72d0e27bbb10785909581cfe41585f42fefd8f79a1a42062c80d55b98e30063e937f03a6aa801db500bf208c4f86b7bb824cc1ed3e37aa.png)

**Comment by heikofriedrich** [comment]
relates to #1231
