### ISSUE TITLE
Show human-friendly matcher name / identity

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#803]
For the future when there's multiple matcher's running, the name of the matcher that send a particular hint should be visible somewhere in the GUI, as it may be an interesting quality criterion for people.

**Comment by m0ru** [comment]
@ waffle discussion column tagging: what's the question to be discussed here? :)
(this is design work that's open imo)
if the question is whether or not we should (given time) then that's a definitive yes :)

**Comment by peacememories** [comment]
This has not had any discussion on it for 2 years. Maybe we should close it for now or move it to "later".
