### ISSUE TITLE
show recent needs in your region on landingpage 

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#815]
One use case is that I may only realize that I can help someone or discuss something when I see that there is the need to do so. The simplest approach to this is showing a recent needs list that the user can influence by time and region.

**Comment by fkleedorfer** [comment]
This is a feature that would be good on the startpage for non-logged-in users, but also something that a logged-in user may be interested in.  By definition, such a view is at first glance independent of owned needs, however, the owner app could save your preferences for this view, and it may also integrate data from your needs in order to sort/filter.

**Comment by quasarchimaere** [comment]
we "implemented" this via the "what's around"-button in the create need view, therefore i will mark this issue as done
