### ISSUE TITLE
link landingpage fotos/text with create-need view

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#816]
Everyone I've seen so far tries to tap the "I want something" or the "I have something to offer" foto or text. We should let users do that, send them to the create view, and make them register when they hit publish.

**Comment by fkleedorfer** [comment]
@quasarchimaere objects that asking to register before publishing can be seen as offensive, I agree.

**Comment by sigpie** [comment]
No longer applicable - landing page now contains create-need-view
