### ISSUE TITLE
New Post » Date Picker

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#82]
Time Picker: Switch from 12h-am/pm to 24h as default. If a browser local is set, use it's standard calender/time-format.

The picker should hold grey default values (current day, 00:00 to 23:59) which can be used, should the user haven't specified anything. This is more intuitive than e.g. "mm/dd/yyyy" where people need to know that e.g. the "mm" stands for "month input using exactly two digits".

**Comment by quasarchimaere** [comment]
duplicate
