### ISSUE TITLE
Consider generating markdown in owner app

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#820]
It may be wise to allow markdown in certain input fields. It's a good compromise between styling options and simplicity/restrictiveness. The most important feature this would enable are links. 

As I see it, the description and the textmessages should allow it.

Here is a datatype we can use: 
`http://ns.ontowiki.net/SysOnt/Markdown`

**Comment by quasarchimaere** [comment]
closing this issue in favor of #2139
