### ISSUE TITLE
Placeholder text still visible when request/messages/... exists

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#826]

**Comment by fkleedorfer** [comment]
This is a very serious regression, making the GUI almost completely unusable.
It is also a reminder to do more thorough integration testing: This change affected parts of the application in which we did not expect any change so they weren't checked.

**Comment by fkleedorfer** [comment]
Make a connection to someone, and go to the messages tab: it will be very hard even to find the handle of the conversation. Testing this might be obstructed by the messed-up matches/post detail veiw (#829)
