### ISSUE TITLE
Feedback for transitions in system-state: Animations

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#841]
We should start adding animations to visualise transitions of system state. E.g. requests that got accepted could move to the messages tab visually (or at least the tabs could blink), the password-field could [shake](https://docs.google.com/presentation/d/1lIMvkPXM2gsieAJ56aokX9QEKsEyTCHiHcJ8SjSU4DQ/pub?start=false&loop=false&delayms=3000&slide=id.gbc279793_050) if the pw wasn't correct, etc. These need to be designed first.

**Comment by fkleedorfer** [comment]
Done
