### ISSUE TITLE
Slim Owner-Server

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#842]
If we could move crypto the js-client – e.g. by using the [WebCryptoAPI](https://www.w3.org/TR/WebCryptoAPI/) via `window.crypto`) – the owner-server’s responsibilities are reduced to storing and synching the list of owned needs and the key across browser-tabs. This sounds like a profile for which there might exist a generic solution, that handles these responsibilities, assuming that the logic of what is stored/retrieved is moved to the javascript. 

http://todomvc.com lists `SocketStream` and `Firebase` under Real-Time. We might want to read up on these. Other solutions might be the backend to Meteor, JSON-LD-API, the reference backend for GraphQL. If you find more interesting leads, please add them below.

**Comment by fkleedorfer** [comment]
Cleaning up old issues - this is out of scope now
