### ISSUE TITLE
Messages are not saved or retransmitted when remote wonnode is down

### ISSUE THREAD

**Issue by heikofriedrich** [researchstudio-sat/webofneeds#855]
Step to test this behavior:
- start 2 owners and 2 wonnodes, one matcher to connect needs across wonnodes
- create need on wonnode 1
- create need on wonnode 2 
- receive match on wonnode/owner 2
- request conversation 
- accept conversation and start chatting
- shut down wonnode 1
- send messages from owner 2 to owner/wonnode 1
- restart wonnode 1 and continue chatting 
  => messages send while wonnode 1 was down are not saved on any of the wonnodes and after owner reload do not appear anymore

=> how to fix this? Saving messages on local wonnode and trying to retransmit in application layer when remote wonnode is there again?

**Comment by fkleedorfer** [comment]
As long as the messages are not wrongly reported as sent successfully, this is actually not a problem
