### ISSUE TITLE
matcher doesn't start up correctly on live

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#859]
noticed after merging #858, that on live, the matcher_service_1 container does not start properly because bigdata is missing. 
Starting bigdata, then matcher_service was enough. matcher_solr reconnected automatically

**Comment by heikofriedrich** [comment]
this occured already before, and after changing to docker compose ... i will have a look in this

**Comment by heikofriedrich** [comment]
Just updating to newest version (downloaded jar from website) of blazegraph is not an options now since it generates an internal error when the matcher service accesses the SPARQL endpoint

**Comment by heikofriedrich** [comment]
try this: https://github.com/blazegraph/database/issues/3
