### ISSUE TITLE
Recovery from session-timeout

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#898]
#897 allows recovery from a disconnect. The same needs to be done for session-timeouts. They should never cause a redirect, but simply pop out the login-dropdown and allow re-login anywhere.

 By polling isSignedIn in the messaging-agent (see commented-out code) the error-scenarios can be differentiated (request failed to send vs server returned an error-code) and then the appropriate actions dispatched -- lostConnection and sessionTimedOut respectively.

**Comment by m0ru** [comment]
Related to #834

**Comment by m0ru** [comment]
Hm, I'm struggling with forcing a timout. `won-owner-webapp/src/main/webapp/WEB-INF/web.xml` » `<session-config>` » `<session-timeout>` doesn't seem to have an effect. Could it be, that the heart-beats send on the web-socket keep the session alive indefinitely anyway?
EDIT: not even going offlinen for the specified session-timeout seems to have an effect. After reconnecting, requests to `isSignedIn` get HTTP-200s again.

**Comment by m0ru** [comment]
If you leave the page open for a longer time ~1h, will result in the heartbeat not getting send and querying `isSignedIn` yield a 401-response.

**Comment by fkleedorfer** [comment]
Closed in favour of #1885
