### ISSUE TITLE
Use Notification Messages

### ISSUE THREAD

**Issue by fsalcher** [researchstudio-sat/webofneeds#90]
Use a special message type (see HintNotification) of messages to inform the owner about events. This makes it easier to add information which are interesting to the owner but are not necessary to be stored in the message itself on the WON node (because the information is already present in another place). E.g. when a connect message arrives at the remote WON node the newly generated connection ID can be send to the owner with such a connect notification message and the on the WON node itself the ID is available within the need meta data.

**Comment by yanapanchenko** [comment]
Owner currently gets messages for all events of interest.
