### ISSUE TITLE
Property Check in the WonMessageBuilder

### ISSUE THREAD

**Issue by fsalcher** [researchstudio-sat/webofneeds#91]
Implement the checkProerties() method in the WonMessageBuilder. The method should check if all necessary properties are set for the specific MessageType. This information (which properties are necessary for which type) could be stored within the MessageType class itself.

**Comment by yanapanchenko** [comment]
We have now message type specific methods in WonMessageBuilder (e.g. setMessagePropertiesForConnect) - the method parameters correspond to all required properties.
