### ISSUE TITLE
Access control - redirect or placeholder

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#912]
atm, if you paste a link to e.g. a connection that you don't own, you see a broken post-info page. either we need to redirect at that point, or show a placeholder text that asks people to log in (make sure logging in doesn't cause a redirect then)

**Comment by quasarchimaere** [comment]
is this still an issue?

**Comment by m0ru** [comment]
Nope, it redirects to the langingpage atm
