### ISSUE TITLE
Inc Request: recovery for missclick on decline

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#916]
If you accidentally click on decline, there's no way of getting in touch with that person again, unless you get matched again. There's no undo button, no list of declined connections,...

**Comment by m0ru** [comment]
Nvm, it shows up in the feed as "conversation closed - click to reopen again". But the link doesn't work, and it needs a more predictable interface for this than the feed.

**Comment by quasarchimaere** [comment]
duplicated by #1055 -> closing this ticket
