### ISSUE TITLE
Type annotations

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#924]
A lot of the bugs we encountered in the js-client could have been avoided or been a lot easier to track down, if we had type-annotations in the code. 

There's two big solutions that allows us to add types gradually: typescript and flow. 

Typescript is a super-set of javascript and has a good eco-system of tools and existing type-definitions for third-party libraries. 

Flow is a type-checker for javascript, that together with a babel-plugin provides similiar functionality to typescript. It seems to provide a smoother transition (from js to annotated js) and is a bit sounder in it's type-checking, however lacks most of the tool-support.

By default I would go with typescript, because of the tool support and larger community. The situation is similiar to git vs mercurial in a way. Both do roughly the same thing, but one has been around for longer, is slightly less smooth but has better support all around

Anyway, starting to add type-informations mostly consists of a bit setup-effort up-front to get the transpiler/compiler to use the information, but I've already done so for a clone of our setup and typescript and could easily adapt the build-script. Imo, doing so would reduce the number of bugs, make debugging faster and would encode implicit knowledge (good for new developers/contributers).

**Comment by fkleedorfer** [comment]
FIrst attempt did not work, not in focus right now.
