### ISSUE TITLE
Pull medium.js and dependencies into bundle again

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#939]
Follow-up to #664 (see there for full details)

No solution could be found, that ensures that medium.js' dependencies are loaded before it and still bundles it. Currently the three scripts are included via `<script>`-tags, thus completely bypassing the transpiling/bundling process.

**Comment by quasarchimaere** [comment]
medium.js has been removed from our codebase -> therefore this ticket is no longer relevant
