### ISSUE TITLE
One need often missing in Posts view

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#942]
1. Create a new account
2. create two needs (hf: better 5 needs)
3. go to the posts view
4. refresh the page

Sometimes (many times actually) one of the two needs is missing, sometimes it's there.

**Comment by m0ru** [comment]
The list of owned needs received at page-load, contains the respective uri, but for some reason fetching it fails silently.

**Comment by heikofriedrich** [comment]
can reproduce this one locally. i create a new account and create 5 needs. then i refresh the post overview page => most of the times only 4 are loaded

**Comment by fkleedorfer** [comment]
Dug deeper and discovered really unexpected behaviour. To reproduce:
with an accout with a few needs (didn't try fewer than 5)
1. Log in
2. enable js debugging
3. Set a breakpoint in won-message-utils.js:406 in order to obtain the list of all needs conveniently. Here's the code at that point:
```
export function fetchOwnedData(email, curriedDispatch) {
    return fetchOwnedNeedUris()
        .then(needUris =>
            fetchDataForOwnedNeeds(needUris, email, curriedDispatch)
        );
}
```
4. when code execution stops there, copy the value of `needUris` to a global variable `myNeeds` via the js console
5. before you hit F8 to resume execution, set a breakpoint at linkeddata-service-won.js:881, so you can intercept the execution after the triples have been inserted. Here's the code at that point: 
```
 function addJsonLdData (uri, data) {
        return new Promise((resolve, reject) =>
            privateData.store.load("application/ld+json", data, function (success, results) {
                if (success) {
                    console.log('linkeddata-serice-won.js: finished storing triples ', data);
                    resolve(uri);
                } else {
                    reject('Failed to store json-ld data for ' + uri);
                }

            })
        );
    };
```
6. Now, every time, the execution reaches that breakpoint, execute this line of js code:
```
myNeeds.map(need => store4dbg.execute("select * where {<"+need+"> ?prop ?val }", function(x,y){console.log(need+ " has " +y.length + " triples")}))
```
You will see that with each call, as expected, the number of triples for another one of the uris will become >0. *However*, at some point, the insertion of the data for the current `uri` will set the number of triples for another uri to 0. Wait for that to happen. Then execute the following lines of code, after copying the uri whose triple count just went to 0
```
myUri = "[paste-the-uri-here]";
store4dbg.execute("select * where {<"+myUri+"> ?prop ?val }", function(x,y){console.log(myUri+ " has " +y.length + " triples")});
store4dbg.execute("select * where {<"+myUri+"> <http://purl.org/webofneeds/model#hasWonNode> ?val }", function(x,y){console.log(myUri+ " has " +y.length + " won:hasWonNode triples")});
store4dbg.execute("select * where {<"+myUri+"> <http://purl.org/webofneeds/model#hasBasicNeedType> ?val }", function(x,y){console.log(myUri+ " has " +y.length + " won:hasBasicNeedType triples")})
```

As you can see, querying for a graph pattern of the form `<uri> ?var1 ?var2` yields no results, but `<uri> <property> ?var1` does yield a result.

**Comment by fkleedorfer** [comment]
To see the actual query solutions in the debugging session, use this js expression:
```
myNeeds.map(need => store4dbg.execute("select * where {<"+need+"> ?prop ?val }", 
    function(x,y){
      console.log(y.map(triple => JSON.stringify(triple)))
    }))
``

**Comment by fkleedorfer** [comment]
The corruption of the rdfstore always seems to happen upon the 5th insertion of JSON-LD data.

**Comment by fkleedorfer** [comment]
I think the culprit is `Lexicon.Lexicon.prototype.registerBlank` and  `Lexicon.Lexicon.prototype.resolveBlank` in rdfstore_js.js: the index structures do not want it to return a string - it should always be an integer. No idea why the return values are explicitly converted to a string: 
```
Lexicon.Lexicon.prototype.registerBlank = function(label) {
    var oid = this.oidCounter;
    this.oidCounter++;
    var oidStr = ""+oid;
    this.OIDToBlank[oidStr] = true;
    return(oidStr);
};

Lexicon.Lexicon.prototype.resolveBlank = function(label) {
//    @todo
//    this is failing with unicode tests... e.g. kanji2

//    var id = label.split(":")[1];
//    callback(id);

    var oid = this.oidCounter;
    this.oidCounter++;
    return(""+oid);
};
```
however, changing them to return an integer fixes all test cases I've set up:
```
Lexicon.Lexicon.prototype.registerBlank = function(label) {
    var oid = this.oidCounter;
    this.oidCounter++;
    var oidStr = ""+oid;
    this.OIDToBlank[oidStr] = true;
    return(oid);
};

Lexicon.Lexicon.prototype.resolveBlank = function(label) {
//    @todo
//    this is failing with unicode tests... e.g. kanji2

//    var id = label.split(":")[1];
//    callback(id);

    var oid = this.oidCounter;
    this.oidCounter++;
    return(oid);
};
```
The code has been changed in the rewrite of rdfstore-js (>0.9) not to return anything at all, so I guess it's not an issue in that version any more.
