### ISSUE TITLE
No visual feedback when connecting from a match

### ISSUE THREAD

**Issue by heikofriedrich** [researchstudio-sat/webofneeds#952]
After requesting a conversation by clicking on a match, entering a text and sending it there is no feedback that the request was actually sent. the match doesnt disappear like it used to be. it just stays there. after page reload however it disappears

**Comment by quasarchimaere** [comment]
should not be a problem anymore, or at least i couldnt reproduce it, matches disappear just like they used to, maybe a little slow but they still do.

**Comment by heikofriedrich** [comment]
ok seems to work on master now, i will close this one

**Comment by heikofriedrich** [comment]
doesnt work on matchat.org

**Comment by heikofriedrich** [comment]
no errors or warnings in owner or wonnode. however there is log output is js console:
"got response for CONNECT: undefined" => message-actions-js:126 successfulConnect => the precessed event has no property "hasMessageType" and no property "isRemoteResponseTo". Why?

**Comment by heikofriedrich** [comment]
is the code in the if statement ever executed? it seems to me it is not. Also there are these refactor TODOs there. if you actually execute the code in the if statement (by using the right selection for "isRemoteResponseTo") then there are effects and popups in the gui that should not be there, so i guess this code should not be executed?! 

@quasarchimaere  can you check if we can delete this whole function then or what we do about the refactoring

**Comment by fkleedorfer** [comment]
Fixed
