### ISSUE TITLE
In map view is often shown grey area

### ISSUE THREAD

**Issue by heikofriedrich** [researchstudio-sat/webofneeds#953]
![grafik](https://cloud.githubusercontent.com/assets/7766279/22420366/6d978762-e6e2-11e6-8d2e-00c77bde2b27.png)

**Comment by m0ru** [comment]
Seems to be mainly occuring in the post-detail view. On reload, the map doesn't zoom after the need-data finishes loading. If one clicks on "show" afterwards, the gray area remains visible, as seen above.

**Comment by m0ru** [comment]
We need to call `map.invalidateSize()` when the map becomes visible.
