### ISSUE TITLE
Do not print User password in log file!

### ISSUE THREAD

**Issue by heikofriedrich** [researchstudio-sat/webofneeds#956]
In class "won.owner.model.User" method toString() prints the password. This function is called in "won.owner.web.websocket.WonWebSocketHandler" in method sendMessageForSession() => logger.warn(MessageFormat.format("caught exception while trying to send on session {1} for needUri {2}, " +
          "user {3}", session.getId(), needUri, user), e);

**Comment by m0ru** [comment]
why does the owner-server even get it in plain text?

**Comment by heikofriedrich** [comment]
no its not plaintext, its the hash

**Comment by m0ru** [comment]
ah, ic ^^
