### ISSUE TITLE
Fix source-maps on matchat.org

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#968]
For some reason the sourcemaps on <https://www.matchat.org/owner/> are currently broken (see image):

![borken_sourcemaps](https://cloud.githubusercontent.com/assets/1730492/22593245/f644d0ae-ea1d-11e6-8361-2392e9083269.PNG)

To test for working source-maps, you can do several things:

* ctrl+p -> app_jspm.bundle.js -> set a break-point in any of our code (not library code) -> it should jump to the corresponding es6-file (i.e. the code we actually wrote)
* open any of the es6-files -> set a breakpoint somewhere -> wait for execution to run into it -> check if you have access to the variables that should be declared at that point (e.g. by looking at the scope-inspector or typing the variable name in the console). you might have to set several breakpoints so that one actually is on top of executed code.
* look at the source-maps themselves in the `./generated`-folder.

**Comment by heikofriedrich** [comment]
i deployed matchat newly from the new jenkins server, it works for me now. 
@m0ru could you also test it then we can close this issue

**Comment by m0ru** [comment]
Jep, works again. :)
