### ISSUE TITLE
When creating needs sometimes hints from the debug bot cannot be added

### ISSUE THREAD

**Issue by heikofriedrich** [researchstudio-sat/webofneeds#971]
The hints are not added in the GUI, also not after reload, but they are available as hints in linked data added to the needs connection.

js exception in console:

First execption:
> Uncaught TypeError: Cannot read property 'get' of undefined
>     at selectors.js:94
>     at immutable.js:1296
>     at immutable.js:3677
>     at immutable.js:1942
>     at ValueNode.iterate (immutable.js:2309)
>     at BitmapIndexedNode.iterate.HashArrayMapNode.iterate (immutable.js:2302)
>     at src_Map__Map.__iterate (immutable.js:1940)
>     at src_Set__Set.__iterate (immutable.js:3677)
>     at groupByFactory (immutable.js:1294)
>     at src_Set__Set.groupBy (immutable.js:4507)

Second execption:
> Uncaught (in promise) TypeError: Cannot read property 'get' of undefined
>     at selectors.js:70
>     at immutable.js:1296
>     at immutable.js:3677
>     at immutable.js:1942
>     at ValueNode.iterate (immutable.js:2309)
>     at BitmapIndexedNode.iterate.HashArrayMapNode.iterate (immutable.js:2302)
>     at src_Map__Map.__iterate (immutable.js:1940)
>     at src_Set__Set.__iterate (immutable.js:3677)
>     at groupByFactory (immutable.js:1294)
>     at src_Set__Set.groupBy (immutable.js:4507)

**Comment by fkleedorfer** [comment]
Fixed AFAIK.
