### ISSUE TITLE
bundle scss along with app

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#976]
Apparently would include our scss in the bundle ([howto](https://advancedweb.hu/2017/01/17/jspm/)) using the [sass-plugin for jspm](https://github.com/mobilexag/plugin-sass) to further reduce the number of http-requests.

This might cause flashes of unstyled content though, so beware.

**Comment by m0ru** [comment]
another potentially interesting guide: <https://ilikekillnerds.com/2016/02/the-definitive-guide-to-bundling-exporting-in-aurelia/>

**Comment by fkleedorfer** [comment]
cleaning up old issues
