### ISSUE TITLE
Optimise images to speed up page-load

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#978]
Seve Edson gives an example of a gulp-task to optimise images -- svgs and bitmaps -- in [this blogpost](https://steveedson.co.uk/gulp/advanced-tasks/). We could add this to our build. We only need to make sure, the viewports- and diagonal layout in the svg-spritesheet still remain, as they're necessary for the icons to work.

**Comment by m0ru** [comment]
There's also new webplattform features for responsive images, that allow us to serve smaller images for smaller screens, in particular `srcset` and `<picture>`.

**Comment by quasarchimaere** [comment]
is this still an issue? if not let us close it

**Comment by m0ru** [comment]
We can't use the gulp plugins anymore, but I'm sure there's some for webpack. Atm all SVGs are optimized using the Inkscape export option. However, it would be nicer if it wasn't possible to forget this (i.e. if the build automatically took care of this). But it's certainly a "Later".

**Comment by fkleedorfer** [comment]
I agree, much later. If this is a thing we should seriously consider, please add it to the refactoring doc https://github.com/researchstudio-sat/webofneeds/blob/master/documentation/future_work/refactoring.md, linking to this isssue.
