### ISSUE TITLE
Automatically notify google of changes to the build

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#979]
If we query `http://www.google.com/webmasters/tools/ping?sitemap={URL TO YOUR SITEMAP.XML}` and `http://www.bing.com/webmaster/ping.aspx?siteMap={URL TO YOUR SITEMAP.XML}` to our deploy-script, we can automatically notify google and bing of updates to our site and make them reindex it again.

@fkleedorfer said we should probably wait a bit with this.

**Comment by fkleedorfer** [comment]
Done
