### ISSUE TITLE
broken login gui

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#985]
On 1+1 mobile

**Comment by fkleedorfer** [comment]
![tmp_12259-img_20170209_131824-39692133](https://cloud.githubusercontent.com/assets/551624/22783168/ebb5c880-eeca-11e6-8c1d-1312c7f926d5.jpg)

**Comment by m0ru** [comment]
![normalappimage 4](https://cloud.githubusercontent.com/assets/1730492/22786238/f73958ea-eed7-11e6-8a91-4cb5fdf9392d.png)
up close

**Comment by quasarchimaere** [comment]
fixed
