### ISSUE TITLE
Color highlight hashtags in title

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#986]
![hashtags](https://cloud.githubusercontent.com/assets/1730492/22786297/39411eda-eed8-11e6-9f58-63e07e1cb7b3.png)

as they have a special semantic role and are outside the normal text-flow we might want to style hashtags differently (e.g. grey them out slightly, make them into links,....)

**Comment by quasarchimaere** [comment]
no longer relevant -> tags are not parsed from title or description any longer
