### ISSUE TITLE
timeout not always detected

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#989]
If you leave the browser open for a while, your session will timeout. There should be visual feedback (and the option to re-login) when this happens. Atm you need to reload the page to notice this happened / recover from this state

**Comment by maxstolze** [comment]
We already have the feature now

![lost_connection](https://user-images.githubusercontent.com/32457902/40708065-bf40c1e4-63f2-11e8-8de4-edbdf8ee09ed.png)

**Comment by m0ru** [comment]
Afaik this is only triggered if an HTTP-request fails or the socket dies. Does the socket die by itself if the pulse-messages don't arrive?

**Comment by m0ru** [comment]
yep it does, so this is really fixed.
