### ISSUE TITLE
timeout shouldn't cause data loss

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#990]
Atm it's possible, if you take your time to write a need, that only when posting you realize the session has timed out, you have to reload and lose all data while doing so.

**Comment by maxstolze** [comment]
I can't reproduce the bug anymore.
Close?

**Comment by m0ru** [comment]
To reproduce: start editing a need, go for a lunch break, come back and hit post (or alternatively change the server config so it drops your session really fast) .

The problem was that the timeout was only detected when an HTTP-request is send or the websocket dies (i.e. issue #989)

**Comment by fkleedorfer** [comment]
Closed in favour of #1885
