### ISSUE TITLE
Users don't dare to post

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#993]
In many cases, users report they would like to post sth but don't know how to write it or what kind of content to post.

**Comment by m0ru** [comment]
@ waffle discussion column tagging: what's the question to be discussed here? :)
(this is design work that's open and that someone needs to tackle either alone or together in an ideation session, e.g. using the design studio method)
if the question is whether or not we should (given time) then that's a definitive yes :)

**Comment by quasarchimaere** [comment]
statement and not an issue -> closing this issue (whats new and whats around auto creation)
