### ISSUE TITLE
costly ng-show

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#994]
[ng-show purposedly is rather costly](http://www.codelord.net/2015/07/28/angular-performance-ng-show-vs-ng-if/), as the hidden directives' watch-expressions are still evaluated. We should take a deeper look into that, to what extend it applies to our code-base and whether or not all our directives would still work if we'd switch to ng-if (afaict they should, as they shouldn't have internal state transitions, i.e. should only render the redux-state to the DOM). Also see the "when to switch and when not to switch"-section in the linked article.

**Comment by fkleedorfer** [comment]
too old
